### ISSUE TITLE
frost-server-mqtt component stops working with "Java heap space" Error but doesn't crash

### ISSUE THREAD

**Issue by oldluke92** [FraunhoferIOSB/FROST-Server#1000]
I got the same issue mentioned in https://github.com/FraunhoferIOSB/FROST-Server/issues/269#issuecomment-819358131.

The frost-server-mqtt component stops responding to requests or publishing events and logs errors like
`Exception in thread "pool-8-thread-5" java.lang.OutOfMemoryError: Java heap space`
But it doesn't crash - in which case kubernetes would restart it.
This started happening after setting Resource declarations to the mqtt deployment. Defined resources are:

```yaml
        resources:
          limits:
            cpu: "2"
            memory: 5Gi
          requests:
            cpu: 250m
            memory: 2Gi
```
The defined Memory limit is never reached though and it seems the service tries to deal with the 2Gi "requests" it was set to.
![Screenshot from 2022-06-24 08-52-36](https://user-images.githubusercontent.com/22979824/175481429-26e4526f-037b-44fa-9767-63c9a331f82e.png)

When there were no limits applied at all, the service consumed more and more memory over Time, till using up most of the kubernetes workers memory (which it ofc has to share with other services ...)

I also noticed that the db started consuming more memory exactly around the time the mqtt-service stopped working aswell as that there are regular CPU usage spikes over extended periods of time for the mqtt-service:
![image](https://user-images.githubusercontent.com/22979824/175484327-480941ec-73f9-4e82-b2b6-e4aaf750ed15.png)

So my questions are:
How should the resource definitions be set so this doesn't happen ?
Will the "frost-server-mqtt consuming all the memory available on the worker node" issue be fixed in a future version ?

The used frost-server-mqtt image is docker.io/fraunhoferiosb/frost-server-mqtt:1.14.0

**Comment by hylkevds** [comment]
Do you have clients that use cleanSession=false ?
If so, then that's probably the cause of the issue, moquette never cleans up those sessions. The just released version 1.15.1 and 2.0.2 use a pre-release of moquette that adds a session timeout for inactive sessions, to avoid this problem.
