### ISSUE TITLE
Question: find oldest and newest observation resultTimes, highest/lowest result etc

### ISSUE THREAD

**Issue by rduivenvoorde** [FraunhoferIOSB/FROST-Server#101]
I tried to find the boundaries of my Observations  time ranges by using a filter query like:
v1.0/Observations?$filter=resultTime eq mindatetime()
or
v1.0/Observations?$count=true&$filter=resultTime eq mindatetime()&$top=1
because I thought mindatetime/maxdatetime would give me the oldest datetime in my data:
But there is no result:
```
{
  "@iot.count" : 0,
  "value" : [ ]
}
```

So apparently I misinterpret mindatatime?

I ended up with:
v1.0/Observations?$top=1&$orderby=resultTime
which is fine and works :-)

But I was wondering what was the best way to find the min/max value of the properties of objects. 
I reckon as long as there is an index on it, this probably works fine?
Or is there a better way?

**Comment by hylkevds** [comment]
It's a bit counter intuitive, but mindatetime holds the minimum possible time, not the minimum occurring time.

If you want to get the minimum or maximum resultTime for a given Datastream, you can get it from the resultTime field of the Datastream. In other words, the minimum time that the server can store.

If you do a lot of queries on Observation/resultTime, you may want to add one or more database indices on that column.

**Comment by hylkevds** [comment]
Of course, the easiest way to get the minimum or maximum of a field is to use oderby on that field and get the first element (`$orderby=result asc&$top=1` or `$orderby=result desc&$top=1`)
