### ISSUE TITLE
datastream POST/PATCH ignores phenomenonTime and resultTime

### ISSUE THREAD

**Issue by scottlimmer** [FraunhoferIOSB/FROST-Server#102]
I believe this is intentional as the the phenomenon/result start/end times are updated by pgsql triggers on observation insert. 

However, I wasted a lot of time on this, assuming there was a date format conversion issue. This was due to the application appearing to process phenomenonTime/ResultTime when they are provided by way of throwing validation errors if the timestamps are incorrect. 

Suggest either: 

- /Datastreams endpoint return message explaining that user provided time-based fields will be ignored and automatically updated on observation insert, or
- /Datastreams endpoint accepts and insert/updates time-based fields

**Comment by hylkevds** [comment]
On a (Multi)Datastream, the fields observedArea, phenomenonTime and resultTime are server generated, though it is not explicitly stated in the specification that they are.
I suppose we could make them user-editable.

**Comment by scottlimmer** [comment]
I did modify the DatastreamFactory::insert method to do this for our purposes. I'm happy for you to have a look at that if it's of any use (I'm not suggesting its a complete solution). Its in feature/store-datastream-time in my fork

**Comment by hylkevds** [comment]
Those are indeed the required changes. It's a pretty trivial change, though I'm thinking it might be good to make it configurable. I can imagine there are use-cases where it is important the Datastream/phenomenonTime is not accidentally set to something incorrect by a user.

**Comment by ch08532** [comment]
> I did modify the DatastreamFactory::insert method to do this for our purposes. I'm happy for you to have a look at that if it's of any use (I'm not suggesting its a complete solution). Its in feature/store-datastream-time in my fork

Thanks for this...the specification does not describe this but if one needs to clear observations then one must be able to null these fields.  One could debate that the observedArea needs to be reset as the OA field spatially computed based on the extent of the FOIs.

The correct fix is to have FROST automatically clear/reset these three fields when a DELETE observations operation is called.

**Comment by hylkevds** [comment]
Making the server-generated properties of (Multi)Datastreams editable can now be done with an option: [plugins.coreModel.editableDsProperties](https://fraunhoferiosb.github.io/FROST-Server/settings/plugins.html#coremodel)
