### ISSUE TITLE
Unknown field: MultiDatastreams

### ISSUE THREAD

**Issue by newinnovations** [FraunhoferIOSB/FROST-Server#1022]
I'm getting acquainted with the FROST-Server and executed the docker quick start tutorial from https://fraunhoferiosb.github.io/FROST-Server/deployment/docker.html 

When posting the demoEntities.json to the server I get:

`
curl -X POST -H "Content-Type: application/json" -d @demoEntities.json http://localhost:8080/FROST-Server/v1.1/Things
`

`
{"code":400,"type":"error","message":"Unknown field: MultiDatastreams\n at [Source: (BufferedReader); line: 1, column: 2835]"}
`

No error message appears in the server logs.

**Comment by hylkevds** [comment]
Did you enable the MultiDatastream plugin?
```
plugins.multiDatastream.enable=true
```

**Comment by newinnovations** [comment]
No I did not. Did I miss part of the instructions?

**Comment by hylkevds** [comment]
Good point, given the docker-deployment demo, the docker compose file should add that line by default.

**Comment by newinnovations** [comment]
Adding `plugins_multiDatastream_enable=true` to the docker compose file did indeed solve it. Thanks.

**Comment by hylkevds** [comment]
Thanks for confirming. I've updated the docker-compose files.
