### ISSUE TITLE
CreateObservations endpoint doesn't always close DB connection

### ISSUE THREAD

**Issue by scottlimmer** [FraunhoferIOSB/FROST-Server#104]
I added a unique resultTime, datastream_id constraint the observations table to avoid duplication when bulk inserting historic observations. This could then trigger an PSQLException that was uncaught. Unlike the other execute methods in the Service class, executeCreateObservation is missing the finally statement from the try catch block that ensure the database connection is closed.

PR: #103

**Comment by hylkevds** [comment]
Thanks for the PR! I've merged it and will release an update of the 1.9 branch soon.

**Comment by hylkevds** [comment]
I released version 1.9.1 that has the fix.
