### ISSUE TITLE
Problems deploying FROST Server HTTP in a Tomcat / Postgres environment 

### ISSUE THREAD

**Issue by ChrisMalewski** [FraunhoferIOSB/FROST-Server#1043]
Dear FROST-Team, we want to deploy FROST server to our enterprise environment. However, the documentation leads only to a certain point. We figured out to setup up the FROST server, but it is somehow misbehaving. Thank you so much for your help.

We tried the following setups:
- FROST-Server.HTTP-2.0.2.war
- Tomcat 10 (using Jakarta Migration Tool)
- Tomcat 9 
- OpenJDK 17
- postgresql-42.4.0.jar (and postgresql-42.2.16.jar)
- postgis-jdbc-2.5.1 (and postgis-jdbc-2.4.0.jar)
- Postgres 12.6 with PostGis 3.0

My questions are: 
1. **How can we use a custom Database schema other than public?** 
We want to use a custom DB schema, e,g. "frost". I figured out, how to configure the schema within the context.xml. The database role is the schema owner and does not have access to the public schema.
 `
 <Resource name="jdbc/sensorThings" auth="Container" type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
		url="jdbc:postgresql://192.168.1.1:5432/mydb01?currentSchema=frost" .../>`
When frost should initiate or update the schema from the WebGUI (/frost/DatabaseStatus), the generation of tables with a geom column fails as frost does not find the postgis extensions.
Generating the tables manually as the schema owner from sql works without problems. Same is with inserting data into tables with a geom attribute:
POST /frost/v1.1/Locations
`{
  "name": "PA",
  "description": "PA",
  "encodingType": "application/vnd.geo+json",
  "location": { "type": "Point", "coordinates": [7.3, 51.08]  }
}`

Fails with:
`10:07:20.907 [http-nio-8099-exec-19] ERROR d.f.i.i.frostserver.service.Service - Failed to handle request (details in debug): SQL [insert into "LOCATIONS" ("ENCODING_TYPE", "DESCRIPTION", "NAME", "GEOM", "LOCATION") values (?, ?, ?, ST_Force2D(ST_Transform(ST_GeomFromGeoJSON(?), 4326)), ?) returning "LOCATIONS"."ID"]; FEHLER: Funktion st_geomfromgeojson(character varying) existiert nicht
  Hinweis: Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.
  Position: 130`

2. **Is it possible to disable write access with server settings, e.g. POST, PATCH, DELETE?**
3. **Is it possible to disable org.eclipse.paho.client in an HTTP only environment?** 
It checks the presence of an MQTT Message Bus every minute and fills the catalina log files. 
`10:04:56.056 [    pool-12-thread-1] ERROR d.f.i.i.f.messagebus.MqttMessageBus - 
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: mosquitto
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
	... 1 common frames omitted`
4. **Is it possible to log the Logger Output to a dedicated Folder and file, e.g. using a logback.xml?** 
My attempts placing a logback.xml stops the frost service from starting.

**Comment by hylkevds** [comment]
Hi Chris,

1.  As you noticed, Frost will need to be able to access the PostGis extensions. This means that either:
    1.  FROST needs to be able to access the schema that the extensions are installed in, and this schema needs to be in the search path. e.g. `?currentSchema=frost,postgis`
    2. The PostGIS extensions need to be installed in the frost schema. [Moving the PostGIS extensions](https://postgis.net/2017/11/07/tip-move-postgis-schema/) is possible.
2. Yes, if you activate an auth module, you can configure write access. See the [Auth section](https://fraunhoferiosb.github.io/FROST-Server/settings/auth.html) in the documentation. There are currently two auth modules, for basic auth and OpenID connect using KeyCloak. Both modules can be configured to allow anonymous read access.
3. If you have only one FROST-HTTP component deployed you can "disable" the message bus by setting the option `bus.busImplementationClass` to `de.fraunhofer.iosb.ilt.sta.messagebus.InternalMessageBus`.
4. What error message do you get when adding a custom logback.xml? Did you try replacing the existing logback.xml?

**Comment by ChrisMalewski** [comment]
Hi Hylke,

thank you very much for your help. All is working fine.

1. Here I had to configure the public schema: `?currentSchema=frost,public`
2. I have not testet that solution yet. The DB layer configures a role with read-only access. However, is it possible to completely drop write access at the service layer? Our setup is configured such that we want to run 2 FROST server instances. One is accessible only within the intranet. Only this instance may write new data. A second one should be accessible via internet. The latter should only be reading data. 
3. That worked. However, when I call `/frost/v1.1` the JSON response still proposes an MQTT endpoint.
4. There is no existing logback.xml. However, that point was my fault as I configured the logback.xml with an very old settings. A new one works as expected.

**Comment by hylkevds** [comment]
1. Excellent.
2. Yes, for that second instance you can add a [basic auth](https://fraunhoferiosb.github.io/FROST-Server/settings/auth.html#auth-settings) module, and empty the "USERS" and "USER_ROLES" tables. That way no one can log in, and thus no one can write. If you enable allowAnonymousRead, then everyone can read.
3. You can set `mqtt.Enabled` to `false` to tell the HTTP component that there is no MQTT.
4. Excellent.

**Comment by ChrisMalewski** [comment]
2. That workaround solves the issue. However, we will end up with two additional schemas. One for the internal write access and an empty one for disabling external write access. Maybe we will see a param that disables write access right away in a future release.

Thanks so much for your help.

**Comment by hylkevds** [comment]
Those two HTTP instances can access the same frost schema. The internal one without authentication will simply ignore the USERS and USER_ROLES tables.

**Comment by ChrisMalewski** [comment]
Sorry, I did not mention that the internal instance must also have an access restriction and thus needs an authentication mechanism. But rethinking the configuration, the following should work: 

In schema 'frost' we persist a role with the value 'write', and there is no role with 'no-write' 

External Read Only Instance content.xml:
`<Parameter override="true" name="auth.role.create" value="no-write" />`
`<Parameter override="true" name="auth.role.update" value="no-write" />`
`...`

Internal Write Instance content.xml:
`<Parameter override="true" name="auth.role.create" value="write" />`
`<Parameter override="true" name="auth.role.update" value="write" />`
`...`

How does FROST Server behave, when we configure a parameter with an empty value?
`<Parameter override="true" name="auth.role.create" value="" />`
Does the default schema definition restricts the role value in the Database to be not null or empty? This woulld prevent the case that a role is added with the value 'no-write' by accident.

**Comment by hylkevds** [comment]
Yes, that would work. I don't think it's a good idea to use an empty role string. It should work fine, but empty strings may cause unforeseen issues.

Instead of calling the role "no-write" it's probably better to name the role "no-not-assign", since it's a role that should never be assigned to any users. With a name like "no-write" someone may mistake it for the "read" role, and give it to a user that should not be able to write...
