### ISSUE TITLE
GeoJSON output is missing the <type> attribute for the feature elements

### ISSUE THREAD

**Issue by rhzg** [FraunhoferIOSB/FROST-Server#1069]
I believe the $resultFormat=GeoJSON out is missing the type attribute in the features list

> features": [{
 "type": "Feature",                <=========== THIS ONE IS MISSING
"properties": {...},
"geometry": {...]}
}, ...

**Comment by hylkevds** [comment]
Seems to be caused by https://github.com/opendatalab-de/geojson-jackson/issues/50
