### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#107]
Hi,
    I tried to compile the project and I got this.
![image](https://user-images.githubusercontent.com/26135719/54256087-bb84d880-4595-11e9-9121-01ef2e566706.png)
Using macOS 10.14.1
           maven 3.5.4
           java 1.8.0_181

How can I fix this? 
Any advice would be great.
Thanks!!!

**Comment by hylkevds** [comment]
Never make screenshots of errors, copy and past the actual text instead. And not just the last bit, but also the bit where the error actually occurred.

That said, to compile the latest development version, you need Java 11.

**Comment by smilehappy126** [comment]
I see. Thanks for replying.  Problem solved.
