### ISSUE TITLE
Geojson output is missing ' "type":"Feature" ' member, making it 'not valid' in some clients

### ISSUE THREAD

**Issue by rduivenvoorde** [FraunhoferIOSB/FROST-Server#1088]
Playing around / testing queries with one or your servers, I was using the following URL to get one Datastream/Location:

https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams?$top=1&$filter=ObservedProperty/name%20eq%20%27SO2%27&$expand=ObservedProperty,Thing/Locations&$resultFormat=GeoJSON

But saving it to disk en trying to load it in QGIS did NOT show the feature.
(though loading it as a service-url, it did....)

But then trying to save it locally and view it in https://geojson.io/ also did not show me the point.

Going to https://geojsonlint.com/ it appears that it is missing the (apparently mandatory) "type":"Feature" part of every Feature:
```
Line 4: GeoJSON features must have a type=feature member
```

Attached both versions, the version retrieved via the url above and a fixed one:

[test_geojson.zip](https://github.com/FraunhoferIOSB/FROST-Server/files/9350465/test_geojson.zip)

It is very well possible that airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de is running an older server? But apparently my other geojson issue: https://github.com/FraunhoferIOSB/FROST-Server/issues/725 is fixed :-)

**Comment by hylkevds** [comment]
Yep, that server was not updated to 2.0.3 yet. Thanks for the notification, updated now.
