### ISSUE TITLE
$select=Datastreams not working

### ISSUE THREAD

**Issue by sgrellet** [FraunhoferIOSB/FROST-Server#109]
Trying to slim down the amount of info down to a bare minimum : say name and the 'links' part.
$select=name,Datastreams not working (and nor its friends)

By links I mean

"Datastreams@iot.navigationLink": "https://brgm.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0/Things(21111)/Datastreams",
"Locations@iot.navigationLink": "https://brgm.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0/Things(21111)/Locations",
 "HistoricalLocations@iot.navigationLink": "https://brgm.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0/Things(21111)/HistoricalLocations",
 "@iot.id": 21111,
 "@iot.selfLink": "https://brgm.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0/Things(21111)"
 
Seems it needs to add 'id' in the $select=id, name, Datastreams for this to work in FROST 1.9.3

Link to INSIDE-information-systems GitHub: INSIDE-information-systems/SensorThingsAPI#8

**Comment by hylkevds** [comment]
Thanks for the report. 
It is now fixed in the master branch.
