### ISSUE TITLE
code":400,"type":"error","message":"Query is not valid after / Role NONE required for request GET /FROST-Server/v1.1/Things

### ISSUE THREAD

**Issue by qwertZ1984** [FraunhoferIOSB/FROST-Server#1112]
Hello,
i get this Error:
Error 400: {"code":400,"type":"error","message":"Query is not valid: Encountered \" \"state \"\" at line 1, column 1.\nWas expecting:\n \"$\" ...\n "}
after i auth with Keycloak.
The log printed: d.f.i.i.f.a.k.KeycloakFilter - Role NONE required for request GET /FROST-Server/v1.1/Things
Any suggestions?

Regards

**Comment by qwertZ1984** [comment]
I figured out the Problem.
in my values.yaml "allowAnonymousRead" was "true". Set it to false and authentication  with Keycloak works fine.

**Comment by hylkevds** [comment]
Which version are you using? It should also work with `allowAnonymousRead` set to `true`.

**Comment by qwertZ1984** [comment]
I'm using 1.14.

**Comment by hylkevds** [comment]
The error message indicates you have an incorrect URL:
```
Query is not valid: Encountered "state" at line 1, column 1.
Was expecting:
 "$" ...\n "
```
So somehow you have the text `state` in your URL, and that is not a valid SensorThings url parameter.

The log entry `d.f.i.i.f.a.k.KeycloakFilter - Role NONE required for request GET /FROST-Server/v1.1/Things` is a debug message (you really should always copy the entire line) and not an error. It just states that the request requires role "none", which means the request is always allowed.

**Comment by hylkevds** [comment]
Closing due to no further activity.

**Comment by qwertZ1984** [comment]
Hello,
you are right. I have the text `state `in my URL: `%2FFROST-Server%2Fv1.1&state=9bdd9849-9cbe-46ae-9e7d-3a0c981b549b&login=true&scope=openid`.
This is the redirect URL from keycloak auth realm. 
With `allowAnonymousRead ` set to `true` no auth is possible against keycloak.
