### ISSUE TITLE
Automatically generated FeatureOfInterests are not emitted on MQTT

### ISSUE THREAD

**Issue by riedel** [FraunhoferIOSB/FROST-Server#113]
Haven't checked in recent versions, but last time I checked if a FeatureOfInterest is generated based on a location MQTT does not emit it. (Which actually makes it impossible to work around #100)

**Comment by hylkevds** [comment]
Good point, I'll look into that.

**Comment by hylkevds** [comment]
It should now publish generated FoIs on MQTT.
