### ISSUE TITLE
Bug when working with ResultQuality and pooq-PresistanceManager

### ISSUE THREAD

**Issue by GDue** [FraunhoferIOSB/FROST-Server#114]
There seems to be a bug in 
de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.factories.ObservationFactory

Line 210 tries to insert a result quality into the newly created observation -->
            insert.put(table.resultQuality, newObservation.getResultQuality().toString());
As easily can be seen it uses ".toString()" on the result quality (which has been parsed correctly up to then).

Later (Line 129, same file) the routine "readResultQuality" is called which tries to parse the above created string as json. unfortunatelly the above way to stringify using .toString generates a string not compatible with JSON.

BR
Gerhard

**Comment by hylkevds** [comment]
Good catch, another thing the conformance test doesn't test.
