### ISSUE TITLE
Filtering on phenomenontime interval yields incorrect results

### ISSUE THREAD

**Issue by buddemat** [FraunhoferIOSB/FROST-Server#116]
When I execute a filter query intended to return all Datastreams that have a phenomenon time greater than the last minute

<MYFROSTSERVER>/v1.0/Datastreams?$filter=phenomenonTime%20gt%20now()%20sub%20duration%27PT60s%27

the result also contains datastreams without any observations (i.e. that do not have a phenomenonTime at all).

I would consider this incorrect behaviour?

**Comment by hylkevds** [comment]
That does indeed sound incorrect.
Which version are you using?

**Comment by buddemat** [comment]
We are running v1.9

**Comment by hylkevds** [comment]
This should now be fixed in master and be part of the next release. If not, please re-open.
