### ISSUE TITLE
FROST behind keycloak help

### ISSUE THREAD

**Issue by cornelius-agrippa** [FraunhoferIOSB/FROST-Server#117]
Hello,

I’m trying to configure FROST Server behind a keycloak setup however I’m having some trouble with 403 Forbidden Status errors. To configure everything I mainly followed the [Auth Guide](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/auth.adoc). 

It works fine for GET requests (because I have `auth.allowAnonymousRead` set as true) but I can’t seem to reach anything else. All my other applications behind keycloak work fine too.

My FROST Server WAR is running on Tomcat 8.5, [running the latest compiled version](https://bintray.com/fraunhoferiosb/Maven/download_file?file_path=de%2Ffraunhofer%2Fiosb%2Filt%2FFROST-Server%2FFROST-Server.HTTP%2F1.9%2FFROST-Server.HTTP-1.9.war). And the relevant configs that I have changed in `context.xml` are as follows:

```XML
<Parameter override="false" name="http.cors.enable" value="true" description="If true, a filter is added that allows cross-origin requests."/>
<!-- authentication/authorisation setting -->
<Parameter override="false" name="auth.provider" value="de.fraunhofer.iosb.ilt.frostserver.auth.keycloak.KeycloakAuthProvider" description="The java class used to configure authentication/authorisation."/>

<Parameter override="false" name="auth.allowAnonymousRead" value="true" description="If true, anonymous users are allowed to read (GET) data."/>

<Parameter override="false" name="auth.keycloakConfigUrl" value="https://(my keycloak server)/auth/realms/devrealm/clients-registrations/install/frost-server" description="The URL on the Keycloak server that the configuration can be downloaded from." />
<Parameter override="false" name="auth.keycloakConfigSecret" value="(the super secret key that keycloak provided me)" description="The secret required for downloading the keycloak config." />
```

When launched, everything seems to run fine, and FROST ends the log with:
```
18:14:38.153 [localhost-startStop-1] INFO   d.f.i.i.f.auth.keycloak.Utils - Fetching Keycloak config from server: https://(my keycloak server)/auth/realms/devrealm/clients-registrations/install/frost-server
18:14:39.161 [localhost-startStop-1] INFO   d.f.i.i.f.auth.keycloak.Utils - Fetched Keycloak config from server. Size 197
```

On Keycloak's side (running version 6.0.1) , the client is configured as follows (taken from the keycloak.json):
```json
{
  "realm": "devrealm",
  "bearer-only": true,
  "auth-server-url": "https://(my keycloak server)/auth",
  "ssl-required": "external",
  "resource": "frost-server",
  "verify-token-audience": true,
  "credentials": {
    "secret": "(the super secret key that keycloak provided me)"
  },
  "use-resource-role-mappings": true,
  "confidential-port": 0,
  "policy-enforcer": {}
}
```
In addition to this, the client also has all the roles: admin, read, update, create, delete, and so does the user I'm logged in as.

The error is just a plain Tomcat error page: "HTTP Status 403 – Forbidden Description The server understood the request but refuses to authorize it."

When I check the logs for both tomcat (catalina.out, localhost.*.log) and keycloak (keycloak/standalone/log/server.log), there are no errors reported about this.

Being a bit at a loss right now, I decided to ask you folks. What do you reckon is going on? Do you notice anything mis-configured?

**Comment by hylkevds** [comment]
Can you increase the log level to `DEBUG` or even `TRACE` for the package `de.fraunhofer.iosb.ilt.frostserver.auth.keycloak` ? That should give more log output.

**Comment by cornelius-agrippa** [comment]
Thank you Hylke, 
I admit I'm not very proficient with Tomcat. How do you customize the log level of a package? Would it require a recompilation of the WAR? I tried a few combinations in the `logging.properties` but to no avail:
```
de.fraunhofer.iosb.ilt.frostserver.auth.keycloak = TRACE
log4j.logger.de.fraunhofer.iosb.ilt.frostserver.auth.keycloak = TRACE
```

Excuse the offtopic, I feel like this is more support than an issue.

**Comment by cornelius-agrippa** [comment]
All right I figured it out :). I recompiled the WAR and added the following to the main logback.xml file in the HTTP package:
```XML
<logger name="de.fraunhofer.iosb.ilt.frostserver.auth.keycloak" level="TRACE"/>
```

This gave me some more details:
```
2019-06-05 18:02:07,894 190220 [http-nio-8080-exec-9] TRACE d.f.i.i.f.a.keycloak.KeycloakFilter - FROST Keycloak Filter - Filtering request...
2019-06-05 18:02:07,895 190221 [http-nio-8080-exec-9] DEBUG d.f.i.i.f.a.keycloak.KeycloakFilter - Role CREATE required for request POST /FROST-Server.HTTP-1.10-SNAPSHOT/v1.0/Things
2019-06-05 18:02:07,897 190223 [http-nio-8080-exec-9] DEBUG d.f.i.i.f.a.keycloak.KeycloakFilter - User is authenticated...
2019-06-05 18:02:07,897 190223 [http-nio-8080-exec-9] DEBUG d.f.i.i.f.a.keycloak.KeycloakFilter - User is not allowed.
```
So it seemed like it wasn't identifying the correct roles for my user, while in fact it has the role for the realm but not the specific client for FROST:
![image](https://user-images.githubusercontent.com/23480205/58975848-e01bd580-87bd-11e9-94f7-1af22d52d2c0.png)


If I add a role to the client, like so:
![image](https://user-images.githubusercontent.com/23480205/58975887-fd50a400-87bd-11e9-8c27-e7a71773b69e.png)

It works fine. Is this intended behavior? I had the idea that a realm role should be applied to every client that's present on that realm? But then again, you wouldn't be able to exclude certain roles from specific clients.

Thank you for the help Hylke.

**Comment by hylkevds** [comment]
Great, you found the logging bits.
I was about to suggest another way to configure the logging, that doesn't require a recompile. I'll leave that here too, in case someone else has a similar problem with logging.

Download [logback.xml](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/FROST-Server.HTTP/src/main/resources/logback.xml) and put it in the conf directory of Tomcat. Then start Tomcat with the option `-Dlogback.configurationFile=/path/to/conf/logback.xml`

Thanks for figuring out that the client roles need to be explicitly set. I'll add it to the documentation :)
