### ISSUE TITLE
Issues with performing "select" operation on Location

### ISSUE THREAD

**Issue by kanishk-chaturvedi** [FraunhoferIOSB/FROST-Server#120]
Hello,

I am facing an issue in performing "select" operation on Location attribute of a Thing and am wondering if you could help me out. 

I deployed the latest image of the FROST server using Docker (https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docker-compose.yaml) on a Linux based Virtual machine. Further, I set up a Node-RED workbench for inserting the observations as well as updating the location of the device in a real-time manner. The entire flow is working absolutely fine. I can check the Historical Locations of the sensor device, e.g., by using the below-mentioned request:
http://129.187.38.206:8080/FROST-Server/v1.0/Things(1)/HistoricalLocations?$expand=Locations&$top=10&$orderby=time%20desc 

However, the issue occurs when I try to select individual attributes (such as name) from Location, e.g.
http://129.187.38.206:8080/FROST-Server/v1.0/Things(1)/HistoricalLocations?$expand=Locations($select=name,location)&$top=10&$orderby=time%20desc

It returns an error
`{
  "code": 500,
  "type": "error",
  "message": "Failed to execute query. See logs for details."
}`

I have attached the Log file showing the detailed error message.
[FROSTServer_Log.txt](https://github.com/FraunhoferIOSB/FROST-Server/files/3314077/FROSTServer_Log.txt)

It appears to me that the FROST server is not able to perform "select" operations correctly with Locations. For example, if I run a basic query to select only the name attribute from Location of a Thing(1)
http://129.187.38.206:8080/FROST-Server/v1.0/Things(1)?$expand=Locations($select=name) 
it produces the same error. 

However, if I perform the same query on the Datastream instead of Location, it works fine,
http://129.187.38.206:8080/FROST-Server/v1.0/Things(1)?$expand=Datastreams($select=name)

I am not sure if it is a bug in the FROST server or some issue with my installation. The similar query with a publicly available SensorThings API (provided by SensorUp company) works fine, e.g.
https://toronto-bike-snapshot.sensorup.com/v1.0/Things(1573)/HistoricalLocations?$expand=Locations($select=name,location)&$top=1&$orderby=time%20desc 

We are trying to visualize our sensor locations on a map using Grafana Dashboard SensorThings API plug-in (https://grafana.com/plugins/linksmart-sensorthings-datasource). This plugin performs the above-mentioned query in order to visualize sensor locations on its map.

I would really appreciate if you could suggest a way forward.

Thanks and regards,
Kanishk

**Comment by hylkevds** [comment]
Thanks for the report.
Which version are you using?  This issue was fixed in commit 95e981474e9a27e061054796e84c5d65bf1e5c53 .

If you can't update your FROST version, a quick fix would be to turn of the option `persistence.alwaysOrderbyId`

**Comment by kanishk-chaturvedi** [comment]
Thank you very much for your response. I installed the FROST Server before this commit and hence, was facing the issue. This issue is OK to be closed.

Just a basic beginner question, is there any way I can upgrade to the latest FROST Server without losing my data in the database? Any link or reference where I can learn that? As I mentioned, I used Docker (https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docker-compose.yaml) for installing and running the FROST Server. I just want to upgrade the FROST keeping the same database.

Many thanks!

**Comment by hylkevds** [comment]
It should just be a matter of giving the command `docker pull fraunhoferiosb/frost-server:latest` and restarting your container. When using that docker-compose file, the data is in a persistent data volume and will be kept.
Afterwards you may have to check the database-upgrade page to check if there are any DB changes that need to be applied.

**Comment by kanishk-chaturvedi** [comment]
OK - great. Thank you very much for your quick response.
