### ISSUE TITLE
Filtering on phenomenontime interval yields empty observations

### ISSUE THREAD

**Issue by jworch** [FraunhoferIOSB/FROST-Server#1213]
Hi, 

with this query

https://frost.swo-netz.de/FROST-Server/v1.1/Things?$select=name&$filter=startswith(name,%27Parkplatz%27)%20and%20properties/behindertenparkplatz%20eq%20%27ja%27&$expand=Datastreams($select=description;$filter=description%20eq%20%27Belegtstatus%27;$expand=Observations($filter=phenomenonTime%20gt%20now()%20sub%20duration%27P1D%27))

there are empty observations again (?). Search for "Parkplatz Hakenstrasse - 01" to see an example in the query response.
Am I doing something wrong here, or is this unintended behaviour? #116 seems to be related. 

We are running 2.02

**Comment by hylkevds** [comment]
In this case the result looks correct. When adding the IDs to your query:
```
https://frost.swo-netz.de/FROST-Server/v1.1/Things?$select=id,name&$filter=startswith(name,%27Parkplatz%27)%20and%20properties/behindertenparkplatz%20eq%20%27ja%27&$expand=Datastreams($select=id,description;$filter=description%20eq%20%27Belegtstatus%27;$expand=Observations($filter=phenomenonTime%20gt%20now()%20sub%20duration%27P1D%27))
```
we can see that that empty Datastream is nr 653 of Thing nr 270
Looking at the Observations of Datastream 653: 
```
https://frost.swo-netz.de/FROST-Server/v1.1/Datastreams(653)/Observations?$orderby=phenomenonTime%20desc
```
We can see that that Datastream no Observations after the 1st of August. So there is simply no data for the last day.

**Comment by jworch** [comment]
That's good news, because the result is more or less exactly what I wanted to get :)

Is it intended behavior because of "Thing" beeing the root of the query or why is it? I just want to understand why it's correct and what's the difference compared to #116

**Comment by hylkevds** [comment]
The Things are at the root of the result, because that's what you are requesting: `.../v1.1/Things?...`
You can start at any point in the data model, and the entity type that you start at will be at the root of the response.

We've written a page about that in our tutorial here: https://fraunhoferiosb.github.io/FROST-Server/sensorthingsapi/requestingData/STA-QueryDesign.html

**Comment by jworch** [comment]
Ah okay. So as I expected. Thanks a lot.
