### ISSUE TITLE
Activate the Multidatastream Addon with Helm Chart

### ISSUE THREAD

**Issue by SyeKlu** [FraunhoferIOSB/FROST-Server#1224]
Hello,
at the moment I can't use the Multidatastream since it was packaged as a plugin in 2.0. The reason is that I won't be able to enable this plugin via the Helm Variables. Is there another good solution?

**Comment by hylkevds** [comment]
The helm chars are currently not properly up-to-date with the configuration options of FROST v2.0.
We're working on it, and we also welcome pull requests that add the options to the helm charts.

**Comment by hylkevds** [comment]
The helm charts have been updated and now contain the option to enable the provided plugins
