### ISSUE TITLE
Problem with "Server not reachable"

### ISSUE THREAD

**Issue by PedroSolino** [FraunhoferIOSB/FROST-Server#1242]
When I use the URL for reach the database from some plugin, the message "Server not reachable" appears. So where can I find the url address of the database? ( I tried http://localhost:8080/FROST-Server/v1.0 , that where I can access the database)

**Comment by hylkevds** [comment]
With so little information there is no way for us to help you.

**Comment by hylkevds** [comment]
No response, closing issue.
