### ISSUE TITLE
resultFormat=CSV misses phenomenonTime

### ISSUE THREAD

**Issue by ndevilleBE** [FraunhoferIOSB/FROST-Server#1246]
Using the extension resultFormat to download CSV, I noticed that phenomenonTime is systematically missing in the downloaded file.
I deployed the application in Docker (image: fraunhoferiosb/frost-server:2.0) with an external PostgreSQL database.
In the browser the information is correct:
https://sensors.naturalsciences.be/sta/v1.1/Datastreams(109)/Observations?$select=phenomenonTime,result
But when I download the data I only have the results:
https://sensors.naturalsciences.be/sta/v1.1/Datastreams(109)/Observations?$select=phenomenonTime,result&$resultFormat=CSV

Do you observe the same issue? Thanks

**Comment by hylkevds** [comment]
Yep, that's a bug.
I'll look into it.

**Comment by ndevilleBE** [comment]
Thanks for checking. I see you commit some changes. Do you plan to merge it with the docker image? I'm not familiar on how the docker code update works.

**Comment by hylkevds** [comment]
I'm releasing 2.0.4 with the fixes in it. Once the build is through it should be available on Docker Hub.
