### ISSUE TITLE
POST Thing with TaskingCapabilities failed

### ISSUE THREAD

**Issue by SamChen83527** [FraunhoferIOSB/FROST-Server#125]
Hi,

I have a question, not sure whether it's my misunderstanding or not.

I use the latest version of Frost Server, and POST a Thing with Locations, Datastreams and TaskingCapabilities. I found the POST result, the POST request was 201 created successful, but only the TaskingCapabilities wasn't POSTed successfully into the server. 

The following figure is the POSTMAN POST result with 201 created:
![POSTThingWithTC](https://user-images.githubusercontent.com/41568211/61426716-f5a02580-a94d-11e9-8655-2cb9f3338690.PNG)

And this is the message body I POST to Frost Server:
`{
  "name": "Test5",
  "description": "Test5",
  "properties": {
    "floor": 1,
    "FeatureName": "R3-118"
  },
  "Locations": [
    {
      "encodingType": "",
      "name": "R3-118",
      "description": "Room",
      "location": {
        "coordinates": [
          121.18747912624934,
          24.967953892881198
        ],
        "type": "Point"
      }
    }
  ],
  "Datastreams": [
    {
      "unitOfMeasurement": {
        "symbol": "C",
        "name": "degree Celsius",
        "definition": ""
      },
      "observationType": "",
      "ObservedProperty": {
        "name": "air_temperature",
        "description": "Temperature of air in situ.",
        "definition": ""
      },
      "name": "Temperature measurement",
      "description": "Temp reading",
      "Sensor": {
        "metadata": "",
        "encodingType": "text/html",
        "name": "DHT22",
        "description": ""
      }
    }
  ],
  "TaskingCapabilities": [
    {
      "name": "taskingcapability name",
      "description": "taskingcapability description",
      "Actuator": {
        "name": "Actuator1",
        "description": "",
        "encodingType": "",
        "metadata": ""
      },
      "taskingParameters": {
        "field": [
          {
            "name": "status",
            "description": "",
            "use": "mandatory",
            "inputType": "Boolean",
            "unitOfMeasurement": "status",
            "constraint": {
              "value": [
                true,
                false
              ]
            }
          },
          {
            "name": "brightness",
            "description": "",
            "use": "optional",
            "inputType": "Integer",
            "unitOfMeasurement": "brightness degree",
            "constraint": {
              "value": [
                {
                  "Max": 254,
                  "Min": 1
                }
              ]
            }
          },
          {
            "name": "functiontype",
            "description": "",
            "use": "optional",
            "inputType": "String",
            "unitOfMeasurement": "type",
            "constraint": {
              "value": [
                "A",
                "B",
                "V",
                "M"
              ]
            }
          }
        ]
      }
    }
  ]
}`

But the TaskingCapabilities wasn't POSTed successfully:
![Thing](https://user-images.githubusercontent.com/41568211/61426946-d950b880-a94e-11e9-83a8-db4d158fe8d0.PNG)

TaskingCapabilities not found:
![TC1](https://user-images.githubusercontent.com/41568211/61425545-dc957580-a949-11e9-8ba9-686f4935f1e2.PNG)

If I POST the TaskingCapability directly by using the Thing.id, it will be successful:
![POSTTC](https://user-images.githubusercontent.com/41568211/61426797-38fa9400-a94e-11e9-9bbe-5f874c4667c1.PNG)

message body:
`{
  "name": "taskingcapability name 2",
  "description": "taskingcapability description: using thing.id",
  "Actuator": {
    "name": "Actuator1",
    "description": "",
    "encodingType": "",
    "metadata": ""
  },
  "Thing": {
    "@iot.id": 4
  },
  "taskingParameters": {
    "field": [
      {
        "name": "status",
        "description": "",
        "use": "mandatory",
        "inputType": "Boolean",
        "unitOfMeasurement": "status",
        "constraint": {
          "value": [
            true,
            false
          ]
        }
      },
      {
        "name": "brightness",
        "description": "",
        "use": "optional",
        "inputType": "Integer",
        "unitOfMeasurement": "brightness degree",
        "constraint": {
          "value": [
            {
              "Max": 254,
              "Min": 1
            }
          ]
        }
      },
      {
        "name": "functiontype",
        "description": "",
        "use": "optional",
        "inputType": "String",
        "unitOfMeasurement": "type",
        "constraint": {
          "value": [
            "A",
            "B",
            "V",
            "M"
          ]
        }
      }
    ]
  }
}`

TaskingCapabilities POST successfully:
![TC2PNG](https://user-images.githubusercontent.com/41568211/61426929-c807ac00-a94e-11e9-8bc8-9845d0cf2a93.PNG)

If it's my problem or not.

And another question:
Where can I open the "navigationLink" of TaskingCapability, Actuator and Task on the root page and every GET responses of the linked entities? It will be helpful if there are the "navigationLinks" of the part 2 STA.

Thanks in advance for any input.

**Comment by hylkevds** [comment]
You caught a bug! Thank you for the detailed report!
Looks like we forgot to check if the Thing has TaskingCapabilities, when posting a thing. Should be easy to fix.

The navigation links should appear when you set the setting `enableActuation` to true. If you have that setting set to true, but they still don't appear, then please open a separate issue for that.

**Comment by hylkevds** [comment]
It should be fixed in the master branch. Which version are you using?

We would like to hear about your experiences with the Tasking part, it would be great if you could give us a short description of your use case.
