### ISSUE TITLE
Very slow Mutlidatastreams response

### ISSUE THREAD

**Issue by ndevilleBE** [FraunhoferIOSB/FROST-Server#1262]
Dear, 
I'm having issue with the mutlidatastreams observations access.
If I access the following URL, it takes forever to access the data, if it succeed before the 502 proxy error.
https://sensors.naturalsciences.be/sta/v1.1/MultiDatastreams(7)/Observations?$top=100
On the other hand, if I query the database directly, I get the results in 58ms.

In the docker logs:
10:35:51.443 [http-nio-8080-exec-1] INFO     d.f.i.i.f.p.p.ResultBuilder - Slow Query executed in 331060 ms:
select "e0"."RESULT_BOOLEAN", "e0"."RESULT_QUALITY", "e0"."PHENOMENON_TIME_START", "e0"."PARAMETERS", "e0"."DATASTREAM_ID", "e0"."RESULT_STRING", "e0"."RESULT_TYPE", "e0"."VALID_TIME_END", "e0"."PHENOMENON_TIME_END", "e0"."FEATURE_ID", "e0"."ID", "e0"."RESULT_JSON", "e0"."RESULT_TIME", "e0"."RESULT_NUMBER", "e0"."VALID_TIME_START", "e0"."MULTI_DATASTREAM_ID" from "OBSERVATIONS" as "e0" join "MULTI_DATASTREAMS" as "e1" on "e1"."ID" = "e0"."MULTI_DATASTREAM_ID" where (true and "e1"."ID" = 7) order by "e0"."ID" asc offset 0 rows fetch next 101 rows only

Any idea what could be the issue? 

Thanks.

**Comment by hylkevds** [comment]
To see why that query is so slow, you can run it with [`explain analyze`](https://www.postgresqltutorial.com/postgresql-explain/).
There's probably an index missing. To see which indices exist, you can use:
```
SELECT indexname,indexdef FROM pg_indexes WHERE tablename = 'OBSERVATIONS';
```

It's also possible the indices are out of date. You can use this query to see when the last analyze happened:
```
SELECT schemaname as schema,relname,n_live_tup,last_vacuum,last_autovacuum,last_analyze,last_autoanalyze,vacuum_count as vc, autovacuum_count as avc 
  FROM pg_stat_user_tables where schemaname='public'
  ORDER BY n_live_tup DESC;
```

**Comment by ndevilleBE** [comment]
```
explain analyze 
select * from "OBSERVATIONS" o where "MULTI_DATASTREAM_ID" = '7';
```
```
Index Scan using "OBSERVATIONS_MULTI_DATASTREAM_ID" on "OBSERVATIONS" o  (cost=0.57..10320808.64 rows=3429347 width=270) (actual time=4.259..4402.368 rows=3100474 loops=1)
  Index Cond: ("MULTI_DATASTREAM_ID" = '7'::bigint)
Planning Time: 193.931 ms
JIT:
  Functions: 2
  Options: Inlining true, Optimization true, Expressions true, Deforming true
  Timing: Generation 0.623 ms, Inlining 0.000 ms, Optimization 0.000 ms, Emission 0.000 ms, Total 0.623 ms
Execution Time: 4561.597 ms
```

Here are the indexes:
```
OBSERVATIONS_PKEY	CREATE UNIQUE INDEX "OBSERVATIONS_PKEY" ON public."OBSERVATIONS" USING btree ("ID")
OBSERVATIONS_DATASTREAM_ID	CREATE INDEX "OBSERVATIONS_DATASTREAM_ID" ON public."OBSERVATIONS" USING btree ("DATASTREAM_ID")
OBSERVATIONS_MULTI_DATASTREAM_ID	CREATE INDEX "OBSERVATIONS_MULTI_DATASTREAM_ID" ON public."OBSERVATIONS" USING btree ("MULTI_DATASTREAM_ID")
OBSERVATIONS_FEATURE_ID	CREATE INDEX "OBSERVATIONS_FEATURE_ID" ON public."OBSERVATIONS" USING btree ("FEATURE_ID")
observations_phenomenon_time_start_idx	CREATE INDEX observations_phenomenon_time_start_idx ON public."OBSERVATIONS" USING btree ("PHENOMENON_TIME_START")
observations_un	CREATE UNIQUE INDEX observations_un ON public."OBSERVATIONS" USING btree ("DATASTREAM_ID", "PHENOMENON_TIME_START")
```
The OBSERVATIONS table was never vacuumed. I guess it is because I kept the default autovaccum settings which are not fit for large tables. This is done now but there is no effect on the performances. 
I ran a full analyze on the database this morning so Indexes are up to date. It makes sense as the queries are fast in my database software (dbeaver).

**Comment by hylkevds** [comment]
That's not the query FROST is running, so the explain analyze results may differ quite a bit. Especially since the FROST query has an order by and a limit in it.

If the `explain analyze` takes too long you can also just do an `explain`. That usually already gives a good indication.

In this case you probably need an index on `MULTI_DATASTREAM_ID` + `ID`, since the where filters on `MULTI_DATASTREAM_ID`, and the `order by` is on `ID`.

**Comment by ndevilleBE** [comment]
Waw the improvement is jaw-dropping!
Index on the MD_ID and ID is indeed the solution.
Many thanks.
