### ISSUE TITLE
Publishing Tasks to devices via MQTT

### ISSUE THREAD

**Issue by DrAyoub** [FraunhoferIOSB/FROST-Server#131]
Hi,
I'm trying to remotely control devices using 'Tasking capability'. When a client create Tasks based on applicable Parameters of a TaskingCapability, a SensorThings API service forwards the request to the device, the device will execute the task accordingly.

So according to '[OGC SensorThings API Part 2: Tasking Core](https://www.oceanbestpractices.net/bitstream/handle/11329/913/17-079r1_OGC_SensorThings_API_-_Part_II_Tasking_Core.pdf?sequence=3&isAllowed=y)' (page 21) When a client post a _Task_ on the Sensorthings API service, this _Task_ must be published via MQTT in the 'TaskingCapabilities (id)/Tasks' topic.

Does Frost-Server support that?

**Comment by mjacoby** [comment]
Yes, the FROST-Server supports that. 
Make sure to enable support for SensorThings API Part 2: Tasking by setting the config property `enableActuation` to true like described in https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc

**Comment by DrAyoub** [comment]
Thank you for your quick reply,
I added 'enableActuation=true' to docker-compose.yaml 
and following the instructions in [wiki/Docker-Quick-Start](https://github.com/FraunhoferIOSB/FROST-Server/wiki/Docker-Quick-Start) to run FROST-Server in localhost.

when I try to subscribe to 'TaskingCapabilities(1)/Tasks' topic from another terminal using :

> mosquitto_sub -h localhost -p 1883 -t 'TaskingCapabilities(1)/Tasks' 

I get an error message on FROST-Server : 

> web_1_d79592634d9a | 09:10:00.514 [nioEventLoopGroup-3-6] WARN   i.m.s.impl.SessionsRepository - Session does not exist. CId=mosqsub|7617-bsuccess-L
web_1_d79592634d9a | 09:10:00.515 [ pool-6-thread-1] INFO  d.f.i.i.f.m.s.SubscriptionFactory - Subscription for invalid topic: TaskingCapabilities(1)/Tasks

**Comment by hylkevds** [comment]
You're missing the version number prefix in your topic: `v1.0/TaskingCapabilities(1)/Tasks`. It is not explicitly mentioned in the standard, but the version number is supposed to be in there, just like in the HTTP paths. The upcoming version 1.1 will explicitly mention that the topic must start with the version number.

**Comment by DrAyoub** [comment]
That's working, thanks.
