### ISSUE TITLE
MQTT subscription

### ISSUE THREAD

**Issue by Alystrasz** [FraunhoferIOSB/FROST-Server#132]
Dear FROST team,
I'm new to the FROST ecosystem, and am creating a client to create Things and follow their location evolution.

I'd like to know when a given thing receives a new location ; I am thus trying to subscribe to 
`mqtt://localhost/FROST-Server/v1.0/Things([THING_ID])/HistoricalLocations` with the [MQTT NPM client](https://www.npmjs.com/package/mqtt) ; my application subscribes to `#` to receive any notification, unfortunately it does not receive any update when HTTP-pushing new locations.

I'm using the all-in-one docker image by running `docker-compose up` in this repository.

**Comment by mjacoby** [comment]
After an initial check it seems that you are correct and this is a bug. 
I'm currently quite busy so it might take a while till I find the time to fix it. If you want to fix it yourself, PRs are always very welcome.

**Comment by DrAyoub** [comment]
Hi,
Is there any update on this issue ?? 
I am also facing the same problem. I try to publish _Location_ over MQTT and subscribe to _HistoricalLocations_

**Comment by mjacoby** [comment]
There is no update on this so far as I've not found the time to do this. 
The fix is actually not completely trivial as it requires some (minor) structural changes to support triggering multiple MQTT messages instead of only one.
