### ISSUE TITLE
idType ignored without explicit persistenceManagerImplementationClass

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#1324]
Version: 2.x

**Bug repro steps**

Use setting:

- plugins.coreModel.idType: UUID

**Expected result**

Model should use UUID type.

**Actual result**

Long id type is used.

Log extracts:

```
17:16:25.052 [ main] WARN d.f.i.i.f.settings.SettingsMigrator - Converting settings of key 'persistence.persistenceManagerImplementationClass' with old value 'de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong'
17:16:25.053 [ main] WARN d.f.i.i.f.settings.SettingsMigrator - Adding key 'persistence.persistenceManagerImplementationClass' : 'de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager'
17:16:25.053 [ main] WARN d.f.i.i.f.settings.SettingsMigrator - Adding key 'plugins.coreModel.idType' : 'LONG'
```

**Workaround**

Explicitly set persistenceManagerImplementationClass with those settings: 

- persistence.persistenceManagerImplementationClass: de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager
- plugins.coreModel.idType: UUID

**Comment by hylkevds** [comment]
It's not so much that the idType is ignored when there is no explicit persistenceManagerImplementationClass, but that when it finds the old value for that key, it ensures that the behaviour stays as it was when for that old value.

For instance, when it finds `de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong` it sets up the persistence manager to use long ids, overwriting the idType settings. 
In your case it finds the old setting `...PostgresPersistenceManagerLong`, so it sets things up for that.

**Comment by pbaumard** [comment]
The logs are misleading since there is no old `de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong` in my settings. I always used UUIDs.

**Comment by hylkevds** [comment]
Indeed. Something is not quite correct. I'll look into it.

**Comment by hylkevds** [comment]
I've commented out all the values from the provided `context.xml` files, so they are no longer taken as de-facto default values. Now the behaviour should be correct, with the log mentioning that the `persistenceManagerImplementationClass` option is not specified and the (actual) default value is used.

**Comment by pbaumard** [comment]
See 965a1f07e65ad2d4e810226266062c38e2e0b015 66db7de1073d49f03f15913caa015f94de895918 1250efc899c79ae8f1fd52fd32e8c5c9deaee3e4
