### ISSUE TITLE
null properties in select

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#1328]
**Version:**

2.x

**Bug repro steps:**

Any query with a select having an non existing property, for example:

`v1.1/Things?$filter=name eq 'whatever'&$select=properties/x`

**Expected result:**

Same as 1.x, that is:

`{"value":[{"properties":{}}]}`

**Actual result:**

`{"value":[{"properties":{"x":null}}]}`

**Comment by pbaumard** [comment]
Is there any reason why this behavior was changed?

Is it about OData? After reading [Null in the OData Standard](https://www.oasis-open.org/committees/download.php/58261/NullInOData.html) and related OData specs I am still not sure what is the OData spec about null values in select.

Anyway, for FROST users like us which require a response as small as possible, this is a blocker change.

So it should at least be possible to get back the 1.x behavior.
If a new behavior is required, this should be a choice as suggested in #516.

**Comment by hylkevds** [comment]
It was probably just a side effect of the re-write of the serialiser for V2.0. Since there is no explicit test for this, it wasn't noticed so far. The OData plugin uses its own serialiser, so there should not be a relation between the two.
