### ISSUE TITLE
resultMetadata no more supported in expand field

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#1329]
**Version**

2.x

**Bug repro steps**

Any query with $resultMetadata in expand field, for example:

`v1.1/Things?$resultMetadata=off&$expand=Datastreams($resultMetadata=off)`

Note that resultMetadata in expand field is mandatory in 1.x not to get metadata in expanded entities.

**Expected result**

Result without metadata, as in 1.x.

**Actual result**

`{"code":400,"type":"error","message":"Query is not valid: \nEncountered an error at (or somewhere around) input:1:60"}`

**Workaround**

Remove expand resultMetadata in 2.x. Converted example query from above repro steps:

`v1.1/Things?$resultMetadata=off&$expand=Datastreams($resultMetadata=off)`

**Comment by hylkevds** [comment]
Does having the `$resultMetadata` parameter in an expand even make sense? OData doesn't allow it:
> [5.1.3 System Query Option $expand](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_SystemQueryOptionexpand)
> Allowed system query options are [$filter](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionfilter), [$select](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionselect), [$orderby](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionorderby), [$skip](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionstopandskip), [$top](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionstopandskip), [$count](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptioncount), [$search](file:///home/scf/ownCloud/Projects/SensorThingsApi/OData/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionsearch), and $expand.

I also noticed that nextLinks break when metadata is off, even though nextLinks should always be included...

**Comment by pbaumard** [comment]
It would be fine for me to keep current 2.x behavior and have a breaking change section in the release notes.

About nextLinks not appearing with resultMetadata=off:

1. as written in https://fraunhoferiosb.github.io/FROST-Server/extensions/ResponseMetadata.html

> resultMetadata=off does not comply with OData specification

2. and [OGC SensorThings API Part 1: Sensing Version 1.1](https://docs.ogc.org/is/18-088/18-088.html#nextLink) does not make it mandatory (notice the _SHALL_, not _MUST_):

> Responses that include only a partial set of the items identified by the request URL SHALL contain a link that allows retrieving the next partial set of items. This link is called a nextLink

**Comment by hylkevds** [comment]
That's not how those words work, see [4. Terms and Definitions](https://docs.opengeospatial.org/is/18-088/18-088.html#terms-definitions):
> In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

In other words, shall == must
But it's not a standards-conform extension, so what the standard states is indeed irrelevant. Tracking down the issue will take some time.

The extension page doesn't mention how the parameter affects `$expand`. In the default STA format the metadata is only included for the top level. Should `$resultMetadata=full` also expose it for expanded items?

**Comment by pbaumard** [comment]
> In the default STA format the metadata is only included for the top level.

In fact only navigationLink metadata is omitted in [OGC SensorThings API Part 1: Sensing Version 1.1](https://docs.ogc.org/is/18-088/18-088.html#requirement-request-data-expand) expand. selfLink metadata is included, and nextlink must be included if necessary.

Is there any reason for navigationLink omission in expand?
I could not find what is OData behavior for expand metadata.

**Comment by hylkevds** [comment]
I'm not sure why it was left out from expands, probably for compactness. It's not explicitly mentioned anywhere and the behaviour is just based on the examples. 

I've not been able to get the OData demo service (https://services.odata.org/TripPinRESTierService) to give me any metadata at all...

I've reworked the way the metadata is handled. Ideally only the formatter should be looking at it.

**Comment by pbaumard** [comment]
metadata is no more support in expand as of 2.x, see 1c64f552cc1c2b83f5684c1af75733ed8bbe3afb
