### ISSUE TITLE
"Failed to add message to queue. Increase the queue size to allow a bigger buffer, or increase the worker pool size to empty the buffer quicker."

### ISSUE THREAD

**Issue by Mby9** [FraunhoferIOSB/FROST-Server#133]
I was getting the following error in the logs while ingesting data to the FROST-Server:
"d.f.i.i.s.m.InternalMessageBus - Failed to add message to queue. Increase the queue size to allow a bigger buffer, or increase the worker pool size to empty the buffer quicker."

I used FROST-Client for creating and inserting entities. The logs at the client simply said: "de.fraunhofer.iosb.ilt.sta.ServiceFailureException: Failed to create entity."

While going through the code, I found out that we need to BlockingQueue size or the Worker Pool size. These settings are fetched from the Environment Variables.

However, I am not exactly sure as to how and where do we need to pass these parameters, and what exact format is used for doing so. 

Please help. Thank you.

**Comment by mjacoby** [comment]
It seems that you are inserting data faster that the server can process, so the internal queue runs full and when you still continue ingesting data this will fail with the above error.

For changing the size of the queue size and/or the number of worker threads please see the documentation on setting here https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc

The properties you are looking for should be

**bus.workerPoolSize**
The number of worker threads to handle sending messages to the bus.

**bus.queueSize**
The size of the message queue to buffer messages to be sent to the bus.

How/Where to set these values depends on yout type of deployment. Please look at the link provided above.

**Comment by Mby9** [comment]
Thank you so much.
