### ISSUE TITLE
Cannot use singular "Datastream" in 2.x filter

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#1330]
**Version**

2.x

**Bug repro steps**

A GET query using a singular 'Datastream' in filter, for example the query from [Example Queries](https://fraunhoferiosb.github.io/FROST-Server/sensorthingsapi/requestingData/STA-Example-Queries.html):

`v1.1/ObservedProperties?$filter=Datastream/Thing/Datastreams/ObservedProperty/name eq 'Temperature'`

**Expected result**

200 result code, as in 1.x.

**Actual result**

`{"code":400,"type":"error","message":"Unknown Property: Datastream"}`

**Workaround**

Use plural Datastreams. Converted above sample query would be:

`v1.1/ObservedProperties?$filter=Datastreams/Thing/Datastreams/ObservedProperty/name eq 'Temperature'`

Note that this converted query is also OK in 1.x.

**Note**

I am not sure what is the extent of this bug. Is it only about Datastream? Is it only about filter?

**Comment by hylkevds** [comment]
In this case FROST is correct and the example is wrong. ObservedProperties don't have a `Datastream` Entity, they have a `Datastreams` EntitySet. Thus the example should use the plural.

**Comment by pbaumard** [comment]
OK, this makes sense.

The difference of behavior between 1.x and 2.x is also appearing with this kind of query which is valid in 1.x but not in 2.x:

`v1.1/Observations?$filter=Datastreams/id eq '1'`

in this case 2.x must use the entity, not the wrongly used entity set, so correct query is:

`v1.1/Observations?$filter=Datastream/id eq '1'`

In addition to fixing [Example Queries](https://fraunhoferiosb.github.io/FROST-Server/sensorthingsapi/requestingData/STA-Example-Queries.html), there should probably be some note in 2.x Release notes about 2.x complying strictly with the spec on contrary to 1.x for the entity vs entity set difference.
