### ISSUE TITLE
FROST-Server.SQLjooq packaging error?

### ISSUE THREAD

**Issue by selimnairb** [FraunhoferIOSB/FROST-Server#136]
The when I build FROST locally the, JAR file for FROST-Server.SQLjooq includes the classpath resources (e.g. liquibase/tables.xml, etc.).  However, the published version of this file on [bintray](https://dl.bintray.com/fraunhoferiosb/Maven/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.SQLjooq/1.10.1/FROST-Server.SQLjooq-1.10.1.jar) does not.  Without the classpath resources, it is not possible to use FROST within [other projects](https://github.com/kinota/kinota-server) as was possible with the querydsl-based persistence implementations.

Would it be possible to republish FROST-Server.SQLjooq-1.10.1.jar to include the classpath resources?  Thanks.

**Comment by selimnairb** [comment]
Also waiting for 1.10.2 (or whatever the next version will be) would be fine too if that is soon-to-be released.

**Comment by hylkevds** [comment]
Indeed. Currently the liquibase xml files are in the "old" FROST-Server.SQL.PG* packages.
I can probably make a 1.10.2 release with those files moved to the new SQLJooq package.

**Comment by selimnairb** [comment]
Just to clarify, when I build a snapshot locally from master, the liquibase files are present in the SQLjooq JAR, so I guess they were missing when 1.101 was released, but have since been added.

**Comment by hylkevds** [comment]
Yes, this changed between 1.10 and 1.11-SNAPSHOT. The old FROST-Server.SQL.PG* packages no longer exist and the liquibase files are now in the SQLJooq package.

I've built a 1.10.2 release that has the xml files in the SQLJooq package. That should work.

**Comment by selimnairb** [comment]
@hylkevds Thanks! This now works.  I don't see 1.10.2 in CHANGELOG.md, but once that's done, this can be closed.  Thanks so much for addressing this so quickly!

**Comment by hylkevds** [comment]
Changes for the 1.10.x releases are only in the 1.10.x branch:
https://github.com/FraunhoferIOSB/FROST-Server/blob/v1.10.x/CHANGELOG.md

These changes are independent from the Master branch, they may be backports, or bug fixes that are no longer relevant for the master branch...

On the other hand, the master Changelog is the easiest to find, so it would make sense to put all releases in there...
