### ISSUE TITLE
Observations time filter not working

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#1500]
Hi,
   I've encountered some issues while using filter feature to query Observations via latest docker image.
E.g.
1.    /v1.0/Datastreams(1)/Observations?$filter=phenomenonTime lt '2001-11-24T14:37:01.000Z'
2.   /v1.0/Datastreams(1)/Observations?$filter=resultTime lt '2001-11-24T14:37:01.000Z'

Both of above returned with 

```
{
     "code": 500,
     "type": "error",
     "message": "Unsupported operation: Can not compare between Duration and de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.fieldwrapper.SimpleFieldWrapper"
}
```

What else expression can I try? 
Thanks in advance!

**Comment by hylkevds** [comment]
Times are not strings in STA / OData and must not be quoted.
Remove the `'` and try again :)

**Comment by smilehappy126** [comment]
It works like a charm. Thanks.
Now I'm curious, what's the difference between my case and [OGC's tutorial document](https://developers.sensorup.com/docs/#query-filter)?

<img width="861" alt="image" src="https://user-images.githubusercontent.com/26135719/226336863-df09495c-3997-4fad-a11d-49ef6773508b.png">

**Comment by hylkevds** [comment]
That's a tutorial made by SensorUP, not OGC. The specification is pretty clear about it:

https://docs.opengeospatial.org/is/18-088/18-088.html#filter
> The literal values SHALL be strings enclosed in single quotes, numbers and boolean values (true or false) or datetime values represented as ISO 8601 time string.

So Strings go in quotes. Numbers, booleans and datetime values not.

The SensorUP implementation may automatically try to convert from strings to date-times, but FROST does not. Unfortunately there is no official OGC tutorial.

**Comment by smilehappy126** [comment]
I see. Thanks!
