### ISSUE TITLE
@iot.count wrong when following @iot.nextlink

### ISSUE THREAD

**Issue by ndevilleBE** [FraunhoferIOSB/FROST-Server#1554]
Dear, 
I noticed that when using the count=true option for the first time, it works fine -> give the total amount of points.
But when I follow the nextlink the count is not valid anymore.

https://sensors.naturalsciences.be/sta/v1.1/MultiDatastreams(12)/Observations?$count=true
-> "@iot.count": 138178,

https://sensors.naturalsciences.be/sta/v1.1/MultiDatastreams(12)/Observations?$skip=200&$orderby=%40iot.id+asc&$count=true&$skipFilter=%28%40iot.id+gt+652814783%29
-> "@iot.count": 1432,

Kind regards

**Comment by hylkevds** [comment]
Looks like the $skipFilter used for more efficient paging is being added to the count query... Oops

Confirmed here: https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Things?$count=true&$select=name&$top=10
Clicking the nextLink reduces the count by 10 each time...

**Comment by ndevilleBE** [comment]
Dear, 
Any update on this specific bug?
By the way, I also noticed that the count result varies greatly when using the "overlaps" and "during" functions.

https://sensors.naturalsciences.be/sta/v1.1/Datastreams(5)/Observations?$filter=overlaps(phenomenonTime,%202020-09-01T00:00:00Z/2021-01-01T00:00:00Z)&$count=true
-> count=6982

https://sensors.naturalsciences.be/sta/v1.1/Datastreams(5)/Observations?$filter=during(phenomenonTime,%202020-09-01T00:00:00Z/2021-01-01T00:00:00Z)&$count=true
-> count=3563

Is there a logic related to the two functions? My count options are 
      - persistence_countMode=LIMIT_ESTIMATE
      - persistence_countEstimateThreshold=500

Kind regards

**Comment by hylkevds** [comment]
It's not fixed just yet.
The counts being different when using count estimates is normal. Overlaps potentially returns more results than during, so it makes sense that the query analyser gives a higher estimate. That's why you should not set the persistence_countEstimateThreshold to a low value. It's weird to request 1000 items, get an @iot.count of 6000, but no nextLink :)
