### ISSUE TITLE
database tables with lower_case names

### ISSUE THREAD

**Issue by ChrisMalewski** [FraunhoferIOSB/FROST-Server#1574]
When setting up a FROST Server, a database schema is generated where most of the tables names are UPPER Case. 
Upper case table names require special handling in several programming languages or frameworks (python, SQL, Java, Spring Boot, ...) e.g. additional quotes in SQL, or particular configuration settings in Spring Boot.

Is it possible to configure FROST using lower_case database table names?

Thanks in advance,
Chris

**Comment by hylkevds** [comment]
Unfortunately that can not easily be changed. But quoting the table and column names in SQL queries should be easy to do in any programming language. (Definitely in Java and SQL, since that's what FROST is written in :) )

**Comment by ChrisMalewski** [comment]
Thanks.
