### ISSUE TITLE
Using the helm install command from README.md does not work

### ISSUE THREAD

**Issue by clemenschuaccso** [FraunhoferIOSB/FROST-Server#1633]
Commit: https://github.com/FraunhoferIOSB/FROST-Server/commit/e4ef0ca36990b241a73a85fd2e10f09eefa2d955

Used helm version on macOS 13.4.1 (22F82)
Artitecture:  M1 Pro

`helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}
`

The command `helm install --name my-release fraunhoferiosb/frost-server`
Does not work and reports:
`Error: unknown flag: --name
`

**Comment by phertweck** [comment]
It looks like that the `--name` parameter is outdated. According to the help page the syntax is `helm install [NAME] [CHART] [flags]`. I'll update the documentation accordingly.
