### ISSUE TITLE
[help]The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

### ISSUE THREAD

**Issue by mulderyu** [FraunhoferIOSB/FROST-Server#1648]
### Environment:
Ubuntu 22.0
Tomcat 10.1.11
PostgreSQL 15

### Error:
when click [SensorThingsApi v1.0], [SensorThingsApi v1.1] or [Database Status and Update]
encounter the following error message:
The requested resource  is not available
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

how to fix this?

**Comment by hylkevds** [comment]
Hard to say with so little information, but it sounds like a configuration problem in your Tomcat.

**Comment by mulderyu** [comment]
it seems like about java runtime version , the tomcat localhost log shows:
java.lang.UnsupportedClassVersionError: de/fraunhofer/iosb/ilt/frostserver/ContextListener has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 (unable to load class [de.fraunhofer.iosb.ilt.frostserver.ContextListener])

and this is my java version on ubuntu 18:
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

so, should I upgrade openjdk version to, such as, 17 ?

**Comment by hylkevds** [comment]
Yes. FROST-Server version 2.1 (and higher) requires Java 17.
