### ISSUE TITLE
Helm chart bug: Mqtt not using external db connection string when frost.db.enableIntegratedDb is set to false

### ISSUE THREAD

**Issue by MichaelTrip** [FraunhoferIOSB/FROST-Server#1686]
When it tried to set the `frost.db.dbExternalConnectionString` and setting `frost.db.enableIntegratedDb ` to `false`, the mqtt deployment still uses the internal database connection string. I will create a PR with the fix.

**Comment by hylkevds** [comment]
Thank you for the PR!

**Comment by MichaelTrip** [comment]
> Thank you for the PR!

no problem :) When will this be released as a helm chart? Because then i can finally switch to the upstream helm chart instead of the local patched  version i am using now :-)

**Comment by hylkevds** [comment]
It should already be in the [snapshots repository](https://fraunhoferiosb.github.io/helm-charts-snapshot/). I'll make a release of 2.1.5 and 2.0.11 soon.

**Comment by hylkevds** [comment]
2.1.5 and 2.0.11 are now available, with this issue fixed.
