### ISSUE TITLE
The phenomenonTime field on a MultiDatastream is updated based on the resultTimes, not the expected phenomenonTimes.

### ISSUE THREAD

**Issue by ixLikro** [FraunhoferIOSB/FROST-Server#1754]
We noticed that the phenomenonTime field is sometimes not set on our MultiDatastreams. It turned out that the phenomenonTime is missing if no resultTime is set for any associated observation. When the resultTimes are set, the phenomenonTime field is available on the MultiDatastream, but it is based on the resultTimes, not the expected phenomenonTimes.

Interestingly, if you manually $select the phenomenonTime field, the server returns the expected time range based on the phenomenonTimes.
Also, in a MultiDatastream, the resultTime field is never set and cannot be selected, which doesn't seem correct since the normal datastream has a resultTime field.

**Comment by hylkevds** [comment]
Thanks for the report. I've found the typo and fixed it.
