### ISSUE TITLE
[Issue]SensorThings API with Tomcat 10

### ISSUE THREAD

**Issue by mulderyu** [FraunhoferIOSB/FROST-Server#1762]
Does anyone succes install STA with Tomcat 10?

I have tried tomcat 10 with STA 2.2.0, 2.1.0, 2.0.0, 1.15.2 and openjdk 1.11, 1.17, 1.19, and all failed
the error message is like this: The requested resource [/FROST-Server.HTTP-2.2.0/v1.0] is not available

current, i can only install STA on tomcat 9

can anyone share the success installation method of STA on tomcat 10 ?

**Comment by hylkevds** [comment]
From Tomcat 9 to 10 there is a breaking change: https://tomcat.apache.org/migration-10.html

> There is a significant breaking change between Tomcat 9.0.x and Tomcat 10.0.x. The Java package used by the specification APIs has changed from javax... to jakarta.... It will be necessary to recompile web applications against the new APIs.

So an application can be either for 9 _or_ 10, but not both.
There is a way to get applications for 9 to run on 10, but I've not tried it yet:

> Tomcat can convert an existing web application from Java EE 8 to Jakarta EE 9 at deployment time using the Apache Tomcat migration tool for Jakarta EE. 

The next version of FROST (2.3.0) will probably be for Tomcat 10.

**Comment by ChrisMalewski** [comment]
Hi mulderyu, we are running FROST on Tomcat 10 and it is stable for more than a year now.
We used the conversion tool to jakarta suggested in Hylke's link.
Please note to also convert the postgis and postgres jars. 
Cheers

**Comment by mulderyu** [comment]
Thanks, I'll try it
