### ISSUE TITLE
System time in Historical Locations

### ISSUE THREAD

**Issue by manuGil** [FraunhoferIOSB/FROST-Server#19]
The entity 'HistoricalLocations' automatically stores system time.  According with[ requirement 8](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#27) of the standard, when a new 'Location' is created a historical location shall be automatically created. This great. However, it offers  some disadvantages: 

1.  The time assigned to the to a historical location is a system time (or database time). This generates inconsistencies between the time a new location is registered into the API and the 'actual' time in which the change of location was reported to the API. Specially important in networks with a big latency.
2.  Drawbacks on handling moving Things (sensors attached to objects that change location very fast: cars, airplanes, people, etc).  Again, the latency of the network may add errors between the location of a Thing and the time in which it reach the API. More importantly, this means that the  'resulTime' in the Observation entity won't match the 'time' in HistoricalLocation. As a result, one can request the 'result' of an observation for time 'X', but one cannot be sure  what was the precise location  of the Thing (producing the observation) at that time, and vice-versa.  

**Any thoughts on how to overcome those disadvantages?**  
My take on this is that the entity model of the standard need changes.

**Comment by hylkevds** [comment]
That's a good point. Might be worth raising it on the SensorThingsAPI github: https://github.com/opengeospatial/sensorthings

I guess one thing you could do is alter the HistoricalLocation after it is generated, to correct the time.

**Comment by manuGil** [comment]
Thanks for your suggestion for a work-around. I will post this in the official repository.

**Comment by hylkevds** [comment]
Maybe a solution would be to add something like this to the spec:

> When a user directly adds new HistoricalLocation, and the time of this HistoricalLocation is later than the latest HistoricalLocation for the Thing of this new HistoricalLocation, then the Locations of the Thing are changed to the Locations of this new HistoricalLocation.

This allows both the current, automatic generation of HistoricalLocations with the current time, by changing the Locations of a Thing, and also changing the Locations of a Thing, with a time other than the current time.

What do you think?

**Comment by hylkevds** [comment]
This is now implemented experimentally. See #66

**Comment by hylkevds** [comment]
This will also be part of STA v1.1.
