### ISSUE TITLE
Using batch createObservations failed

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#1924]
Hi
I'm sending createObservations request to FROST-Server but keep receiving error message below:
`{"code":400,"type":"error","message":"Missing required property 'result'"}`
But it will works while I separate the array and send it one by one using `/Observation`.

Here's my request ↓
url: http://localhost:43795/FROST-Server/v1.1/Observations
data:
`[
    {
        "Datastream": {
            "@iot.id": 1
        },
        "components": [
            "phenomenonTime",
            "result",
            "FeatureOfInterest/id"
        ],
        "dataArray": [
            [
                "2010-12-23T10:20:00-0700",
                20,
                1
            ],
            [
                "2010-12-21T10:21:00-0700",
                30,
                1
            ]
        ]
    }
]`

Am I missing something? Thanks!

p.s.  Using FROST-Server in container from docker-image.

**Comment by hylkevds** [comment]
You should be posting the DataArray to ` /v1.1/CreateObservations`.

**Comment by smilehappy126** [comment]
Yes. I sent it to `/v1.1/CreateObservations` but in vain.
I mean posting to `/Observation` one by one works well to proof the service is healthy.

**Comment by hylkevds** [comment]
Hmm, testing with `latest` I did notice FROST is picky about the time zone formatting, it wants the `:` in there: `2010-12-21T10:21:00-07:00`.
But after changing that it works. Which version are you using?

**Comment by smilehappy126** [comment]
I'm using `latest` as well. Not sure how to check the corresponding version number. But the error log is not relevant to `phenomenonTime` but `result`？

**Comment by hylkevds** [comment]
The version number is in the logs.
And I need to be able to reproduce your error to be able to find the cause...

**Comment by smilehappy126** [comment]
I see. FROST-Server.Core Version: v2.3.0-33-g48825bc.

**Comment by smilehappy126** [comment]
If I add the `:` to phenomenonTime. It seems no error now.

**Comment by hylkevds** [comment]
That's the same version I'm testing with...
It's very odd that you got the error about the result. Are you sure you received that error when POSTing to `/v1.1/CreateObservations`? I do get that error when posting to `/v1.1/Observations`.

**Comment by smilehappy126** [comment]
Yep. But I can't reproduce as well. But adding `:` do solve the problem. Thanks!
