### ISSUE TITLE
Inconsistency in CSV Result Documentation

### ISSUE THREAD

**Issue by ChrisMalewski** [FraunhoferIOSB/FROST-Server#1934]
https://fraunhoferiosb.github.io/FROST-Server/extensions/CSV-ResultFormat.html
suggests to use` ResultFormat=CSV` to export as csv

https://fraunhoferiosb.github.io/FROST-Server/sensorthingsapi/requestingData/STA-ResultFormats.html
suggests to use `$resultFormat=CSV `

latter works for current FROST.

Kinde regards

**Comment by hylkevds** [comment]
Indeed, that first one is not correct. Thanks for reporting!
