### ISSUE TITLE
Facing CORS Issue

### ISSUE THREAD

**Issue by syed-saad-zahidi** [FraunhoferIOSB/FROST-Server#1991]
I have frost server deployed on my server. This is my frost server yaml file 
version: '3'
    services:
      web:
        image: fraunhoferiosb/frost-server:2.0
        container_name: frost_6088
        environment:
          - serviceRootUrl=https://6088-frost-dev.hef.tum.de/FROST-Server
          - http_cors_enable=true
          - http_cors_allowed.origins=*
          - persistence_db_driver=org.postgresql.Driver
          - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
          - persistence_db_username=sensorthings
          - persistence_db_password=ChangeMe
          - persistence_autoUpdateDatabase=true
          - persistence_alwaysOrderbyId=true
          - auth.provider=de.fraunhofer.iosb.ilt.frostserver.auth.keycloak.KeycloakAuthProvider
          - auth.keycloakConfigUrl=https://keycloak-dev.hef.tum.de/realms/master/clients-registrations/install/frost_6088
          - auth.keycloakConfigSecret=tz6Xx1g8HLbz94XkZ11Vm77YqMMBehs9
        ports:
          - 6088:8080
          - 1978:1883
        depends_on:
          - database
        restart: always
      database:
        image: postgis/postgis:11-2.5-alpine
        container_name: frost_6088_db
        environment:
          - POSTGRES_DB=abcd123
          - POSTGRES_USER=abcd123
          - POSTGRES_PASSWORD=abcd123
        volumes:
          - postgis_volume:/var/lib/postgresql/data
        restart: always
    volumes:
        postgis_volume:

I have generate ssl certificate through lets encrypt and i am using nginx as a reverse proxy.When using axios request from my react app i am facing below cors error 

Access to XMLHttpRequest at 'https://6088-frost-dev.hef.tum.de/FROST-Server/v1.0/Things' from origin 'https://sensorhub-dev.hef.tum.de' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hylkevds** [comment]
When using CORS with access control, one
- must set http_cors_support_credentials to true and 
- can not use `*` for http_cors_allowed_origins.
