### ISSUE TITLE
Updating the Configuration of Running Frost Instance

### ISSUE THREAD

**Issue by syed-saad-zahidi** [FraunhoferIOSB/FROST-Server#1994]
I have multiple frost instances running on docker. I am using Keycloak for authentication. I want to update the config url and client id of a running frost docker container without deleting it. What are the possibility for it, Below is my yaml file for creating the Frost instance 

    version: '3'
    services:
      web:
        image: fraunhoferiosb/frost-server:2.0
        container_name: frost_6065
        environment:
          - serviceRootUrl=http://tuzehez-dev.srv.mwn.de:6065/FROST-Server
          - http_cors_enable=true
          - http_cors_allowed.origins=*
          - persistence_db_driver=org.postgresql.Driver
          - persistence_db_url=jdbc:postgresql://database:5432/****
          - persistence_db_username=sensorthings
          - persistence_db_password=ChangeMe
          - persistence_autoUpdateDatabase=true
          - persistence_alwaysOrderbyId=true
          - auth.provider=de.fraunhofer.iosb.ilt.frostserver.auth.keycloak.KeycloakAuthProvider
          - auth.keycloakConfigUrl=https://keycloak-dev.hef.tum.de/realms/master/clients-registrations/install/frost_6065
          - auth.keycloakConfigSecret=o41fFMNdmZoFAYb0yKd5tUmvjpkkbPZO
        ports:
          - 6065:8080
          - 1955:1883
        depends_on:
          - database
        restart: always
      database:
        image: postgis/postgis:11-2.5-alpine
        container_name: frost_6065_db
        environment:
          - POSTGRES_DB=****
          - POSTGRES_USER=*****
          - POSTGRES_PASSWORD=*****
        volumes:
          - postgis_volume:/var/lib/postgresql/data
        restart: always
    volumes:
        postgis_volume:

**Comment by hylkevds** [comment]
As far as I know there is no way to change configuration in a running Docker container. This always involves starting a new container with the new configuration.
Depending on the Docker environment, you can first start the new one before stopping the old one. I'm not sure how docker-compose does that.
