### ISSUE TITLE
Allow use of MULTIPOLYGON in spatial relationship functions

### ISSUE THREAD

**Issue by jacob-a-brown** [FraunhoferIOSB/FROST-Server#2016]
`MULTIPOLYGON`s used to be enabled for spatial relationship functions (see [commit 6f5b54e](https://github.com/FraunhoferIOSB/FROST-Server/blob/6f5b54e1bdae573504a45dc077666d7ab1f916c0/FROST-Server.Util/src/main/java/de/fraunhofer/iosb/ilt/frostserver/util/WktParser.java)), but no longer are. It would be very useful if they could be enabled and allowed again.

**Comment by hylkevds** [comment]
Ah, I had not expected multiPoligon to be used much, and forgot to implement it in the new parser :)
Should not be easy enough to add.

How are you using it in filters?

**Comment by jacob-a-brown** [comment]
We are using it to identify locations within a particular geographic boundary. We are retrieving the boundaries from [Geoconnex](https://reference.geoconnex.us/openapi#/), and they are `MultiPolygons`. See the counties in New Mexico, for example: https://reference.geoconnex.us/collections/counties/items?f=json&statefp=35

**Comment by hylkevds** [comment]
It should be fixed in the development version. I'll backport it to 2.4.x too.
