### ISSUE TITLE
POST CreateObservations on fresh FROST-Server produces inconsistent errors

### ISSUE THREAD

**Issue by georghas** [FraunhoferIOSB/FROST-Server#2025]
I encountered some weird behavior.

I set up a fresh FROST-Server using Docker with the image `fraunhoferiosb/frost-server:2.5.0-SNAPSHOT`.
I inserted several Things. One with multiple datastreams and some others with single datastreams. They all have names, descriptions, properties and locations.
Then, I tried to send HTTP requests to insert Observations as described here:

### Initial Inserts
I insert lots of Observation arrays by calling `POST /v1.1/CreateObservations` like so (dates and results were randomized, datastream IDs and feature IDs were not):
```json
[
  {
    "Datastream": {
      "@iot.id": 1
    },
    "components": [
      "phenomenonTime",
      "result",
      "FeatureOfInterest/id"
    ],
    "dataArray": [
      [
        "2023-11-09T07:46:51.754Z",
        2.09534,
        1
      ],
      [
        "2017-01-09T07:22:51.784Z",
        5433,
        1
      ] , …
    ]
  }
]
```

They all produced `201` success responses.

### 1st HTTP request
I insert an Observation array by calling `POST /v1.1/CreateObservations` using this body:
```json
[
  {
    "Datastream": {
      "@iot.id": 1
    },
    "components": [
      "phenomenonTime",
      "result"
    ],
    "dataArray": [
      [
        "2023-11-09T07:46:51.754Z",
        2.09534
      ]
    ]
  }
]
```

It produced a `500` error response with this body:
```json
{"code":500,"type":"error","message":"SQL  insert into  FEATURES  ( DESCRIPTION ,  NAME ,  PROPERTIES ,  GEOM ,  ENCODING_TYPE ,  FEATURE ) values (?, ?, ?::json, ST_Force2D(ST_Transform(ST_GeomFromGeoJSON(?), 4326)), ?, ?) returning  FEA"}
```

### 2nd HTTP request
So I believed the request had to include a Feature of Interest in the response.
So I added a Feature of Interest ID to the body and posted it to the same address:
```json
[
  {
    "Datastream": {
      "@iot.id": 1
    },
    "components": [
      "phenomenonTime",
      "result",
      "FeatureOfInterest/id"
    ],
    "dataArray": [
      [
        "2023-11-09T07:46:51.754Z",
        2.09534e-36,
        1
      ]
    ]
  }
]
```

It produced a `201` success response.

### 3rd HTTP request
Afterwards, I tested creating an Observation by calling `POST /v1.1/Observations` with this body:
```json
{
  "result" : 21,
  "Datastream": {"@iot.id": 1}
}
```
Note the lack of a Feature of Interest.
It produced a `201` success response.

### 4th HTTP request
Then, I tried to create an Observation array again by calling `POST /v1.1/CreateObservations` with this body:
```json
[
  {
    "Datastream": {
      "@iot.id": 1
    },
    "components": [
      "result"
    ],
    "dataArray": [
      [
        2.09534e-36
      ]
    ]
  }
]
```

Now it produced this `500` error response:
```json
{"code":500,"type":"error","message":"SQL  insert into  OBSERVATIONS  ( RESULT_NUMBER ,  RESULT_TYPE ,  RESULT_JSON ,  FEATURE_ID ,  RESULT_STRING ,  DATASTREAM_ID ,  RESULT_BOOLEAN ) values (?, ?, ?::json, ?, ?, ?, ?) returning  OBSERVAT"}
```

### 5th HTTP request
Then I posted this Observation array:
```json
[
  {
    "Datastream": {
      "@iot.id": 1
    },
    "components": [
      "phenomenonTime",
      "result"
    ],
    "dataArray": [
      [
        "2023-11-09T07:46:51.754Z",
        2.0953
      ]
    ]
  }
]
```

Against all expectation, it succeeded with a `201` response.

### Further HTTP requests
From this point on, any other similar requests (different phenomenon times, different result numbers, different Datastream IDs) would also produce `201` success responses.

What is going on?

**Comment by hylkevds** [comment]
Can you still access the full error in the log files? The http response only shows a truncated part of the errors.

**Comment by georghas** [comment]
In my sheer endless wisdom, I already destroyed the container producing the error. I can no longer access the logs.
Also I can not reproduce the error anymore.
Thinking about it, I believe the error was caused by me, and not by the FROST-Server.
Sorry for wasting your time.
