### ISSUE TITLE
CreateObservations with missing FOI in database produces error, but 201 response code

### ISSUE THREAD

**Issue by georghas** [FraunhoferIOSB/FROST-Server#2026]
Sending the following request to `POST /v1.1/CreateObservations` produces both an error in the response body and a `201 Created` HTTP response code, if the Feature of Interest ID in the request body does not exist in database:

Request Body:
```json
[
  {
    "Datastream": {
      "@iot.id": 10
    },
    "components": [
      "phenomenonTime",
      "result",
      "FeatureOfInterest/id"
    ],
    "dataArray": [
      [
        "2017-11-09T07:46:51.754Z",
        2.0953,
        6
      ]
    ]
  }
]
```

Response:
`201 Created`

Response Body:
```json
["error No such entity 'FeatureOfInterest' with id [6]"]
```

Data is not persisted in database.
Hence I believe, it should not produce a `201` response code, but rather some `4xx` response code instead.

**Comment by hylkevds** [comment]
https://docs.ogc.org/is/18-088/18-088.html#_response_4
