### ISSUE TITLE
CRS different than WGS84

### ISSUE THREAD

**Issue by claudiadragoste** [FraunhoferIOSB/FROST-Server#2057]
Hello,

I have a doubt: can I change the CRS of the fields that are geometries ("GEOM" and "OBSERVED_AREA" for the tables "DATASTREAMS", "MULTIDATASTREAMS", "LOCATIONS" and "FEATURES" to use a diiferents one? (is this all or did i miss someone?)

Instead of 

"encodingType":"application/geo+json",
"location":{
   "type":"Point",
   "coordinates":[
      16.301278,
      48.14125
   ]
}

Will this work?

"encodingType":"application/geo+json",
"location":{
  {
     "type":"Point",
     "crs":{
        "type":"name",
        "properties":{
           "name":"EPSG:25831"
        }
     },
     "coordinates":[
        396681.647271179,
        4612041.964920721
     ]
  }
}

Thank you very much

**Comment by hylkevds** [comment]
You can, but clients won't be able to understand the data any more.
GeoJSON can only contain WGS84 (lon, lat coordinate pairs).

Until the [JSON-FG standard](https://github.com/opengeospatial/ogc-feat-geo-json) is finished, alternative CRSs are problematic.

**Comment by claudiadragoste** [comment]
It's clear, thank you
