### ISSUE TITLE
Keycloak Authentication Issue

### ISSUE THREAD

**Issue by syed-saad-zahidi** [FraunhoferIOSB/FROST-Server#2077]
I am able to view all my json without login with keycloak. Some time before it was working fine below is docker-compose file for frost server

version: '2.4'

services:
  web:
    image: fraunhoferiosb/frost-server:2.0
    container_name: frost_6091
    environment:
      - serviceRootUrl=https://6091-frost-dev.abc.de/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=abc
      - persistence_db_password=abc
      - persistence_autoUpdateDatabase=true
      - persistence_alwaysOrderbyId=true
      - auth.provider=de.fraunhofer.iosb.ilt.frostserver.auth.keycloak.KeycloakAuthProvider
      - auth.keycloakConfigUrl=https://keycloak-dev.abc.de/realms/master/clients-registrations/install/frost_6091
      - auth.keycloakConfigSecret=eh75w9YsYa3QFB8ObgsgJJrnurQ094N7
    ports:
      - 6091:8080
      - 1981:1883
    depends_on:
      - database
    volumes:
      - /root/wait-for-it.sh:/wait-for-it.sh  # Mount the wait-for-it.sh script
    entrypoint: >
      sh -c "/wait-for-it.sh database:5432 --timeout=60 -- catalina.sh run"  # Run the wait-for-it and start Tomcat
    restart: always

  database:
    image: postgis/postgis:11-2.5-alpine
    container_name: frost_6091_db
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sensorthings -d sensorthings"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgis_volume: 

There should be keycloak redirection before a user can view the datastreams etc.

**Comment by hylkevds** [comment]
Please post the complete HTTP pod log file.

**Comment by syed-saad-zahidi** [comment]
This is my docker containers logs 

NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Dec-2024 14:13:37.930 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.88
13-Dec-2024 14:13:37.933 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Apr 9 2024 13:22:30 UTC
13-Dec-2024 14:13:37.933 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.88.0
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-202-generic
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.23+9
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
13-Dec-2024 14:13:37.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
13-Dec-2024 14:13:37.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
13-Dec-2024 14:13:37.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
13-Dec-2024 14:13:37.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlogging.level.de.fraunhofer=DEBUG
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
13-Dec-2024 14:13:37.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
13-Dec-2024 14:13:37.946 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
13-Dec-2024 14:13:37.946 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
13-Dec-2024 14:13:37.946 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
13-Dec-2024 14:13:37.949 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.3.0] using APR version [1.7.0].
13-Dec-2024 14:13:37.949 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
13-Dec-2024 14:13:37.949 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
13-Dec-2024 14:13:37.953 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
13-Dec-2024 14:13:38.235 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
13-Dec-2024 14:13:38.257 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [500] milliseconds
13-Dec-2024 14:13:38.307 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
13-Dec-2024 14:13:38.307 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.88]
13-Dec-2024 14:13:38.310 SEVERE [main] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
13-Dec-2024 14:13:38.314 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/FROST-Server]
13-Dec-2024 14:13:40.865 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
14:13:41.374 [            main] INFO   d.f.i.i.f.util.GitVersionInfo - FROST-Server.Core Version: v2.0.13
14:13:41.377 [            main] INFO  d.f.i.i.f.h.c.AbstractContextListener - Context initialised, loading settings.
14:13:41.689 [            main] WARN    d.f.i.i.f.s.SettingsMigrator - Converting setting with old key: persistence.alwaysOrderbyId to new key: alwaysOrderbyId with value: true
14:13:41.690 [            main] INFO     d.f.i.i.f.settings.Settings - Not set logSensitiveData, using default value 'false'.
14:13:41.690 [            main] INFO     d.f.i.i.f.settings.Settings - Setting tempPath has value '/usr/local/tomcat/work/Catalina/localhost/FROST-Server'.
14:13:41.690 [            main] INFO     d.f.i.i.f.settings.Settings - Setting serviceRootUrl has value 'https://6091-frost-dev.hef.tum.de/FROST-Server'.
14:13:41.690 [            main] INFO     d.f.i.i.f.settings.Settings - Not set useAbsoluteNavigationLinks, using default value 'true'.
14:13:41.691 [            main] INFO     d.f.i.i.f.settings.Settings - Not set defaultCount, using default value 'true'.
14:13:41.691 [            main] INFO     d.f.i.i.f.settings.Settings - Not set defaultTop, using default value '100'.
14:13:41.691 [            main] INFO     d.f.i.i.f.settings.Settings - Not set maxTop, using default value '100'.
14:13:41.691 [            main] INFO     d.f.i.i.f.settings.Settings - Setting alwaysOrderbyId has value 'true'.
14:13:41.691 [            main] INFO     d.f.i.i.f.settings.Settings - Not set maxDataSize, using default value '25000000'.
14:13:41.692 [            main] INFO     d.f.i.i.f.settings.Settings - Not set extension.filterDelete.enable, using default value 'false'.
14:13:41.693 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.mqttServerImplementationClass, using default value 'de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer'.
14:13:41.693 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.Enabled, using default value 'true'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.Port, using default value '1883'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.Host, using default value '0.0.0.0'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.internalHost, using default value 'localhost'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.SubscribeMessageQueueSize, using default value '10'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.SubscribeThreadPoolSize, using default value '10'.
14:13:41.694 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.CreateMessageQueueSize, using default value '10'.
14:13:41.695 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.CreateThreadPoolSize, using default value '5'.
14:13:41.695 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.QoS, using default value '2'.
14:13:41.696 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.persistenceManagerImplementationClass, using default value 'de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager'.
14:13:41.696 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.idGenerationMode, using default value 'ServerGeneratedOnly'.
14:13:41.697 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.autoUpdateDatabase has value 'true'.
14:13:41.697 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.slowQueryThreshold, using default value '200'.
14:13:41.697 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.queryTimeout, using default value '0'.
14:13:41.697 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.countMode, using default value 'full'.
14:13:41.698 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.countEstimateThreshold, using default value '10000'.
14:13:41.699 [            main] INFO     d.f.i.i.f.settings.Settings - Setting bus.busImplementationClass has value 'de.fraunhofer.iosb.ilt.frostserver.messagebus.InternalMessageBus'.
14:13:41.699 [            main] INFO     d.f.i.i.f.settings.Settings - Not set extension.customLinks.enable, using default value 'false'.
14:13:41.699 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.providedPlugins, using default value 'de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreService,de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreModel,de.fraunhofer.iosb.ilt.frostserver.formatter.PluginResultFormatDefault,de.fraunhofer.iosb.ilt.frostserver.plugin.actuation.PluginActuation,de.fraunhofer.iosb.ilt.frostserver.plugin.multidatastream.PluginMultiDatastream,de.fraunhofer.iosb.ilt.frostserver.plugin.batchprocessing.PluginBatchProcessing,de.fraunhofer.iosb.ilt.frostserver.plugin.format.dataarray.PluginResultFormatDataArray,de.fraunhofer.iosb.ilt.frostserver.plugin.format.csv.PluginResultFormatCsv,de.fraunhofer.iosb.ilt.frostserver.plugin.format.geojson.PluginResultFormatGeoJson,de.fraunhofer.iosb.ilt.frostserver.plugin.openapi.PluginOpenApi,de.fraunhofer.iosb.ilt.frostserver.plugin.odata.PluginOData,de.fraunhofer.iosb.ilt.frostserver.plugin.modelloader.PluginModelLoader'.
14:13:41.699 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.plugins, using default value ''.
14:13:41.699 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading plugins.
14:13:41.700 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreService
14:13:41.701 [            main] INFO  d.f.i.i.f.p.c.PluginCoreService - Creating new Core Service Plugin.
14:13:41.701 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreService.enable, using default value 'true'.
14:13:41.703 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreModel
14:13:41.735 [            main] INFO   d.f.i.i.f.p.c.PluginCoreModel - Creating new Core Model Plugin.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.enable, using default value 'true'.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType, using default value 'LONG'.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.datastream, using default value 'LONG'.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.feature, using default value 'LONG'.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.historicalLocation, using default value 'LONG'.
14:13:41.736 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.location, using default value 'LONG'.
14:13:41.737 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.observedProperty, using default value 'LONG'.
14:13:41.737 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.observation, using default value 'LONG'.
14:13:41.737 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.sensor, using default value 'LONG'.
14:13:41.737 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.coreModel.idType.thing, using default value 'LONG'.
14:13:41.737 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.formatter.PluginResultFormatDefault
14:13:41.738 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.actuation.PluginActuation
14:13:41.743 [            main] INFO   d.f.i.i.f.p.a.PluginActuation - Creating new Actuation Plugin.
14:13:41.743 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.actuation.enable, using default value 'false'.
14:13:41.744 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.multidatastream.PluginMultiDatastream
14:13:41.748 [            main] INFO  d.f.i.i.f.p.m.PluginMultiDatastream - Creating new MultiDatastream Plugin.
14:13:41.749 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.multiDatastream.enable, using default value 'false'.
14:13:41.749 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.batchprocessing.PluginBatchProcessing
14:13:41.751 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.batchProcessing.enable, using default value 'true'.
14:13:41.751 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.format.dataarray.PluginResultFormatDataArray
14:13:41.754 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.dataArray.enable, using default value 'true'.
14:13:41.766 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.format.csv.PluginResultFormatCsv
14:13:41.767 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.csv.enable, using default value 'true'.
14:13:41.767 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.format.geojson.PluginResultFormatGeoJson
14:13:41.768 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.geojson.enable, using default value 'true'.
14:13:41.768 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.openapi.PluginOpenApi
14:13:41.772 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.openApi.enable, using default value 'false'.
14:13:41.772 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.odata.PluginOData
14:13:41.774 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.odata.enable, using default value 'false'.
14:13:41.774 [            main] INFO       d.f.i.i.f.s.PluginManager - Loading de.fraunhofer.iosb.ilt.frostserver.plugin.modelloader.PluginModelLoader
14:13:41.775 [            main] INFO  d.f.i.i.f.p.m.PluginModelLoader - Creating new ModelLoader Plugin.
14:13:41.775 [            main] INFO     d.f.i.i.f.settings.Settings - Not set plugins.modelLoader.enable, using default value 'false'.
14:13:42.180 [            main] INFO  d.f.i.i.f.p.PersistenceManagerFactory - Running database update for de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager
14:13:42.181 [            main] INFO  d.f.i.i.f.p.p.PostgresPersistenceManager - Applying upgrades in liquibase/core.xml
14:13:42.183 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.url has value '*****'.
14:13:42.183 [            main] INFO  d.f.i.i.f.p.p.u.ConnectionUtils - Setting up BasicDataSource for database connections.
14:13:42.183 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.driver has value 'org.postgresql.Driver'.
14:13:42.202 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.url has value '*****'.
14:13:42.202 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.username has value 'sensorthings'.
14:13:42.203 [            main] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.password has value '*****'.
14:13:42.203 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.db.conn.idle.max, using default value '8'.
14:13:42.207 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.db.conn.max, using default value '8'.
14:13:42.207 [            main] INFO     d.f.i.i.f.settings.Settings - Not set persistence.db.conn.idle.min, using default value '0'.
14:13:42.702 [            main] INFO              liquibase.database - Set default schema name to public
14:13:42.794 [            main] INFO           liquibase.lockservice - Successfully acquired change log lock
14:13:43.269 [            main] INFO             liquibase.changelog - Reading from public.databasechangelog
14:13:43.353 [            main] INFO           liquibase.lockservice - Successfully released change log lock
14:13:43.354 [            main] INFO  d.f.i.i.f.p.p.u.LiquibaseHelper - Liquibase changed the search_path from '"$user", public, topology, tiger' to 'public, "$user", public, topology, tiger'. Changing it back.
14:13:43.356 [            main] INFO  d.f.i.i.f.p.PersistenceManagerFactory - Database-update successful.
14:13:43.357 [            main] INFO  d.f.i.i.f.p.PersistenceManagerFactory - Running database update for de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreModel
14:13:43.357 [            main] INFO  d.f.i.i.f.p.p.PostgresPersistenceManager - Applying upgrades in liquibase/plugincoremodel/tables.xml
14:13:43.361 [            main] INFO              liquibase.database - Set default schema name to public
14:13:43.375 [            main] INFO           liquibase.lockservice - Successfully acquired change log lock
14:13:43.646 [            main] INFO             liquibase.changelog - Reading from public.databasechangelog
14:13:43.707 [            main] INFO           liquibase.lockservice - Successfully released change log lock
14:13:43.707 [            main] INFO  d.f.i.i.f.p.p.u.LiquibaseHelper - Liquibase changed the search_path from '"$user", public, topology, tiger' to 'public, "$user", public, topology, tiger'. Changing it back.
14:13:43.708 [            main] INFO  d.f.i.i.f.p.PersistenceManagerFactory - Database-update successful.
14:13:43.708 [            main] INFO   d.f.i.i.f.p.c.PluginCoreModel - Initialising Core Model Types...
14:13:43.708 [            main] INFO       d.f.i.i.f.s.PluginManager - Initialising data model plugins. Pass 1, 1 plugins.
14:13:43.708 [            main] INFO   d.f.i.i.f.p.c.PluginCoreModel - Linking Core Model Types...
14:13:43.732 [            main] INFO   d.f.i.i.f.model.ModelRegistry - Finalising 8 EntityTypes.
14:13:43.733 [            main] INFO     d.f.i.i.f.settings.Settings - Setting http.cors.enable has value 'true'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.allowed.origins, using default value '*'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.allowed.methods, using default value 'GET,POST,HEAD,OPTIONS'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.exposed.headers, using default value 'Location'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.allowed.headers, using default value 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.support.credentials, using default value 'false'.
14:13:43.734 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.preflight.maxage, using default value '1800'.
14:13:43.735 [            main] INFO     d.f.i.i.f.settings.Settings - Not set http.cors.request.decorate, using default value 'true'.
14:13:43.737 [            main] INFO     d.f.i.i.f.settings.Settings - Not set bus.workerPoolSize, using default value '2'.
14:13:43.738 [            main] INFO     d.f.i.i.f.settings.Settings - Not set bus.queueSize, using default value '100'.
14:13:43.742 [            main] INFO     d.f.i.i.f.settings.Settings - Not set auth.provider, using default value ''.
14:13:43.749 [            main] WARN   d.f.i.i.f.m.MqttServerFactory - Using MqttServerClass de.fraunhofer.iosb.ilt.frostserver.mqtt.moquette.MoquetteMqttServer instead of old name de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer
14:13:43.757 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.immediate_buffer_flush, using default value 'true'.
14:13:43.757 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.session_queue_size, using default value '1024'.
14:13:43.757 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.session_timeout_seconds, using default value '3600'.
14:13:43.757 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.netty.mqtt.message_size, using default value '8092'.
14:13:43.757 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.persistentStoreType, using default value 'memory'.
14:13:43.758 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.WebsocketPort, using default value '9876'.
14:13:43.758 [            main] INFO     d.f.i.i.f.settings.Settings - Not set mqtt.javaKeystorePath, using default value ''.
14:13:43.758 [            main] INFO     d.f.i.i.f.settings.Settings - Not set auth.provider, using default value ''.
14:13:43.995 [            main] INFO     d.f.i.i.f.settings.Settings - Not set queueLoggingInterval, using default value '0'.
13-Dec-2024 14:13:44.058 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/FROST-Server] has finished in [5,744] ms
13-Dec-2024 14:13:44.077 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Dec-2024 14:13:44.084 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [5827] milliseconds
root@tuzehez-dev:~#

**Comment by hylkevds** [comment]
> 14:13:43.758 [ main] INFO d.f.i.i.f.settings.Settings - Not set auth.provider, using default value ''.

Your settings don't take effect, since you're using a `.` in the name. But, as the documentation states, environment variables with a `.` are not allowed.

**Comment by syed-saad-zahidi** [comment]
can you provide me an example. how to use the env variable for auth.provider?. It would be helpful. Currently I am following this documentation: **https://fraunhoferiosb.github.io/FROST-Server/settings/auth.html**
