### ISSUE TITLE
Dead link to Docker Documentation

### ISSUE THREAD

**Issue by gautier-laurent** [FraunhoferIOSB/FROST-Server#209]
Hi,

Just to let you know that the link to "use Docker" page of the documentation runs to a 404 page.
Correct link seems to be https://fraunhoferiosb.github.io/FROST-Server/deployment/docker.html
The "deployement" part is missing.

Best regards

**Comment by hylkevds** [comment]
Thanks for reporting! I missed that link when moving documentation around.
