### ISSUE TITLE
Error Building Own Images

### ISSUE THREAD

**Issue by bruno-ribeiro** [FraunhoferIOSB/FROST-Server#213]
Hi, I download the project and using the source code I tried to build my own docker images using this command:

`mvn dockerfile:build -pl FROST-Server.HTTP,FROST-Server.MQTT,FROST-Server.MQTTP`

However, when it doesn't complete, because an error appears.
I have attached the terminal log with the error: [TerminalLog.txt](https://github.com/FraunhoferIOSB/FROST-Server/files/4540649/TerminalLog.txt)

My objective is to create a new string property in the table Datastreams, change the rest of the code to handle requests with the new property and compile.
Building my own images, because at the moment the docker images in the docker file are from your repository in DockerHub.

**Comment by hylkevds** [comment]
Did you build the software before trying to make the docker image?
You do that with the command:
`mvn install -DskipTests -Dmaven.javadoc.skip=true`

**Comment by hylkevds** [comment]
By the way, what is the reason you want to add a new field to the Datastreams table, instead of storing the data in the "properties" field? The properties field can also be used in filters and orderby queries, and if needed you can also add an index if you use it a lot.

**Comment by bruno-ribeiro** [comment]
Yes, you are right. I did not see the field "properties" in your data model, so I can use that. Thank you!

Even though, I might still need to make other changes. So, when I build the software with that command, an error also appears: [BuildTerminalLog.txt](https://github.com/FraunhoferIOSB/FROST-Server/files/4550831/BuildTerminalLog.txt)

**Comment by hylkevds** [comment]
How did you check out the sources? For some reason the build can not find the .git directory with the git repository information...

**Comment by bruno-ribeiro** [comment]
Yes, I checked out a new project and now all seems to be working. Thank you, for all the help.
