### ISSUE TITLE
Temporally unsorted server responses

### ISSUE THREAD

**Issue by HEFLoRa** [FraunhoferIOSB/FROST-Server#221]
Dear FROST community,

we are currently facing an odd issue with a newly set-up FROST server. When resquesting observations from the server (either via Grafana or as direct HTTP request), the returned response is not properly sorted according to the "phenomenonTime". Within the reponse listing there are small blocks of observations that are listed chronologically, however these blocks are then again mostly unsorted according to time themselves. Did some experience a similar behaviour? Is there a recommended fix for this issue?

**Comment by hylkevds** [comment]
Can you give an example of the query you are using, and the response you are getting?

**Comment by HEFLoRa** [comment]
**- Query:**



GET http://#server_address#/Datastreams(1)/Observations?$filter=phenomenonTime%20gt%202020-02-29T23:00:00.000Z%20and%20phenomenonTime%20lt%202020-03-16T22:59:59.000Z&$select=phenomenonTime,result&$top=1000

**- Reponse:**

{
  "@iot.nextLink": "http://localhost:8080/FROST-Server/v1.0/Datastreams(1)/Observations?$top=1000&$skip=1000&$select=result,phenomenonTime&$filter=%28%28phenomenonTime+gt+2020-02-29T23%3A00%3A00.000Z%29+and+%28phenomenonTime+lt+2020-03-16T22%3A59%3A59.000Z%29%29",
  "value": [
    {
      "phenomenonTime": "2020-03-02T19:28:17.343Z",
      "result": 15
    },
    {
      "phenomenonTime": "2020-03-02T19:28:58.994Z",
      "result": 15
    },
    {
      "phenomenonTime": "2020-03-02T19:29:40.589Z",
      "result": 15
    },
    {
      "phenomenonTime": "2020-03-02T19:30:22.193Z",
      "result": 15
    },
    {
      "phenomenonTime": "2020-03-02T19:31:45.432Z",
      "result": 15
    },
    **{
      "phenomenonTime": "2020-03-02T19:32:27.164Z",
      "result": 15
    },
    {
      "phenomenonTime": "2020-03-02T12:31:19.159Z",
      "result": 16
    },**
    {
      "phenomenonTime": "2020-03-02T12:35:28.920Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T12:38:15.551Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T12:39:38.839Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T12:40:20.341Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T12:55:36.126Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:03:14.080Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:03:55.673Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:05:18.938Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:10:10.292Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:12:56.814Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:15:02.238Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:19:11.461Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:21:16.514Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:21:58.031Z",
      "result": 16
    },
    **{
      "phenomenonTime": "2020-03-02T12:33:24.054Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T12:43:48.508Z",
      "result": 16
    },**
    {
      "phenomenonTime": "2020-03-02T12:59:45.929Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:01:09.183Z",
      "result": 16
    },
    {
      "phenomenonTime": "2020-03-02T13:01:50.828Z",
      "result": 16
    },
...

**Comment by hylkevds** [comment]
You're not sorting on phenomenonTime, or any other field, so you're getting the data in the order it is stored in the database. 
If you want the data ordered by phenomenonTime, you should add `&$orderby=phenomenonTime asc`

**Comment by HEFLoRa** [comment]
Thank you! Is there some way to configure temporal sorting at the server side? E.g. that responses are sorted automatically by time without having to explicitely specify in the request?

**Comment by hylkevds** [comment]
No, if you want things sorted, you have to explicitly state so. Even if we would implement automatic sorting in FROST, if your client assumes the results are automatically sorted, then your client will break as soon as it hits a different server implementation.

**Comment by HEFLoRa** [comment]
Actually, the odd thing is that also the entity ID's are not listed in ascending order within the FROST server, even though they have been chronologically posted to the server (as the ascending ID numbering also indicates): 

(Request: http://#server_name#/Datastreams(7)/Observations
(Response:) 

{
  "value": [
    {
      "phenomenonTime": "2020-05-27T**13:07:41**.332Z",
      "resultTime": null,
      "result": 24.7,
      "Datastream@iot.navigationLink": ...
      "@iot.id": **455914**,
      "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.0/Observations(455914)"
    },
    {
      "phenomenonTime": "2020-05-27T**13:18:11**.253Z",
      "resultTime": null,
      "result": 24.6,
      "Datastream@iot.navigationLink": ...
      "@iot.id": **455927**,
      "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.0/Observations(455927)"
    },
    {
      "phenomenonTime": "2020-05-27T**13:12:56**.299Z",
      "resultTime": null,
      "result": 24.7,
      "Datastream@iot.navigationLink": ...
      "@iot.id": **455921**,
      "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.0/Observations(455921)"
    },
    {
      "phenomenonTime": "2020-05-27T**13:23:26**.398Z",
      "resultTime": null,
      "result": 24.6,
      "Datastream@iot.navigationLink": ...
      "@iot.id": **455934**,
      "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.0/Observations(455934)"
    },
    {
      "phenomenonTime": "2020-05-27T**12:46:41**.435Z",
      "resultTime": null,
      "result": 24.7,
      "Datastream@iot.navigationLink": ...
      "@iot.id": **455887**,
      "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.0/Observations(455887)"
    },...
  ]
}

@hylkevds Can you think of a possible reason for this?

**Comment by hylkevds** [comment]
Yep, that's also normal with almost all databases. If you do not specify an order, you get them in the order they have on disk, and the database will put them where there is space. Updating or deleting will create gaps that get filled in again later, and even if you never update or delete anything in a table, maintenance and analysis runs may still shuffle things around.

**Comment by HEFLoRa** [comment]
After some researching in the documentation, we found that server-side sorting can be implemented using the Persistence-Settings (https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html). By including "persistence.alwaysOrderbyId" into the set-up configurations (e.g. in docker-compose.yaml when using docker) an ‘orderby=id asc’ query is added to ensure consistent paging.

**Comment by hylkevds** [comment]
Yes, but your client should not depend on this, because other servers may not have such a setting. If you reqire an order, specify that order!
