### ISSUE TITLE
PhenomenonTime not updated in Multidatastream obs insertion

### ISSUE THREAD

**Issue by spezzi** [FraunhoferIOSB/FROST-Server#229]
I'm using both datastreams and multidatastreams in my FROST installation and I've noticed that phenomenonTime is set only for datastreams.
I've seen the 3 triggers fired in the CRUD operations on OBSERVATIONS table that run the procedures to update phenomenontime, resulttime and observed_area fields in DATASTREAMS table, but no functions for MULTIDATASTREAMS.

Am I missing something? tnx

**Comment by hylkevds** [comment]
Yes, good point. We missed that when adding MultiDatastreams.

It should just be a matter of updating the three triggers in the [postgresTriggers.sql](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/FROST-Server.SQLjooq/src/main/resources/liquibase/postgresTriggers.sql) file. New triggers are not needed. Maybe a check in each, if the NEW/OLD has a Datastream ID or a MultiDatastream ID.

Can you give that a try?

**Comment by spezzi** [comment]
Yes, I'll willingly try.

**Comment by hylkevds** [comment]
Should now be fixed, tanks to PR #236
