### ISSUE TITLE
Add Keycloak AuthProvider to the MQTT Part

### ISSUE THREAD

**Issue by franceOne** [FraunhoferIOSB/FROST-Server#232]
Hello, i use the docker-compose-seperated.yaml to deploy the FROST-Server.

I added successfull the Keycloak AuthProvider to the HTTP Part (edited the context.xml File)
@ "FROST-Server.HTTP/target/FROST-Server.HTTP-1.12-SNAPSHOT/META-INF/context.xml"

But i have no Idea where i can set the AuthProvider for the MQTT Part.

Thanks for your advice.

Best wishes,
Francesco

**Comment by hylkevds** [comment]
You can add all settings to the `enviroment` part of the docker compose yaml file.
As explained in the [settings](https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html) documentation, you do have to replace the dots (`.`) with underscores (`_`).
The auth settings are the same between the HTTP module and the MQTT module.

**Comment by hylkevds** [comment]
If this issue is still relevant, please re-open it.
