### ISSUE TITLE
observedArea in Datastream created automatically

### ISSUE THREAD

**Issue by tsungweihsu** [FraunhoferIOSB/FROST-Server#274]
Hello FROST-Team,

we have ran into some data importing problems that were caused by automatic property creation. We assigned Datastream with `name`, `description`, `observationType`, `sensor`, `observedProperty`, `unitOfMeasurement` and lastly `thing` which has a `location` entity attached as the following example:

"location" : {"type":"Feature","geometry":{"type":"**Point**","coordinates":[52.00,7.00]}}

As we tried to **update** a selected datastream, an error occurred stating that `observedArea` attribute expects a **polygon** value rather than a **point** value. and we found out that `observedArea` attribute has been automatically created (although defined as optional described in [OGC SensorThings API guideline](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#28)) with the values directly from the `location` entity assigned on the `thing`. This automatic attribute creation really prevents the updates of datastream, since we do not have polygon values for things.

In observedArea attribute:
{"type":"**Point**","coordinates":[52.00,7.00]}

Is this issue caused by the internal relation mechanism or can be resolved in the latest version of the server?
Thanks in advance.

We are using:
FROST-Server version: v1.12.2

Tsung-Wei Hsu

**Comment by hylkevds** [comment]
Yes, the standard states the observedArea should be a polygon, but doesn't actually take into account that it's possible for all observations to happen at a single point. In which case it's not possible to make a polygon.

For a quick fix, you can just leave out the `observedArea` attribute when updating the Datastream. Since it's autogenerated, updating it manually won't do much.
I'll add a todo for the next version to also accept point geometries as observedArea.

**Comment by tsungweihsu** [comment]
Thanks for your kind replay and the suggestion for a quick fix. The simple update can unfortunately not be proceeded, since the error actually occurs when a search query is called to select a specific Datastream, an example as the following:

var ds: Datastream? = service.datastreams().query().filter("name eq '$stationName'").first()

The error message:
Class org.geojson.Point not subtype of [simple type, class org.geojson.Polygon] (through reference chain: de.fraunhofer.iosb.ilt.sta.model.Datastream["observedArea"])

There is a org.geojson.Point value in `observedArea` attained from `location` as described above causing this error.

We previously used version 1.9.3 with mostly identical settings which did not throw this error, because `observedArea` isn't auto-generated. There seems to be a mechanical change after v1.10 where this attribute gets created without assignment.

**Comment by hylkevds** [comment]
That seems to be an issue in FROST-Client, not FROST-Server.
Which version of FROST-Client are you using?

**Comment by tsungweihsu** [comment]
Thanks, you are right. The error has be resolved with the latest FROST-Client 0.32. `ObservedArea` can accept Point value normally. Thanks again!

**Comment by hylkevds** [comment]
You're welcome.
