### ISSUE TITLE
$select of properties/<field_name> where properties are defined for any entity doesn't work

### ISSUE THREAD

**Issue by chhonker** [FraunhoferIOSB/FROST-Server#29]
`http://localhost:8080/SensorThingsService/v1.0/Things?$select=properties/buoyId`
returns 404 Not Found with error message: Unexpected 'I'

Whereas `$filter=properties/buoyId eq '123'` works fine.
Why isn't select available on the basic on properties/<fieldname>

**Comment by hylkevds** [comment]
Currently $select only works on Entity level, so you can't select inside (json) properties. The URL parser already rejects the request in this case, since only top-level entity properties are allowed in the $select list.

**Comment by chhonker** [comment]
Can we expect this in future release?

**Comment by hylkevds** [comment]
It's not explicitly part of the standard, but I don't really see a reason not to include it as a non-standard extension. So if someone implements it it'll be in a future release. I don't think we'll get to it soon.

**Comment by hylkevds** [comment]
This feature is now available in FROST 1.13: https://fraunhoferiosb.github.io/FROST-Server/extensions/DeepSelect.html
FROST 1.13 will be released soon.
