### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by matcho** [FraunhoferIOSB/FROST-Server#291]
Hello,

After successfully deploying and running FrostServer under Tomcat9, I'm now facing an issue regarding character encoding.

The PostgreSQL database was created with UTF8 encoding as explained in the documentation. Tomcat is running on localhost, on an Ubuntu Linux machine, having `fr_FR.UTF-8` as system locale.

However, when POSTing some data with non-ascii characters, erroneous characters are stored into the database, and appear as such when subsequently GETting data. Example :
```
curl -X POST 'http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations' -d '{ "name": "München", "description": "München ist die Landeshauptstadt des Freistaates Bayern", "encodingType":"application/vnd.geo+json", "location": { "type": "Point", "coordinates": [ 48.1363467, 11.5695699 ] } }'
```

In Firefox Browser : open http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations
```
{
  "value" : [ {
    "name" : "MÃ¼nchen",
    "description" : "MÃ¼nchen ist die Landeshauptstadt des Freistaates Bayern",
    "encodingType" : "application/vnd.geo+json",
    "location" : {"type":"Point","coordinates":[48.1363467,11.5695699]},
    "HistoricalLocations@iot.navigationLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)/HistoricalLocations",
    "Things@iot.navigationLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)/Things",
    "@iot.id" : 1,
    "@iot.selfLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)"
  } ]
}
```

PostgreSQL query shows that data was recorded erroneously
```
SELECT "NAME", "DESCRIPTION" FROM "LOCATIONS";
   NAME   |                       DESCRIPTION                        
----------+----------------------------------------------------------
 MÃ¼nchen | MÃ¼nchen ist die Landeshauptstadt des Freistaates Bayern
(1 row)
```

When updating database (only the `NAME` field in this example) using the same input source (same Linux terminal on the same OS, same keyboard etc.), value is stored and read appropriately
```
UPDATE "LOCATIONS" set "NAME"="München" WHERE "ID" = 1;

SELECT "NAME", "DESCRIPTION" FROM "LOCATIONS";
  NAME   |                       DESCRIPTION                        
---------+----------------------------------------------------------
 München | MÃ¼nchen ist die Landeshauptstadt des Freistaates Bayern
(1 row)
```

When reading data again through the API, characters are now valid in the `name` field
```
{
  "value" : [ {
    "name" : "München",
    "description" : "MÃ¼nchen ist die Landeshauptstadt des Freistaates Bayern",
    "encodingType" : "application/vnd.geo+json",
    "location" : {"type":"Point","coordinates":[48.1363467,11.5695699]},
    "HistoricalLocations@iot.navigationLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)/HistoricalLocations",
    "Things@iot.navigationLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)/Things",
    "@iot.id" : 1,
    "@iot.selfLink" : "http://localhost:8080/FROST-Server.HTTP-1.12/v1.1/Locations(1)"
  } ]
}
```

Frow what I understand, the API messes up with the input characters at POST time but reads them correctly at GET time ? Do I have to configure something in either Tomcat or FrostServer, or send a specific HTTP header ?

Note: when POSTing data using `axios` with NodeJS, the issue occurs as well.

Thank you for any advice,
Mathias

**Comment by hylkevds** [comment]
Can you try setting the header:
`Content-Type: application/json;charset=UTF-8`
That should ensure that the client tells Tomcat that the data is in UTF-8.

**Comment by matcho** [comment]
It works, thank you.

Is it possible to make this content-type the expected default in FrostServer app, or is it Tomcat related only ?

**Comment by hylkevds** [comment]
It is Tomcat related, but maybe we can find a way to make Tomcat use UTF-8 by default.

**Comment by hylkevds** [comment]
It seems to actually be a result of the Servlet specification: https://cwiki.apache.org/confluence/display/TOMCAT/Character+Encoding
> If a character encoding is not specified, the Servlet specification requires that an encoding of ISO-8859-1 is used. 

I've not had success yet with changing the default to UTF-8...

**Comment by tobilarscheid** [comment]
Hi everyone, just wanted to chime in here and say that we stumbled across this as well. In my opinion this should be treated as a bug, as the json spec states utf-8 as the default. So, glad to see you are working on this. Thank you!

**Comment by hylkevds** [comment]
The big problem, is that the HTTP 1.1 specification states that if the content type is not specified, the server MUST interpret the data as ISO-8859-1. Doing something else would violate the HTTP 1.1.
If you think this is a bug, you'll have to file a bug report for the HTTP 1.1 specification...

That said, since UTF-8 is a superset of ISO-8859-1, nothing should break if we just secretly do the conversion. However that would be a FROST-Server specific fix, and your code would still fail on any other STA implementation.

**Comment by tobilarscheid** [comment]
Not sure if I agree with what you said about HTTP 1.1 - in my opinion it should be sufficient to send 'Content-Tye: application/json' - this should be enough to indicate to the server that whatever follows is utf-8 encoded, if not otherwise indicated.
Apart from this "RFC-lawyering": my gut feeling is that FROST just behaves strange here - all other JSON based APIs I have interacted with so far just "secretly convert" to UTF-8.
I really don't want to sound aggressive or push you in any direction - just trying to provide my point of view here.

**Comment by hylkevds** [comment]
No worries. I agree that it's weird that the json content type still requires a character encoding, given that json implies UTF-8. And given that UTF-8 is a superset of ISO-8859-1, the conversion wouldn't break anything.

It's not a high priority for me, but a PR is welcome.

**Comment by tobilarscheid** [comment]
PR is open, feel free to continue discussion over there :-)

**Comment by tobilarscheid** [comment]
I think this can be closed for now.
