### ISSUE TITLE
Running on Wildfly

### ISSUE THREAD

**Issue by niekarends** [FraunhoferIOSB/FROST-Server#30]
I would like to run the SensorThingsServer on Wildfly 10. 
I saw that the configuration is partially in context.xml which makes running the application Tomcat specific.

**Comment by hylkevds** [comment]
Thanks, I'll have a look. 
The advantage of the context.xml is that it is copied outside of the war the first time the war is deployed, so you don't lose your settings if you update the war at a later date. So I'll probably keep the context.xml.

**Comment by hylkevds** [comment]
I've merged the changes. Thanks!
