### ISSUE TITLE
Can't inizialize database with tomcat

### ISSUE THREAD

**Issue by nicololevorato** [FraunhoferIOSB/FROST-Server#309]
I followed the documentation to deploy frost server on tomcat, but when i try to inizialize/upgrade the database i'm stuck with no response from the server. The tomcat console is stuck with

> 15:38:27.865 [http-apr-8080-exec-3] INFO    d.f.i.i.f.h.c.DatabaseStatus - DatabaseStatus Servlet called.
> 15:38:27.876 [http-apr-8080-exec-3] INFO     d.f.i.i.f.settings.Settings - Not set persistence.db.url, using default value ''.
> 15:38:27.877 [http-apr-8080-exec-3] INFO   d.f.i.i.f.p.p.ConnectionUtils - Setting up DataSource for database connections.
> 15:38:27.877 [http-apr-8080-exec-3] INFO     d.f.i.i.f.settings.Settings - Setting persistence.db.jndi.datasource has value 'jdbc/sensorThings'.

**Comment by hylkevds** [comment]
If there is no logging output after that, I suppose the server is trying to connect to your datasource but is not getting a response.
What is the definition of the `jdbc/sensorThings` datasource? And where is it configured?

**Comment by nicololevorato** [comment]
jdbc/sensorThings is defined in context.xml in webapps and in server.xml

> <Resource
        name="jdbc/sensorThings" auth="Container"
        type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
        url="http://127.0.0.1:24100/"
        username="sensorthings" password=""
        maxTotal="20" maxIdle="10" maxWaitMillis="-1"
        defaultAutoCommit="false"
    /> 
where the url is my pgAdmin server hosted in my pc with a database called sensorThings.

**Comment by nicololevorato** [comment]
resource is defined both in webapps context.xml either in server.xml. Definition is 

> Resource

            name="jdbc/sensorThings" auth="Container"
            type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
            url="jdbc:postgresql://127.0.0.1:24100/sensorThings"
            username="" password=""
            maxTotal="20" maxIdle="10" maxWaitMillis="-1"/>`
the url is the pgAdmin server hosted in my pc with a database named sensorThings.

**Comment by hylkevds** [comment]
Is it possible there is a firewall interfering with the connection between tomcat and the database?
Do you have other applications hosted in the same Tomcat that use that database server?

**Comment by nicololevorato** [comment]
Tomcat is just running FROST server and there are no other programs which are using the database. I tried with windows firewall disabled and still same issue. The database is empty, i don't know if it's a problem. Sry, i'm new to this kind of things.

**Comment by hylkevds** [comment]
Are you sure PostgreSQL is running on port 24100? The default port for PostgreSQL is 5432.
From what you wrote in your first post, I suspect that 24100 is where PgAdmin is running, not where PostgreSQL is running.

**Comment by nicololevorato** [comment]
Oh yes, thank you very much!
