### ISSUE TITLE
Cannot create/update object using Id other type than integer

### ISSUE THREAD

**Issue by DLade** [FraunhoferIOSB/FROST-Server#317]
Recording to the specification the Id of an entity can be anything:
http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#23

So in this client (https://github.com/gost/sensorthings-net-sdk) are used strings as Id at all.

But creating a Datastream (example below) results in error.
```
{
    "description": "Werte",
    "name": "Werte",
    "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
    "unitOfMeasurement": {
        "name": "centimeter",
        "symbol": "cm",
        "definition": "https://ucum.org/ucum.html"
    },
    "ObservedProperty": { 
        "@iot.id": 4,
        "name": "ObservedProperty",
        "description": "ObservedProperty",
        "definition": "ObservedProperty",
        
        "@iot.selfLink": "http://localhost:8080/FROST-Server/v1.1/ObservedProperties(4)"
    },
    "Sensor": {
        "name": "Sensor",
        "description": "Sensor",
        "encodingType": "application/pdf",
        "metadata": "https://arxiv.org/pdf/1207.0203.pdf"
    },
    "Thing": { "@iot.id": "1" }
}
```
`{"code":400,"type":"error","message":"Cannot construct instance of `de.fraunhofer.iosb.ilt.frostserver.model.core.IdLong` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('1')\n at [Source: (String)\"{\n    \"description\": \"Werte\",\n    \"name\": \"Werte\",\n    \"observationType\": \"http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement\",\n    \"unitOfMeasurement\": {\n        \"name\": \"centimeter\",\n        \"symbol\": \"cm\",\n        \"definition\": \"https://ucum.org/ucum.html\"\n    },\n    \"ObservedProperty\": { \n        \"@iot.id\": 4,\n        \"name\": \"ObservedProperty\",\n        \"description\": \"ObservedProperty\",\n        \"definition\": \"ObservedProperty\",\n        \n        \"@iot.selfLink\": \"http://loc\"[truncated 276 chars]; line: 24, column: 27]"}`

note: May be simple to have a constructor for a given string - it can result in error if parsing is wrong.

**Comment by hylkevds** [comment]
If you use Longs as IDs, you have to put longs in the JSON. Just as FROST presents them to you when fetching entities. You can't just change data types and expect things to work...

If you want to use Strings or UUIDs as IDs, you can change to a different database back-end.
See the persistence settings on the [settings page](https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html#persistence-settings).

Do note that non-Long primary keys are a lot less efficient.

**Comment by DLade** [comment]
I see, I will find out if I can fix this issue in our client.
