### ISSUE TITLE
Batch process multiple Observations at once

### ISSUE THREAD

**Issue by tobilarscheid** [FraunhoferIOSB/FROST-Server#318]
For importing a large amount of already existing sensor data from an archive I would like to be able to send multiple observations in one POST request. Currently, this does not seem to be possible. I think such functionality is not currently part of SensorThings, but are there any plans to implement it any way? Would you be interested in a Pull Request adding this kind of batch processing?

**Comment by hylkevds** [comment]
You can do that using [DataArrays](https://hylkevds.github.io/sensorthings/18-088/18-088.html#create-observation-dataarray) ([v1.0](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#82)) or Batch processing. DataArrays is the easier and more efficient solution.

**Comment by tobilarscheid** [comment]
Very cool, thank you for the quick reply! Is this actually implemented in FROST Server?

**Comment by hylkevds** [comment]
Yep, it's supported.

**Comment by tobilarscheid** [comment]
Awesome. Closing this for now, thank you again!
