### ISSUE TITLE
Removing the context path /FROST-Server/

### ISSUE THREAD

**Issue by tobilarscheid** [FraunhoferIOSB/FROST-Server#324]
Hi everyone,

I am trying to remove the context path configured in [context.xml](https://github.com/FraunhoferIOSB/FROST-Server/blob/83a79944dae3599924def29b250a04694fd5e6bf/FROST-Server.MQTTP/src/main/webapp/META-INF/context.xml#L2), so that my FROST Server is reachable under `example.com/` instead of `example.com/FROST-Server/`. 
I am using your standard docker image, what configuration param would help me with this? Changing the `serviceRootUrl` did not help, it just messed up the links generated by FROST.

Best,

Tobi

**Comment by ksonda** [comment]
You could use a reverse proxy server in front of FROST, and do an internal rewrite from /* to /FROST-Server, so that the client sees example.com/ while the api sees hostname:port/FROST-Server/

**Comment by hylkevds** [comment]
The suggestion of @ksonda is the usual approach.
In the Docker images it is not possible to change this, since it would require changing the way the image is built.
