### ISSUE TITLE
Frost Docker container shuts down by itself 

### ISSUE THREAD

**Issue by chenkianwee** [FraunhoferIOSB/FROST-Server#328]
I have setup a frost server with the docker images. The container seems to shut down by itself. I checked the log and it is filled with these errors. Just wondering what is happening here. Am I posting too frequently to the server?

19:03:55.405 [https-openssl-nio-8080-exec-10] INFO     d.f.i.i.f.p.p.ResultBuilder - Slow Query executed in 252 ms:
select "OBSERVATIONS"."RESULT_NUMBER", "OBSERVATIONS"."RESULT_TYPE", "OBSERVATIONS"."RESULT_JSON", "OBSERVATIONS"."PHENOMENON_TIME_END", "OBSERVATIONS"."RESULT_STRING", "OBSERVATIONS"."PHENOMENON_TIME_START", "OBSERVATIONS"."RESULT_BOOLEAN" from "OBSERVATIONS" join "DATASTREAMS" as "e1" on "e1"."ID" = "OBSERVATIONS"."DATASTREAM_ID" where (true and "e1"."ID" = 1 and "OBSERVATIONS"."PHENOMENON_TIME_START" > timestamp with time zone '2020-12-22 05:00:00+00:00' and "OBSERVATIONS"."PHENOMENON_TIME_END" <= timestamp with time zone '2020-12-24 19:03:33.213+00:00' and "OBSERVATIONS"."PHENOMENON_TIME_START" < timestamp with time zone '2020-12-24 19:03:33.213+00:00') limit 1001 offset 35000
19:03:55.956 [https-openssl-nio-8080-exec-11] INFO     d.f.i.i.f.p.p.ResultBuilder - Slow Query executed in 202 ms:
select "OBSERVATIONS"."RESULT_NUMBER", "OBSERVATIONS"."RESULT_TYPE", "OBSERVATIONS"."RESULT_JSON", "OBSERVATIONS"."PHENOMENON_TIME_END", "OBSERVATIONS"."RESULT_STRING", "OBSERVATIONS"."PHENOMENON_TIME_START", "OBSERVATIONS"."RESULT_BOOLEAN" from "OBSERVATIONS" join "DATASTREAMS" as "e1" on "e1"."ID" = "OBSERVATIONS"."DATASTREAM_ID" where (true and "e1"."ID" = 2 and "OBSERVATIONS"."PHENOMENON_TIME_START" > timestamp with time zone '2020-12-22 05:00:00+00:00' and "OBSERVATIONS"."PHENOMENON_TIME_END" <= timestamp with time zone '2020-12-24 19:03:28.509+00:00' and "OBSERVATIONS"."PHENOMENON_TIME_START" < timestamp with time zone '2020-12-24 19:03:28.509+00:00') limit 1001 offset 51000

**Comment by hylkevds** [comment]
What is too much depends on your hardware and usage patterns.

These messages are not errors, but only warnings that a query took longer than 200 milliseconds to complete. This usually just means it is time to have a look at adding an index on the relevant database table. Have a look at the documentation site for more information about indices.

From the query it also seems you are doing a lot of paging, with only 1000 items per page. It's a good idea to increase the page size in this case.

Happy holidays,
Hylke
________________________________

**Comment by chenkianwee** [comment]
Hi Hylke, 
Thanks for the reply. I have added a new index to the observation table. Hope it will solve the problem. I am new to postgresql, what do you mean by increase the paging. If possible can you point me to resources on how to increase the paging? Thanks. Happy Holidays to you too !!

**Comment by hylkevds** [comment]
It's a FROST setting that controls the maximum number of items returned in a list: maxTop
You should experiment with 10000 or so, and use $top=10000 when getting Observations.

**Comment by chenkianwee** [comment]
Thanks !! I have made all the changes.
