### ISSUE TITLE
Security: database password and other other details logged 

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#337]
**Steps to reproduce**

Starts FROST Server with those properties:

1. persistence_db_url
2. persistence_db_username
3. persistence_db_password

**Actual result**

Those properties are logged, for example:

>  12:55:43.178 [localhost-startStop-1] INFO d.f.i.i.f.settings.Settings - Setting persistence.db.url has value 'jdbc:postgresql://my-instance/my-database'.
>  12:55:43.179 [localhost-startStop-1] INFO d.f.i.i.f.settings.Settings - Setting persistence.db.username has value 'my-db-user'.
>  12:55:43.179 [localhost-startStop-1] INFO d.f.i.i.f.settings.Settings - Setting persistence.db.password has value 'my-secret-password'.

**Expected result**

Those property values should not be logged. See for example [OWASP Logging Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#data-to-exclude).

> The following should not usually be recorded directly in the logs, but instead should be removed, masked, sanitized, hashed or encrypted:
> 
[...]
> - Authentication passwords
> - Database connection strings

**Comment by hylkevds** [comment]
Thanks, good point.
I've updated the settings loader, so it now hides passwords and DB connection strings by default. They can still be shown with a config setting, to help when debugging issues.
