### ISSUE TITLE
Questions about tomcat configuration

### ISSUE THREAD

**Issue by rlhochpass** [FraunhoferIOSB/FROST-Server#340]
I have a understanding problem about the documentation of the tomcat-deployment of the FROST-Server. 
After the copy of the two files i must edit the resource of the server.xml file. 
If I look at the server.xml of the docker container with docker exec I see that the server.xml is not be edited. 
**So I have questions:** 

- If i go into the tomcat/conf/Catalina/localhost there is nothing. So where is the appname.xml? 
- So can anybody explain me in general where I must edit something for the tomcat deployment. (-->/conf/web.xml, webapps/.../META-INF/context.xml, /conf/server.xml, /conf/CATALINA/.../appname.xml) 
--> where i give the resource to the database? 
--> where i must configurate something (f.e. the service url) for the FROST-Server? (only in webapps/.../context.xml ?)

Thanks.

**Comment by hylkevds** [comment]
Tomcat configuration is a bit tricky...
There are four places in a Tomcat environment were configuration options can reside:
- Enviroment variables
- The Context entry either in
  - server.xml
  - $CATALINA_BASE/conf/[enginename]/[hostname]/appname.xml
  - /META-INF/context.xml inside the war file.

These are taken in this order, first value found.
In the docker case, all configuration is done over environment variables.

The file `$CATALINA_BASE/conf/[enginename]/[hostname]/appname.xml` is only generated automatically when you have the COPYXML option enabled in Tomcat.

after editing the server.xml file, Tomcat must be restarted for changes to take effect.

**Comment by rchochpass** [comment]
I'm still new to tomcat, hence the question:
The configuration of the resource via the server.xml and the context.xml from the .war file was not yet successful. I also kept restarting the Tomcat.

How would you approach the Tomcat configuration? Is there a workflow for this so that it is not so "tricky"?
Thank you for your prompt reply.

**Comment by hylkevds** [comment]
In the logging output of FROST, do you actually see the configuration you entered, or do you only see the default settings?

**Comment by rlhochpass** [comment]
Everything worked. Many thanks for the help.

**Comment by rchochpass** [comment]
In addition:
This is how it worked for me now:
- copyXML is set to true in conf / server.xml
- in the webapps / FROST-Server / META-INF / context.xml the override (s) must be set to true
- Complete configuration of the FROST server (with auth) in the conf / Catalina / localhost / FROST-Server.xml (here the override (s) are set to false)

Many thanks for the help.
