### ISSUE TITLE
 filtering with date() function doesn't seem to work 

### ISSUE THREAD

**Issue by ksonda** [FraunhoferIOSB/FROST-Server#352]
Compare

https://twsd.internetofwater.dev/api/v1.1/Datastreams('NC0326010-WaterDistributed')/Observations?$filter=date(phenomenonTime)%20gt%20date('2019-10-01')

https://twsd.internetofwater.dev/api/v1.1/Datastreams('NC0326010-WaterDistributed')/Observations?$filter=phenomenonTime%20ge%202019-10-01T00:00:01.000Z

**Comment by hylkevds** [comment]
Can test the development branch? It should be fixed there.

Note that filtering using date can return unexpected results, since a date does not have a time zone. This causes the results to be dependent on the database server configuration.

**Comment by ksonda** [comment]
Thanks. That works. database config sensitivity acknowledged
