### ISSUE TITLE
Question: does FROST use an index on JSON data in "PROPERTIES"?

### ISSUE THREAD

**Issue by volcan01010** [FraunhoferIOSB/FROST-Server#370]
Hi,

We are copying data from an existing data store to FROST Server for publication.  In this process, we include the primary key ID from our old data store as a value in the JSON "PROPERTIES".  We run many queries like this:

```
/FROST-Server/v1.1/Sensors?$select=@iot.id&$filter=properties/internal_id eq 123
```

I have added an index to the "PROPERTIES" column (following [these instructions](https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING)) to see if it speeds things up:

```sql
CREATE INDEX idxginp_sensors_properties ON "SENSORS" USING GIN ("PROPERTIES" jsonb_path_ops);
```

It didn't seem to make much difference.  Maybe I didn't have enough records for it to matter, but I even added on to Observations.

Do you know if the FROST query will benefit from these indices?  If not, is there a way that I can write the filter so that it will?

**Comment by hylkevds** [comment]
The sure way to find out if PostgreSQL is using an index is to find the exact query the FROST is using, and run it manually with `explain analyze` prepended.

To find the exact query, you can set the setting `persistence.slowQueryThreshold` to something low, so that your query is logged.

It could be that FROST currently uses queries that don't benefit from GIN indexes. So far I've generally added btree indexes on the exact left-hand-side of the compare that FROST generates.

**Comment by volcan01010** [comment]
Thanks for this.  I ran explain analyse on the following and it uses the index:

```sql
SELECT * FROM "OBSERVATIONS" WHERE "PARAMETERS" @> '{"sen_id": 3062797}';
``
I'll try your suggestion and see the exact query that FROST runs.

**Comment by hylkevds** [comment]
FROST generates traditional comparisons, like
```
"PARAMETERS"::jsonb#>'{ sen_id }' = to_jsonb(3062797)
```

**Comment by volcan01010** [comment]
Thanks for getting back so quickly.  I found a query in the logs that was looking up the `iot.id` for one of our `sen_id` parameters.  It looks like this:

```
select "OBSERVATIONS"."ID" from "OBSERVATIONS" where (1 = 1 and "OBSERVATIONS"."PARAMETERS"::jsonb#>>'{ sen_id }' = cast('3085900' as varchar)) limit 4001
```
EXPLAIN ANALYSE shows that it doesn't use the index for this.

Since looking into this, I've learned about the _persistence.idGenerationMode_ setting.  I'm going to investigate setting this to _ServerAndClientGenerated_ and supplying the `iot.id` for Observations as our internal store value.  That way it becomes the primary key and will be indexed automatically.

I hope that this will also speed up our batch load process.  At the moment, PostgreSQL has to roll back many transactions when parallel requests try to take the same server-generated ID.  That issue should be resolved if we supply the ID.

Thanks again for all your help.

**Comment by hylkevds** [comment]
> At the moment, PostgreSQL has to roll back many transactions when parallel requests try to take the same server-generated ID.

That should never happen! The sequence used to generate IDs should give out each ID value only once, regardless how many parallel inserts happen. Are you using the default FROST-generated database, or did you modify it?

**Comment by volcan01010** [comment]
OK.  I did wonder.  I don't know what is causing all the rollbacks, then.  We are using the FROST-generated database.

The graph below is from uploading 5,000 Observation records via our script.  The script queries FROST to see if an item with our internal ID exists, then POSTs the record if it isn't found or PUTs it if it is.
 
<img width="439" alt="frost_rollbacks" src="https://user-images.githubusercontent.com/12040043/112298089-89cb9f80-8c8e-11eb-8cf8-1bd82b7a1ae5.PNG">

I have done more reading and learned that some database frameworks do a rollback after read-only queries by default, so perhaps it is this.

**Comment by hylkevds** [comment]
Yeah, in that case you are most likely seeing the "rollbacks" on transactions that did not change anything.

**Comment by volcan01010** [comment]
OK.  Thank you for your help and for FROST Server.  You have answered my question, so I'll close the issue.

**Comment by hylkevds** [comment]
If you have the time, it would be great to get some performance comparisons between the two query styles, with and without the different types of indexes. That would give us some insight if it's worth trying to change the query generator to generate the other type of query for situations where it is possible.

**Comment by volcan01010** [comment]
I'm off for Easter but will look into this when I get back.  We will have a database with 2 million observations to test against then.

**Comment by volcan01010** [comment]
Hi,

I have our database in a suitable state to perform the queries now.  We modified our FROST server to use `persistence_idGenerationMode=ServerAndClientGenerated` and updated our ETL process to provide an ID for the Observations as they are uploaded.

This made the upload process much quicker because we have to check if an Observation already exists before deciding whether to POST a fresh one or PUT an update.  Previously, this check ran against a parameter held in the JSON, but now it uses the indexed primary key.  Previously, each new Observation took longer to check as the table got bigger, but the index look up is constant time.

The database (our prod001) now has nearly 2.8 million observations (populated in around 3 hours) that look like this:

```json
{
    "@iot.id": 164139268,
    "phenomenonTime": "2020-01-09T15:30:00.000Z",
    "parameters": {
        "sen_id": 164139268,
        "publish_yn": "Y"
    },
    "result": 0.7659,
    "resultTime": "2020-01-09T15:30:00.000Z",
    "@iot.selfLink": "http://zhwlapiprod002.ad.nerc.ac.uk:8080/FROST-Server/v1.1/Observations(164139268)",
    "Datastream@iot.navigationLink": "http://zhwlapiprod002.ad.nerc.ac.uk:8080/FROST-Server/v1.1/Observations(164139268)/Datastream",
    "MultiDatastream@iot.navigationLink": "http://zhwlapiprod002.ad.nerc.ac.uk:8080/FROST-Server/v1.1/Observations(164139268)/MultiDatastream",
    "FeatureOfInterest@iot.navigationLink": "http://zhwlapiprod002.ad.nerc.ac.uk:8080/FROST-Server/v1.1/Observations(164139268)/FeatureOfInterest"
}
```

### Results

Here are the results from some single value lookups:

---

FROST current query: 837 msec
```sql
SELECT "OBSERVATIONS"."ID" FROM "OBSERVATIONS" WHERE (1 = 1 AND "OBSERVATIONS"."PARAMETERS"::jsonb#>>'{ sen_id }' = CAST('164211863' AS varchar));
```

---

Direct primary key lookup: 396 msec
```sql
SELECT "ID" FROM "OBSERVATIONS" WHERE "ID" = 164211863;
```

---

Simple query on JSON parameters: 776 msec
```sql
SELECT "ID" FROM "OBSERVATIONS" WHERE "PARAMETERS" @> '{"sen_id": 164211863}';
```

---

Create an index on the JSON parameters: 9 secs
```sql
CREATE INDEX idxginp_observation_parameters ON "OBSERVATIONS" USING GIN ("PARAMETERS" jsonb_path_ops);
```

Repeat simple query on JSON parameters: 432 msec
Repeat FROST current query: 786 msec

### Discussion

Adding the index to the Parameters reduced the time for the simple JSON query by 50% but didn't affect the FROST query.  The improved time was similar to the time for a primary key lookup.

Let me know if there are other queries to try.

**Comment by hylkevds** [comment]
Cool, great test!

What STA query did you use? I'm a bit surprised by the `CAST` in the _FROST current_ query. I'd expect something like: 
```
where (true and "e0"."PARAMETERS"::jsonb#>'{ id }' = to_jsonb(?))
```
Though I don't expect that to have much difference on performance.

It's clear the current frost query can not use GIN indexes. Can the right-hand-side of the `@>` operator contain column/table references, or does it always have to be a fixed string?

Can you try adding the index:
```
CREATE INDEX "idx_obs_param_senid" ON "OBSERVATIONS" USING btree ("PROPERTIES"::jsonb #> '{sen_id}'::text[] ASC);
```
I would expect that index to give your query a performance similar to a direct primary key lookup. 

I'm a bit surprised at the duration of your _Direct primary key lookup_, 396 msec is quite slow. Our database of ~400 million Observations that one in less than a millisecond if the index has been read before and is cached. Did you run it multiple times? Can you also give the `explain analyze` output of the different queries? That would give a good insight in the details.

**Comment by volcan01010** [comment]
Some more results.  All the above was tested by running queries against database directly using pgAdmin.

These are with the same data, but now I have `slowQueryThreshold=0.1` so I can see what FROST does.

---

http://server/FROST-Server/v1.1/Observations?$select=@iot.id&$filter=parameters/sen_id%20eq%20164139283

```
frost_1  | 08:45:41.508 [http-nio-8080-exec-7] INFO     d.f.i.i.f.p.p.ResultBuilder - Slow Query executed in 467 ms:
frost_1  | select "OBSERVATIONS"."ID" from "OBSERVATIONS" where (1 = 1 and "OBSERVATIONS"."PARAMETERS"::jsonb#>'{ sen_id }' = to_jsonb(1)) limit 4001
```

---

http://server/FROST-Server/v1.1/Observations(164139283)
http://zhwlapiprod001.ad.nerc.ac.uk:8080/FROST-Server/v1.1/Observations(164139283)?$select=@iot.id

No query is logged as when looking up Observations based on their @iot.id.

---

I tried to create the index using various permutations of the command that you suggested, but I kept getting a syntax error.

`CREATE INDEX "idx_obs_param_senid" ON "OBSERVATIONS" USING btree ("OBSERVATIONS"."PARAMETERS"::jsonb#>'{sen_id}'::text[] ASC);`

results in 

```
ERROR:  syntax error at or near "#>"
LINE 1: ...VATIONS" USING btree ("OBSERVATIONS"."PARAMETERS" #> '{sen_i...
```

**Comment by hylkevds** [comment]
Ah there is a missing set of brackets in the index creation query. Try:
```
CREATE INDEX "idx_obs_param_senid" ON "OBSERVATIONS" USING btree (("PARAMETERS" #> '{ sen_id }') ASC);
```

**Comment by volcan01010** [comment]
I added the index with the revised command it and worked.  Request such as:

http://server/FROST-Server/v1.1/Observations?$select=@iot.id&$filter=parameters/sen_id%20eq%20164139286

are running in less than 0.1 millisecond. This compares to over 1100 milliseconds before.  `EXPLAIN ANALYSE` shows it runs a Bitmap Heap Scan followed by Bitmap Index Scan using the index, instead of the Parallel Seq Scan before.

**Comment by volcan01010** [comment]
So this suggests that putting a btree index on the particular PARAMETERS field that you are interested in will create and index that FROST can use.  Thanks!

**Comment by volcan01010** [comment]
Would you like me to update this page: https://fraunhoferiosb.github.io/FROST-Server/deployment/db_performance.html?

**Comment by hylkevds** [comment]
Yes, that would be very helpful, thank you!

**Comment by volcan01010** [comment]
Thanks for all your help, and thanks for FROST-Server.
