### ISSUE TITLE
Docker rebuild?

### ISSUE THREAD

**Issue by kensongzhu** [FraunhoferIOSB/FROST-Server#44]
Hello,

I just try to play a bit with the docker rebuild of the repo, I ran the cmd in the root folder following the construction on README 

**mvn dockerfile:build -pl FROST-Server**

[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: FROST-Server @ 
[ERROR] Could not find the selected project in the reactor: FROST-Server -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

If I tried following cmd, the build did start but it failed on  the **ADD** INSTRUCTION
 
**mvn dockerfile:build -pl FROST-Server.HTTP**
.....
[INFO]  ---> Using cache
[INFO]  ---> 374ffbd77c57
[INFO] Step 6/6 : ADD target/${WAR_FILE} /usr/local/tomcat/webapps/FROST-Server.war
[INFO] 
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder086415024/target/FROST-Server.HTTP-1.6-SNAPSHOT.war: no such file or directory

What am I missing here? Any help would be really appreciated. Thanks in advance

**Comment by hylkevds** [comment]
That should indeed be FROST-Server.HTTP.
Did you run `mvn install` before the docker command?

**Comment by kensongzhu** [comment]
Okay, I thought, it could run without previously running **mvn install**.
Now it works after **mvn install**,  it should be **mvn dockerfile:build -pl FROST-Server.HTTP**

Just a follow-up question,  I am still a bit confused about how to have customized configuration of context.xml in the Docker, as mentioned in the doc,  

> Make sure your adapted file is located in $CATALINA_HOME/conf/Catalina/localhost/FROST-Server.xml

Does it mean, I need to create a Dockerfile based on that image **fraunhoferiosb/frost-server: latest**,
Then **ADD** my customized FROST.xml to the path mentioned above?

Thanks 
kensong

**Comment by hylkevds** [comment]
Yes, I think that's how you do it, though I don't have much Docker experience yet.
You then also change the docker-compose.yaml to use your custom image instead of fraunhoferiosb/frost-server:latest

We're looking into ways to expose the configuration parameters using environment variables, since that would be cleaner.

**Comment by kensongzhu** [comment]
Already tried on Friday, however it seems no effect.  The service still takes context.xml as default configuration.  Now the only way that works for me is modifying the context.xml inside the FROST-Server.HTTP,  then rebuild the project and image.

**Comment by hylkevds** [comment]
In the latest version you can now override all configuration settings using environment variables. Could you try it out, to see if it works as you'd expect?

Since environment variables often do not allow the `.` character, you can use `_` instead.
