### ISSUE TITLE
Provide pre-built docker images also for the keycloak branch

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [FraunhoferIOSB/FROST-Server#46]
Since authentication/authorization is needed in many use-cases a pre-built docker image also for the keycloak branch would be great.

**Comment by phertweck** [comment]
We'll have I look into this. Maybe it's possible to build an additional docker image for each useful branch.

**Comment by hylkevds** [comment]
Since 1.9 Keycloak is part of the master branch
