### ISSUE TITLE
Java version of the SensorThings API entity model

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/FROST-Server#47]
Hi,

I’ve just created a library that exposes a Java version of the SensorThings API entity model: https://github.com/StoreConnect/sensorthings-api-model

As you may expect, idea is to provide a reusable library of the SensorThings API entity model for Java users.

Mainly developed for SensorThings API’s clients, I wonder if you will be interested to include it to the FROST-Server. This way, this library could be the bridge between a SensorThings API server and a SensorThins API client.

Note this model tries to be as tiny, simple and reusable as possible. From now, it covers:
- The default Sensing entities
- The SensorThings MultiDatastream extension

In a future release, it will also cover the SensorThings Data Array extension.

Any remark would be greatly appreciated :-) If you are interested we could imagine to iterate together to fit to your needs.

Regards,
Aurélien

**Comment by abourdon** [comment]
My bad, I just realized you already have the https://github.com/FraunhoferIOSB/FROST-Client project that does the job and even more.

Sorry guys, I close this issue
Aurélien

**Comment by hylkevds** [comment]
That's cool.
It's good to have multiple implementations of client libraries, since they tend to have a different focus, and different projects have different needs.
