### ISSUE TITLE
dataArray to MultiDatastream

### ISSUE THREAD

**Issue by cornelius-agrippa** [FraunhoferIOSB/FROST-Server#48]
Hello,

I'm trying to insert Observations using dataArrays on a MultiDatastream that has 3 ObservedProperties . However I'm not too sure how I should format my dataArray.

I was reading the standard format for Datastreams here: http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#83 So I'm trying to follow the convention by building an object like this for MultiDatastreams:
```
[
  {
    "MultiDatastream": {
      "@iot.id": 2
    },
    "components": [
      "phenomenonTime",
      "result"
    ],
    "dataArray": [
      [
        "2018-04-04T10:20:00-0700",
        [6, 10.0, 64]
      ]
    ],
    "dataArray@iot.count": 1
  }
]
```

However this gives me "error Missing Datastream or MultiDatastream.". 
The MultiDatastream is defined as follows:
```
{
    "name": "Wind",
    "description": "Wind is the perceptible natural movement of the air",
    "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation",
    "multiObservationDataTypes": [
        "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
        "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
        "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement"
    ],
    "unitOfMeasurements": [
        {
            "name": "deg",
            "symbol": "deg",
            "definition": "urn:ogc:def:uom:OGC:1.0:degree"
        },
        {
            "name": "m/s",
            "symbol": "m_s",
            "definition": "urn:ogc:def:uom:OGC::m_s"
        },
        {
            "name": "m/s",
            "symbol": "m_s",
            "definition": "urn:ogc:def:uom:OGC::m_s"
        }
    ]
}
```

It works fine for Datastreams, so I'm wondering if I'm formatting it correctly? 

Thanks in advance.

**Comment by hylkevds** [comment]
Your post formatting looks fine. It seems there is a bug with dataArray and MultiDatastreams.

**Comment by hylkevds** [comment]
It should work in the latest version now.

**Comment by cornelius-agrippa** [comment]
Yes, it works perfectly.

I'm using the keyCloak branch so I applied the fix manually on my end.

Thank you!
