### ISSUE TITLE
Cannot change PersistenceManager

### ISSUE THREAD

**Issue by image357** [FraunhoferIOSB/FROST-Server#50]
In my context.xml I have
```
<Parameter override="false" name="persistence.persistenceManagerImplementationClass" value="de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString" description="The java class used for persistence (must implement PersistenceManaher interface)"/>
```

However, when running FROST-Server, e.g. in debug mode in Netbeans, it defaults to
```
de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong
```

This is propably due to the changes in ``Settings.java`` from [this commit](https://github.com/FraunhoferIOSB/FROST-Server/commit/a15007b9a0a518edc1146d383287b5adc8d3117f), where in line 44 we now have:
```
wrapper.setProperty("persistence.persistenceManagerImplementationClass", "de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong");
```

Is there a new way to set/override the PersistenceManager?

**Comment by hylkevds** [comment]
That line 44 should not have been committed, that was just for testing.

**Comment by hylkevds** [comment]
Should work again.
