### ISSUE TITLE
mqtt with python paho.mqtt

### ISSUE THREAD

**Issue by chenkianwee** [FraunhoferIOSB/FROST-Server#506]
This is a question and not an issue. I have been using FROST-Server for some time and have been using the http protocols for posting and getting data from the database. I am interested in exploring the use of MQTT for my development. Thus, I am trying to understand how to connect to the MQTT broker of the FROST-Server. I am using the all-in-one Docker image and have deploy the server on the university server. I have been doing my http posting and getting through this url: https://andlchaos300l.princeton.edu:8080/FROST-Server . In this python script I am trying to subscribe to the Observations using the paho.mqtt library
```
import random
from paho.mqtt import client as mqtt_client

broker = 'andlchaos300l.princeton.edu'
port = 1883
topic = '/v1.0/Observations'
# generate client ID with pub prefix randomly
client_id = f'python-mqtt-{random.randint(0, 100)}'
username = ''
password = ''

def connect_mqtt() -> mqtt_client:
    def on_connect(client, userdata, flags, rc):
        print('trying to connect')
        if rc == 0:
            print("Connected to MQTT Broker!")
        else:
            print("Failed to connect, return code %d\n", rc)

    client = mqtt_client.Client(client_id)
    client.username_pw_set(username, password)
    client.on_connect = on_connect
    client.connect(host = broker, port=port)
    return client

def subscribe(client: mqtt_client):
    def on_message(client, userdata, msg):
        print(f"Received `{msg.payload.decode()}` from `{msg.topic}` topic")

    client.subscribe(topic)
    client.on_message = on_message

def run():
    client = connect_mqtt()
    print('connected to mqtt')
    subscribe(client)
    print('subscribed')
    client.loop_forever()
    print('looped')

if __name__ == '__main__':
    run()
```
I am getting an error msg '
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it' 

I am just wondering how should I connect to the MQTT broker. Thanks.

**Comment by hylkevds** [comment]
Do you have a firewall running on the machine, or in front of the machine, that blocks connections on port 1883?
What options did you use when starting FROST?

**Comment by chenkianwee** [comment]
I am not sure about the firewall, I am connecting within the university, so I think it shld be fine. I will try it out on a local machine and see if the codes work. When starting FROST set the mqtt port to be 1883. So the way I am specifiying the connection shld be correct in my code? THanks

**Comment by hylkevds** [comment]
I don't use python much, but it looks OK to me. The error you get means your client can not connect to FROST. That can be either because of a firewall, or because FROST is not listening on the given port. You should be able to confirm the latter from the logging output of FROST.

**Comment by chenkianwee** [comment]
I tried the code out on a local machine and it worked. So it must be some firewall blocking the ports on the university network. Thanks for the quick reply.  

```
import random
from paho.mqtt import client as mqtt_client

broker = '192.168.1.245'
port = 1883
topic = 'v1.0/Observations'
# generate client ID with pub prefix randomly
client_id = f'python-mqtt-{random.randint(0, 100)}'
username = ''
password = ''

def connect_mqtt() -> mqtt_client:
    def on_connect(client, userdata, flags, rc):
        if rc == 0:
            print("Connected to MQTT Broker!")
        else:
            print("Failed to connect, return code %d\n", rc)

    client = mqtt_client.Client(client_id)
    client.username_pw_set(username, password)
    client.on_connect = on_connect
    client.connect(host = broker, port=port)
    return client

def subscribe(client: mqtt_client):
    def on_message(client, userdata, msg):
        print(f"Received `{msg.payload.decode()}` from `{msg.topic}` topic")

    client.subscribe(topic)
    client.on_message = on_message

def run():
    client = connect_mqtt()
    subscribe(client)
    client.loop_forever()

if __name__ == '__main__':
    run()
```
