### ISSUE TITLE
question SensorThingsService loglevel

### ISSUE THREAD

**Issue by OodSigma** [FraunhoferIOSB/FROST-Server#515]
This is a question and not an issue.
We use the FROST-Server as a docker-container and as a tomcat installation. The log level is currently INFO. Unfortunately, we have not found a way to adjust the log level. Is there a way to set the logging to DEBUG?

**Comment by hylkevds** [comment]
Currently there is no easy way to do this, and we should probably use variables for the most common settings, as explained in https://www.cloudesire.com/configure-logback-log-level-via-environment-variables/
For now, you could try mapping a modified logback.xml into your container, and using an environment variable to make it active. Something along the lines of:
CATALINA_OPTS=-Dlogback.configurationFile=/path/to/config.xml

**Comment by OodSigma** [comment]
THX
