### ISSUE TITLE
Multiple Locations 

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#52]
Hello,

I try to connect several Locations to one Thing through HTTP, however, the second location keep overwrite the first one and make this Thing's Location remain one location.

Did anyone occur same problem or solve it?

Any help will be appreciated. Thanks a lot.

**Comment by hylkevds** [comment]
A Thing can only have 1 real-world location. Therefore, if you add a new Location to a Thing, the old location is automatically removed. 
A Thing can have multiple Location entities, but they have to be different encodings of the same real-world location. 
To link these multiple Location entities to the Thing, you have to link them all in the same request.

**Comment by smilehappy126** [comment]
Hi,
   Successfully create. However, it seems to be considered as one Location with two kinds of descriptions.
How can I create two different Locations Object just in one request.
![image](https://user-images.githubusercontent.com/26135719/39567223-d8c4b808-4ef0-11e8-865a-c7039c2bd3bd.png)

Thanks for answering.

**Comment by hylkevds** [comment]
That JSON looks fine to me. Locations is an array, with two objects in it.
If you format your JSON properly it'll be easier to recognise.

**Comment by smilehappy126** [comment]
Thanks a lot. The problem is fixed.

**Comment by smilehappy126** [comment]
Hi, 
Now with the Multiple Location, it seems that Observation can't automatically link Location as it's FeatureOfInterest.
How can I let the server automatically use the first Location object in Location Array as the Observation's FeatureOfInterest?

Thanks for answering.

**Comment by hylkevds** [comment]
Hmm, it seems it fetches the first Location it finds in the database. If that happens to be one of the non-geoJSON Locations, it'll fail. Which error message do you get?

**Comment by smilehappy126** [comment]
This is how the Locations Table looks like in my PostgreSQL:
![image](https://user-images.githubusercontent.com/26135719/39965965-1f0659ec-56d6-11e8-9fd7-e2f3389ea90b.png)
And the error code was "HTTP code 500", using Eclipse :
![image](https://user-images.githubusercontent.com/26135719/39966013-12ebc7fe-56d7-11e8-9e74-28d89edf9650.png)

**Comment by hylkevds** [comment]
Ok, that's the client side error, do you happen to have the server-side exception from the server logs?

**Comment by hylkevds** [comment]
It should work in the master branch now.

**Comment by smilehappy126** [comment]
You actually did a amazing job. Thanks a lot!

**Comment by smilehappy126** [comment]
Thanks for fixed it, the problem of FeatureOfInterest was solved.
However, there's something bad happened.

![image](https://user-images.githubusercontent.com/26135719/39974264-08ad921c-575a-11e8-98aa-9f8ee2f3dc74.png)
As the pic shows, the Location which was selected to be Observation's FeatureOfInterest disappeared in the /v1.0/Location, but it still remain in postgre's Location Table.
![image](https://user-images.githubusercontent.com/26135719/39974282-33b6327a-575a-11e8-87cc-5272bdcd7847.png)

**Comment by smilehappy126** [comment]
Oh, I found it when I orderby "@iot.id". Thanks a lot !!
