### ISSUE TITLE
Deleting observations for a MultiDatastream does not clear the MultiDatastream resultTime, phenomenonTime

### ISSUE THREAD

**Issue by ch08532** [FraunhoferIOSB/FROST-Server#549]
I was expecting that a delete call to our multidatastream/observations would result in the following to be nulled out in the MultiDatastream:

resultTime
phenomenonTime

However, what we are seeing is that the values persist. How does one clear these values when there is no observations?  My understanding these three values are computed based on recorded observations.

We tried a PUT and PATCH on the Multidatastream to null these values directly but still those values persist.

**Comment by hylkevds** [comment]
Datastream/resultTime and Datastream/phenomenonTime not being nulled out when deleting all Observations is a bug in the database trigger that updates those values. I've fixed it in the dev version.
Making those properties directly editable is discussed in #102

**Comment by ch08532** [comment]
@hylkevds , is this fix up on docker hub?  We have been using the latest tag but there appears to be a few tags.  Would you be able to direct me which one has the fix?

**Comment by hylkevds** [comment]
The fix is in develop-1.15.0-SNAPSHOT
I'll merge it into the release after my holiday.
________________________________
