### ISSUE TITLE
Extended Properties - V1.1 Request

### ISSUE THREAD

**Issue by KathiSchleidt** [FraunhoferIOSB/FROST-Server#56]
In order to provide fuller information, adding a properties element as in the Thing class would be most valuable. Through such an extension, we can even reach INSPIRE compliance :)
The properties extension would be required for the following classes:

- Datastream
- ObservedProperty

To my understanding, in Sensors the metadata element serves this purpose. What I'm not quite clear on is if the feature element of the FeatureOfInterest or the location element of Location can also be utilized for such additional information

**Comment by KathiSchleidt** [comment]
also on STA github as https://github.com/opengeospatial/sensorthings/issues/49

**Comment by hylkevds** [comment]
Great idea, that's why we've already implemented it. :)
Once it is added to the standard we might have to update our implementation, depending on the specifics.

**Comment by hylkevds** [comment]
It's in v1.1 and in FROST.
