### ISSUE TITLE
changing to client-generated ids with strings

### ISSUE THREAD

**Issue by kkehl-usgs** [FraunhoferIOSB/FROST-Server#569]
Hi,

In the documentation it shows I can change environment variables for the FROST Server as follows (yaml):

- Name: persistence_idGenerationMode
  Value: ServerAndClientGenerated

but the documentation doesn't show that I can do the same with the PostgresPersistenceManagerString setting.   Is that setting available as an environment variable or is it necessary to edit the context.xml?

Thanks!

**Comment by hylkevds** [comment]
Yes, that setting works for all three persistence managers, and all settings can be set using environment variables. See: https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html

Environment variables take higher priority over context.xml.
