### ISSUE TITLE
CSV result format - V1.1 Request 

### ISSUE THREAD

**Issue by KathiSchleidt** [FraunhoferIOSB/FROST-Server#58]
In order to make STA data more accessible, it would be valuable to provide a simple CSV result format

also on STA github under https://github.com/opengeospatial/sensorthings/issues/51

**Comment by hylkevds** [comment]
The development version now has a CSV ResultFormat, as described in:
https://github.com/INSIDE-information-systems/SensorThingsAPI/blob/master/CSV-ResultFormat/CSV-ResultFormat.md
