### ISSUE TITLE
Delete observations in a given time range for a particular datastream

### ISSUE THREAD

**Issue by kkehl-usgs** [FraunhoferIOSB/FROST-Server#584]
Hi,

Is it possible to do this?  I know you added the extension to delete from all Observations in a given time range, but is it possible to do something like this?

/FROST-Server/v1.1/Datastreams('6080360a43da4a64ae728e77ca89148e')/Observations?$filter=phenomenonTime ge '2021-07-20T19:15:00Z' and phenomenonTime lt '2021-09-01T13:00:00Z'?

When I try to delete with this, I'm getting an UnsupportedOperationException.  Is there an alternative way to do the same thing?  Thanks!

**Comment by hylkevds** [comment]
You should be able to send an HTTP DELETE to that URL and have it delete only those entities that match the filter. If the filter is valid, the delete should work.
Do note that times in URLs are not Strings and thus should not be quoted! So your URL should be:

```
/FROST-Server/v1.1/Datastreams('6080360a43da4a64ae728e77ca89148e')/Observations?$filter=phenomenonTime ge 2021-07-20T19:15:00Z and phenomenonTime lt 2021-09-01T13:00:00Z
```

**Comment by kkehl-usgs** [comment]
Thanks again!
