### ISSUE TITLE
Duplicated key error after manually inserting data to the database

### ISSUE THREAD

**Issue by EnocMartinez** [FraunhoferIOSB/FROST-Server#588]
I'm trying to load a huge amount of legacy data (around 30 GB in CSV files) into a FROST Server. Since loading this amount of data is very slow using the API, I'm using COPY from CSV files directly into the database (around 15.42 seconds for 500k observations). The idea is to load legacy data and afterwards start streaming real-time data via HTTP / MQTT.

My approach was to insert the first observation of each datastream via API, COPY the rest of them and finally insert the last observation via API.  However, after COPY I can't insert any further observations via API, because it throws this error:

''ERROR: duplicate key value violates unique constraint "OBSERVATIONS_PKEY" sensorthings    |   Detail: Key ("ID")=(9) already exists''

It looks that the server is never aware that new observations have been inserted and it keeps trying to add keys that are already used. I tried to restart the service and perform "database update"  after COPY, but I still get the same error. 

Is there any way to force an update so the server  gets the correct OBSERVATIONS_PKEY? Alternatively, is there another way to speed up the ingestion of huge amounts of data?

BTW, I can successfully GET all values from the API after a COPY, it is just affecting the POST.

**Comment by hylkevds** [comment]
I guess the data imported using COPY also included the ID column? In that case the IDs were not generated by PostgreSQL, and thus the sequence that is normally used to generate IDs was not updated.
You can use the following statement to set the sequence used for Observations to a correct value:
```
select setval('"OBSERVATIONS_ID_seq"', (select max("ID") from "OBSERVATIONS") );
```

**Comment by EnocMartinez** [comment]
Thanks for your prompt answer! Yes the COPY included the ID. After running the statement the API works again. Thanks a lot.

**Comment by hylkevds** [comment]
You're welcome.
By the way, with a large data set, don't forget to monitor your queries/performance and add relevant indices to improve performance.
