### ISSUE TITLE
FROST-Server.HTTP::ContextListener MqttManager.shutdown() does not appear to be necessary

### ISSUE THREAD

**Issue by selimnairb** [FraunhoferIOSB/FROST-Server#62]
`MqttManager.shutdown()` is called in `ContextListener.contextDestroyed()`, but`MqttManager.init(...)` does not call `ContextListener.contextInitialized()`.  See [here](https://github.com/FraunhoferIOSB/FROST-Server/blob/86e1b2d19e474b26514e5d007302f7ad24a3dd30/FROST-Server.HTTP/src/main/java/de/fraunhofer/iosb/ilt/sta/ContextListener.java#L68).  This should be harmless, but the call to `MqttManager.shutdown()` should be removed as it does not appear to be necessary.  This may be an artifact leftover from when there was not a standalone HTTP server.  (Or I could be wrong and the call to `shutdown()` is necessary.)

**Comment by hylkevds** [comment]
Ah, yes, in the stand-alone HTTP package the call to MqttManager.shutdown() is pointless, but harmless. It checks if there really is an instance of the MqttManager before doing anything.

**Comment by hylkevds** [comment]
I've removed the call.
