### ISSUE TITLE
Save the Date: Tuesday 11.9.2018: OGC SensorThings API Summit, Stuttgart, Germany.

### ISSUE THREAD

**Issue by hylkevds** [FraunhoferIOSB/FROST-Server#63]
on the occasion of the OGC TC/PC Meetings in Stuttgart, Germany the OGC organises a special

## OGC Summit on SensorThings API – Technology and Applications

on Tuesday, 11 Sep 2018

The objective of this summit is to gather the user and provider community that is interested in the current technology, applications and the future of the OGC SensorThings API standards. Experts who are member of the OGC working groups pursuing the development of this standard will discuss with users who are applying this standard already now in software applications of various domains.

The summit will take place on the occasion of the OGC TC/PC meetings at the HFT Stuttgart, Germany, on Tuesday, 11 Sep 2018, between 10 am and 5 pm.

### Agenda template
* 10.00-13.00
  *  SensorThings API standard and implementations
  * Relationship to the OGC Sensor Web Enablement standards
* 14.00-17.00
  * Applications and projects – use cases and experiences
  * Round-table about the next steps

### Summit and Program Co-Chairs
* Dr. Thomas Usländer, Fraunhofer IOSB, Germany
* Dr. Steve Liang, University of Calgary, Canada / SensorUp

### Organizational Chair
* Prof. Dr. Volker Coors, HFT Stuttgart, Germany

### Registration:
http://ogcmeet.org/#specialevents

**Comment by hylkevds** [comment]
The latest version of the agenda can be found here: https://www.iosb.fraunhofer.de/servlet/is/85589/

**Comment by EOSIT** [comment]
Were there any outputs from this summit that can be viewed online?

**Comment by hylkevds** [comment]
Public publication of the presentations should follow hopefully soon. OGC members can already access them through the OGC portal.

Here is the report for the closing plenary of the OGC Meeting:
[2018_Stuttgart_OGC Summit SensorThingsAPI - report for closing plenary.pdf](https://github.com/FraunhoferIOSB/FROST-Server/files/2449761/2018_Stuttgart_OGC.Summit.SensorThingsAPI.-.report.for.closing.plenary.pdf)

**Comment by hylkevds** [comment]
A zip file with all presentations can be found at the OGC portal at: https://portal.opengeospatial.org/files/?artifact_id=81432
The presentation of Steve Liang is separate and will follow soon.

**Comment by mjacoby** [comment]
The link to the OGC portal seems to be down
