### ISSUE TITLE
Quotationmarks in URLs using IDs

### ISSUE THREAD

**Issue by image357** [FraunhoferIOSB/FROST-Server#64]
Hey,

we have a problem using the grafana dashboard (https://code.linksmart.eu/projects/OGC-ST/repos/grafana-sensorthings-datasource/browse) on top the FROST-Server with string ids.
We could track it down to the presence of quotationmarks inside the brackets of urls that use ids.
Are these quotationmarks part of the standard? (http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#38)

Currently it is:
```
@iot.id    "geo.uni-augsburg.de/Fixed-Wing-UAV-0" 
@iot.selfLink    "http://localhost:8080/FROST-Server/v1.0/Things('geo.uni-augsburg.de/Fixed-Wing-UAV-0')" 
```

we would need and think it should be:
```
@iot.id    "geo.uni-augsburg.de/Fixed-Wing-UAV-0" 
@iot.selfLink    "http://localhost:8080/FROST-Server/v1.0/Things(geo.uni-augsburg.de/Fixed-Wing-UAV-0)" 
```
Do note: the result is unparsable by frost.
Should ids be escaped according to url schemes? (https://tools.ietf.org/html/rfc3986)
```
@iot.id    "geo.uni-augsburg.de/Fixed-Wing-UAV-0" 
@iot.selfLink    "http://localhost:8080/FROST-Server/v1.0/Things(geo.uni-augsburg.de%2FFixed-Wing-UAV-0)" 
```

Thank you for you reply and opinion on this topic.

Cheers,
Marcel Köpke

**Comment by hylkevds** [comment]
Yes, according to OData, String constants in URLs are quoted using single quotes, also for IDs in brackets. For an example, see [4.3.5 Alternate Keys](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AlternateKeys) of OData Version 4.01. Part 2: URL Conventions

Special characters inside the string will still have to be url encoded as well.

**Comment by image357** [comment]
Ok thanks. The dashboard has to be extended to handle string constants according to OData then.

Should the URL encoding of string IDs be enforced by the server?

**Comment by hylkevds** [comment]
There is no real need for that. If a string contains characters that make the URL invalid the request will simply fail. Browsers also sometimes cause trouble with urlencoded / (%2F) in the part of the URL before the "?".

The String ids are not tested quite as much, especially with URIs as IDs, so it is quite possible that there are some bugs there.

**Comment by image357** [comment]
Currently I can create both ids 'foo/bar' and 'foo%2Fbar' as different entities.
However, the following GET querry:
`http://localhost:8080/FROST-Server/v1.0/Things('foo%2Fbar')`
ends with an error code 400 (bad request) while 
`http://localhost:8080/FROST-Server/v1.0/Things('foo/bar')`
works

**Comment by image357** [comment]
Can/should I add a check on the id format to the IdGenerationHandler?

**Comment by hylkevds** [comment]
A quick google search for tomcat %2f in url shows that the problem might be with Tomcat itself. It seems Tomcat translates foo%2Fbar to foo/bar before handing it to FROST. This might need some debugging to see what happens exactly.

**Comment by hylkevds** [comment]
I've done some more testing, and urlencoding a / in the part of a url before the ? is not allowed. This is a security measure of Tomcat, to make sure the user can recognise what is being requested.

So for a Thing with an ID of `http://server.de/things/mine`, the selflink is `http://localhost:8080/FROST-Server/v1.0/Things('http://server.de/things/mine')`

If you have a Thing with [ and ] in the id, like `things[mine]`, the [ and ] have to be urlencoded in the self-link: http://localhost:8080/FROST-Server/v1.0/Things('things%5Bmine%5D')
The generated selfLinks currently do not do this, that's a bug.

**Comment by hylkevds** [comment]
FROST-Server now generates correct self and next links.
FROST-Client can now also properly behaves when IDs are URLs. I had to remove the use of URI.normalise, since it would replace the `http://example.com` with `http:/example.com`...
