### ISSUE TITLE
Suppress automatic creation of HistoricalLocation

### ISSUE THREAD

**Issue by image357** [FraunhoferIOSB/FROST-Server#66]
Hey,

consider the following scenario:
A mobile sensor loses connectivity and buffers its GPS locations with timestamps. When it reconnects it tries to update the database with its buffered locations, hence it successively creates new Location entities for a given Thing entity.

Currently, there is a default behavior that a HistoricalLocation (HL) is created with the server's system time when no HistoricalLocation is present.

However, this default HL is always created when a Location is linked to a Thing no matter if there is already a different HL linked to that Location.

Take a post request to `FROST-Server/v1.0/Things('thingid')/Locations` with:
```
{
  "name": "UofC CCIT",
  "description": "University of Calgary, CCIT building",
  "encodingType": "application/vnd.geo+json",
  "location": {
    "type": "Point",
    "coordinates": [-114.133, 51.08]
  },
  "HistoricalLocations": [{
   "time": "1999-09-19T19:19:09.999Z"
   }]
}
```

This will **not** create and link a 1999 HL to either the Thing or Location. It will create the default HL. This also happens if I inline the ThingId:
```
{
  "name": "UofC CCIT",
  "description": "University of Calgary, CCIT building",
  "encodingType": "application/vnd.geo+json",
  "location": {
    "type": "Point",
    "coordinates": [-114.133, 51.08]
  },
  "HistoricalLocations": [{
   "time": "1999-09-19T19:19:09.999Z",
   "Thing": {"@iot.id": "thingid"}
   }]
}
```

I have tried several different ways of getting around this. For instance, creating HL with inline Location with inline ThingID. This will create the 1999 HL but also create a second one (the default system time one), which is false because the Thing wasn't at that Location when the querry was made.

Is there a propper way of creating and linking a Location together with a predefined HL to a Thing without invoking a default HL?

**Comment by hylkevds** [comment]
This is partly covered in the topic https://github.com/opengeospatial/sensorthings/issues/30 on the SensorThings API issues list. I proposed a solution there. Could you have a look at that, and, if that solution would work for your case, chime in on that topic? The more feedback we get, the more likely the next version of the standard has the right changes.

A HistoricalLocation is created whenever the Location of a Thing changes. Regardless of whether this is done by adding the Thing to the Location, or the Location to the Thing.
Such an automatically generated HL always has the current system time.

In your cast, with a backlog of Locations, in the current version of STA, you could:
1. Create the Locations, but not link them to the Thing.
2. Link the last location to the Thing. This will generate a HL with the wrong time.
3. Change the time on the generated HistoricalLocation.
4. Finally, manually create the missing HistoricalLocations.

The standard states that user are not supposed to manually generate HLs, except when importing old data. Your use-case would qualify for that exception :)

It's quite a round-about way to get the desired result, so I might implement the solution I proposed in the topic I referenced above before it makes it into the next version of the standard.

**Comment by hylkevds** [comment]
The master branch now contains this feature. If you create a HistoricalLocation, and the time if this HistoricalLocation is later than any other HistoricalLocation for the given Thing, then the Locations of the Thing are set to the Locations of the newly created HistoricalLocation.
