### ISSUE TITLE
No authentication required for MQTT?

### ISSUE THREAD

**Issue by tfeseker** [FraunhoferIOSB/FROST-Server#667]
Hi,

I have a question concerning authentication for MQTT-connections to the FROST server:

I am running an HTTP-FROST-Server in Tomcat on machine A (Centos Linux). The pgsql db is on the same machine A. Everything works fine, including authentication, which is required for any HTTP-access to the data.

Now I have added an MQTT-FROST-Server on machine B (also Centos Linux) and connected it to the existing HTTP-FROST-Server on machine A using a mosquitto broker on machine A as message bus. The MQTT-FROST-Server on machine B is connected to the same pgsql database on machine A. The MQTT-FROST-Server we are using is

https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.MQTT/1.13.0/FROST-Server.MQTT-1.13.0-jar-with-dependencies.jar

My FrostMqtt.properties-file is stored in the same folder and supplied as an argument when starting the jar-file.

The communication between the two FROST servers on the message bus seems to work just fine. However, it is possible to connect to the MQTT-FROST-Server on machine B without any authentication, subsribe to any topic and even publish new observations. That seems really odd.

Is there really no authentication for MQTT-connections to FROST-Servers?

Tom

**Comment by hylkevds** [comment]
There is authentication on the MQTT component, but you have to turn it on. You can add the same settings that you used for the HTTP component to the FrostMqtt.properties file.

**Comment by tfeseker** [comment]
Thanks for the quick reply!

I just used the properties file from GitHub as a template and didn't notice that the auth provide was not set. Adding the following parameters solved my problem;

auth.provider=de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
auth.db.url=jdbc:postgresql://xxx
auth.db.username=xxx
auth.db.password=xxx
auth.allowAnonymousRead=false
auth.role.read=read
auth.role.create=create
auth.role.update=update
auth.role.delete=delete
auth.role.admin=admin

Is there a full documentation of all parameters anywhere?

**Comment by hylkevds** [comment]
Yep, on the documentation site: https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html

**Comment by tfeseker** [comment]
Oops. Thank you!
