### ISSUE TITLE
No documentation for mqtt.WaitForEnter

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/FROST-Server#67]
Hi,

When starting the FROST-Server's MQTT service, it complains because of the missing `mqtt.WaitForEnter` configuration value:

```
11:47:44.755 [            main] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for mqtt.WaitForEnter, using default value false.
```

But when reading the [settings documentation file](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc), there is no information about it.

Could you please update the settings documentation file to add this parameter?

Thanks

**Comment by hylkevds** [comment]
Good point, I've added it to the settings.
