### ISSUE TITLE
Discarded null or empty geojson Feature properties in Location

### ISSUE THREAD

**Issue by pbaumard** [FraunhoferIOSB/FROST-Server#693]
**Bug reproducible steps**

1. Insert a location with either:
```json
{
  "name": "CCIT",
  "description": "Calgary Center for Innovative Technologies",
  "encodingType": "application/geo+json",
  "location": {
    "properties": null,
    "type": "Feature",
    "geometry":{
      "type": "Point",
      "coordinates": [-114.06,51.05]
    }
  }
}
```
or
```json
{
  "name": "CCIT",
  "description": "Calgary Center for Innovative Technologies",
  "encodingType": "application/geo+json",
  "location": {
    "properties": {},
    "type": "Feature",
    "geometry":{
      "type": "Point",
      "coordinates": [-114.06,51.05]
    }
  }
}
```
2. then retrieve the inserted location

**Expected result**

Should get the same location properties value as inserted.

**Actual result**

The properties are discarded in retrieved location, which is:

```json
"location": {
    "type": "Feature",
    "geometry":{
      "type": "Point",
      "coordinates": [-114.06,51.05]
    }
  }
```

**Notes**

1. Above examples are modified from [OGC SensorThings API Part 1: Sensing Version 1.1 - example 2](https://docs.ogc.org/is/18-088/18-088.html#location).
Note that the SensorThings 1.1 example 2 with missing feature properties is actually invalid GeoJSON according to [GeoJSON RFC 7946](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2)

>    o  A Feature object has a member with the name "properties".  The
>       value of the properties member is an object (any JSON object or a
>       JSON null value).

2. I noticed this bug when I tried to add LOCATION column json schema constraint using [postgres-json-schema](https://github.com/gavinwahl/postgres-json-schema)
```bash
# GeoJSON schema is also valid against JSON schema draft 4
# Set properties as optional as a workaround from FROST bug
curl https://geojson.org/schema/GeoJSON.json | sed 's|draft-07|draft-04|g' | sed 's|"properties",||g' > /tmp/GeoJSON.json
echo "ALTER TABLE \"LOCATIONS\" ADD CONSTRAINT location_valid_geojson CHECK (validate_json_schema('$(cat /tmp/GeoJSON.json)'::jsonb, \"LOCATION\"::jsonb));" >> /tmp/json-schema-validation.sql
```

**Comment by hylkevds** [comment]
Indeed. I've fixed it in the 2.0 branch.
