### ISSUE TITLE
Keycloak server with self signed certificate

### ISSUE THREAD

**Issue by Okanmercan99** [FraunhoferIOSB/FROST-Server#694]
I have a self signed certificated keycloak server for development. I give config file to FROST-Server and FROST-Server starts as normal. However when i try to reach https://<frost-server-url>/FROST-Server/v1.1 it returns HTTP 500. 

Log file:
![image](https://user-images.githubusercontent.com/44125929/147103154-4b992e25-6acf-42eb-be18-fefb790abeb6.png)

As i understand, it does not accept self signed certificate. Are there any way to let frost connect self signed certificated keycloak?

Thank you for your help,

**Comment by hylkevds** [comment]
If keycloak does not have an option to ignore certificate errors, the only option I see is adding the certificate you used to sign your self-signed certificate to the trust store in the docker image. You can build a new docker image, based on the FROST image, that adds the certificate to the trust store.

**Comment by qwertZ1984** [comment]
Hello, same Problem here.
How can i build a new image with certs in trusted store?
I can't run update-ca-certificates because i'm not root on the container.

**Comment by hylkevds** [comment]
You can specify the user to use when executing commands in a docker container using the `-u` option.

**Comment by qwertZ1984** [comment]
Hello. I build a new image and add 

COPY full.pem /usr/local/openjdk-11/lib/security/
RUN \
    cd /usr/local/openjdk-11/lib/security/ \
    && keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias stlcert -file full.pem
 to Dockerfile.
If i look into the running docker containter i can see my certificate but the error is still present.

Did i miss something?

**Comment by qwertZ1984** [comment]
I resolve the issue. 
The keytore is /opt/java/openjdk/lib/security/cacerts.
