### ISSUE TITLE
Elastic Search for SensorThingsServer?

### ISSUE THREAD

**Issue by geoxanadu** [FraunhoferIOSB/FROST-Server#7]
Hi,

since the amount of sensordata is growing fast the question raises if there are plans to implemented  other data storages (i.e. Elastic Search) in the server or if you stick with PostGIS?

best regards

**Comment by hylkevds** [comment]
What is "fast" in your case?

We do not have concrete plans to implement other data storage backends at the moment, but the architecture is flexible enough to allow it. We, of course, warmly welcome code contributions :)

Note that the hard part will be implementing the filtering and expression language on any database that does not support these features natively.

**Comment by geoxanadu** [comment]
Hi,

fast means, that there will be easily (ten) thousands of sensors within  the next year (at least from my point of view :) )

**Comment by hylkevds** [comment]
Well, in that case you should also have the resources to set up a proper [PostgreSQL cluster](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling).

The biggest issue I see with non-relational data storage systems is how to implement the query capabilities.
Of course, if you do not need the Full relational query capabilities that the SensorThings API offers, you could use the SensorThings API for storing metadata, but store the observations themselves in Elasticsearch.

**Comment by adrhc** [comment]
taken from [postgresql 9.6 documentation](https://www.postgresql.org/docs/9.6/static/creating-cluster.html):
Before you can do anything, you must initialize a database storage area on disk. We call this a database cluster. **A database cluster** is a collection of databases that is managed by a **single instance of a running database server**.

I see no performance benefit o using a postgresql cluster.
I too would like an elasticsearch based solution.

**Comment by hylkevds** [comment]
The page you quoted has nothing to do with replication, load balancing or performance. The term "cluster" in that page means something different.

I won't have time (or the need) to implement an elasticsearch based back-end any time soon, but I'll happily accept quality pull request.

**Comment by adrhc** [comment]
I agree with you so better saying is that for using many instances of Postgres ("true" cluster) with same database (meaning same set of files) one should use additional software as you already [pointed](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling).

**Comment by hylkevds** [comment]
Someone recently pointed me at https://www.citusdata.com 
This might be an easy way to scale up a PostgreSQL database. I don't have any experience with it, so if anyone knows more it would be great if they could share their experiences.

**Comment by hylkevds** [comment]
Since I don't think anybody is going to implement an elasticsearch back-end any time soon, I'll close this issue.
