### ISSUE TITLE
Unexpected behavior with @iot.nextLink

### ISSUE THREAD

**Issue by Jabst** [FraunhoferIOSB/FROST-Server#72]
Hello,

I am writing a client-side pagination and I use the @iot.nextLink of every GET response to retrieve the remaining entities. However I have noticed that in the latest release of the FROST server (with serverTop=2 in the context.xml) for the following request: https://coral-tools.inesctec.pt/tomcat/sensorthings/v1.0/Datastreams?$expand=Thing,Sensor,ObservedProperty I get the first two Datastream entities(because of the serverTop being equal to 2) but afterwards I do the following request: https://coral-tools.inesctec.pt/tomcat/sensorthings/v1.0/Datastreams?$skip=2&$expand=Thing,Sensor,ObservedProperty and my FROST server returns all of the other datastreams(starting from the third but ignoring the top rule because it returns more than 2 entities).

I have tested the very same with an older version of the FROST server and the behavior is different, where the response in this case only contains two entities, as expected.

Is this a bug or do I have to specify the $top query parameter from now on?

**Comment by Jabst** [comment]
Apparently this only occurs if you have two different FROST server implementations with different defaultTop accessing the same database.

**Comment by hylkevds** [comment]
There should be no interaction between two FROST instances that access the same database, so this should not happen. Can you still reproduce it?
