### ISSUE TITLE
Tomcat deployment issue

### ISSUE THREAD

**Issue by aarathimuppalla** [FraunhoferIOSB/FROST-Server#734]
I tried deploying pre-compiled war files in Tomcat. Only the homepage of FROST server is visible. All other webpages are failing with 404 not found error. Please help. I tried with maven installation with 1.15 and 1.13 versions. I am facing the same issue.
I maybe missing something. 

I followed the documentation available on https://fraunhoferiosb.github.io/FROST-Server/deployment/tomcat.html for configuration for database configuration. Even if there is an issue with the database, I think I should not see 404 error. 

Please help.

I am attaching the homepage I am seeing below.
![image](https://user-images.githubusercontent.com/20355226/150833475-3c6b991b-49f5-4383-b021-25bb3ef52b0e.png)

**Comment by hylkevds** [comment]
What's the output in the log files?
What are the exact URLs that give you 404s?

**Comment by aarathimuppalla** [comment]
These are the URLs or which I am getting 404 errors. Log file doesn't show anything except  404 errors.
/FROST-Server.HTTP-1.15.0-SNAPSHOT/DatabaseStatus
/FROST-Server.HTTP-1.15.0-SNAPSHOT/v1.1
/FROST-Server.HTTP-1.15.0-SNAPSHOT/v1.0

I copied the war file in the Tomcat webapps folder. Will that be enough or Am I missing something?

**Comment by hylkevds** [comment]
The log file gives you all settings FROST-Server loads. It's generally called catalina.[date].log
After copying the war, you have to configure the database connection and base URL.

**Comment by aarathimuppalla** [comment]
Thanks for your help. The problem is with my tomcat installation. I reinstalled it correctly and it worked.
