### ISSUE TITLE
Configure correct server name for inclusion in results

### ISSUE THREAD

**Issue by EOSIT** [FraunhoferIOSB/FROST-Server#76]
Please can you point me to the docs where it described thow to configure the server name in the output response. At present it just shows `localhost:8080`:
```
{
    "name" : "pH",
    "definition" : "https://en.wikipedia.org/wiki/PH",
    "description" : "pH is a logarithmic scale used to specify the acidity or basicity of an aqueous solution.",
    "Datastreams@iot.navigationLink" : "http://localhost:8080/FROST-Server/v1.0/ObservedProperties(4)/Datastreams",
    "MultiDatastreams@iot.navigationLink" : "http://localhost:8080/FROST-Server/v1.0/ObservedProperties(4)/MultiDatastreams",
    "@iot.id" : 4,
    "@iot.selfLink" : "http://localhost:8080/FROST-Server/v1.0/ObservedProperties(4)"
  }
```

The actual machine is residing at an address with the form `http://machinename.dhcp:8081/FROST-Server/`

The software is installed via Docker on that machine.

**Comment by hylkevds** [comment]
https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc
Change the `serviceRootUrl` to your externally exposed path.

**Comment by EOSIT** [comment]
I am using the Docker install; is there an external config file in which this setting should be placed?  If so, what is it and how should it passed to the container at runtime?  If not, is there another way of providing this setting (e.g. in an `.env` file)?

**Comment by EOSIT** [comment]
That's working, thanks.
