### ISSUE TITLE
could not access file "$libdir/postgis-2.4" after docker image upgrade

### ISSUE THREAD

**Issue by hylkevds** [FraunhoferIOSB/FROST-Server#78]
After upgrading the `mdillon/postgis` docker image you probably will run into the following exception:
```
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
```

This is because PostGIS was upgraded to version 2.5, and the `mdillon/postgis` docker image does not automatically upgrade the database to reflect this. To fix this, you have to run the `update-postgis.sh` in the container:
```
# Find out the database container id
docker ps
# Get a shell into the database container
docker exec -i -t [database container id]  /bin/sh
# Run the update script
/usr/local/bin/update-postgis.sh
```

Also see: https://github.com/appropriate/docker-postgis/issues/110

**Comment by MBARIMike** [comment]
I'm getting the same error and tried the suggested fix with this change to the last line:
```
POSTGRES_USER=postgres /usr/local/bin/update-postgis.sh
```
Resulting in this output:
```
Updating PostGIS extensions 'template_postgis' to 2.5.1
NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_topology" already exists, skipping
NOTICE:  extension "fuzzystrmatch" already exists, skipping
NOTICE:  extension "postgis_tiger_geocoder" already exists, skipping
ALTER EXTENSION
Updating PostGIS extensions '' to 2.5.1
NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_topology" already exists, skipping
NOTICE:  extension "fuzzystrmatch" already exists, skipping
NOTICE:  extension "postgis_tiger_geocoder" already exists, skipping
ALTER EXTENSION
```
After restarting my containers I still get:
```
could not access file "$libdir/postgis-2.4": No such file or directory
```

I have existing databases; do I need to update the extensions on them too?

**Comment by MBARIMike** [comment]
Aha! The `update-postgis.sh` script accepts arguments. I was able to fix things for my existing databases with (for example):
```
POSTGRES_USER=postgres /usr/local/bin/update-postgis.sh stoqs stoqs_simz_aug2013
```

**Comment by jonnysandu** [comment]
@MBARIMike Do you still experience this issue from time to time? I recently bumped into it again, running update-postgis.sh on the `mdillon/postgis` fixed the problem, but it's weird that it's happening in the first place every now and then.

**Comment by hylkevds** [comment]
This will (unfortunately) always happen when PostGIS is updated. That's one of the reasons one should never use "latest" in a production environment, and make a database backup before upgrading PostgreSQL or PostGIS.

Note that there are now "official" PostGIS docker images: [postgis/postgis](https://hub.docker.com/r/postgis/postgis)

**Comment by MBARIMike** [comment]
I haven't experienced the problem since first reporting it.
