### ISSUE TITLE
Problems with PATCH and PUT

### ISSUE THREAD

**Issue by hk298** [FraunhoferIOSB/FROST-Server#79]
Newbie here...
I created a Thing and now I'm trying to update it. However neither PATCH nor PUT is working for me. I'm a using an up-to-date docker container with a docker-compose file based on the one supplied on your site. Creating, reading and deleting objects works fine.

Here's the curl command I'm using:
```
curl -X PUT -H "Content-Type: application/json" -d '{  \
   "description": "new description"   \
}' "http://localhost:8080/v1.0/Things(4)"

```
The server replies with:
```
HTTP Status 403 – Forbidden
The server understood the request but refuses to authorize it.

```
When I use PATCH, requests are replied to with:
```
HTTP Status 501 – Not Implemented
Method [PATCH] is not implemented by this servlet for this URI
The server does not support the functionality required to fulfill the request.

```
Here are my docker-compose environment settings:
```
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - http_cors_allowed_methods=OPTIONS,GET,POST,PUT,PATCH,DELETE
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true

```

What am I doing wrong?

**Comment by hylkevds** [comment]
Did you add a reverse proxy? If not, then you are missing the `FROST-Server/` bit from your urls.
Try a PUT or PATCH to `http://localhost:8080/FROST-Server/v1.0/Things(4)`

**Comment by hk298** [comment]
Oh, that's embarrassing. The cURL snippet I used was a leftover from a test with another SensorThings implementation that does not require this bit. After correcting the URL, it worked as expected. PATCH works fine with the JSON from my example. PUT gives me 400 Bad Request, but that's according to spec (Section 10.3.1).

Thanks for your quick reply.

**Comment by hylkevds** [comment]
No problem, happens to us all.
Let us know if you have any other issues or questions.
