### ISSUE TITLE
Response body for OData compliance

### ISSUE THREAD

**Issue by emdekatharina** [FraunhoferIOSB/FROST-Server#796]
In order to be compliant with the OData specification, the FROST Server should send a response body along with the answer to a POST request

**Comment by hylkevds** [comment]
Relevant sections from the OData standard:

- 11.4.2 [Create an Entity](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_CreateanEntity)
- 8.2.8.7 [Preference return=representation and return=minimal](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_Preferencereturnrepresentationandret)

**Comment by hylkevds** [comment]
Should be fixed in the develop-2.0 branch now.
