### ISSUE TITLE
Java 11 support?

### ISSUE THREAD

**Issue by selimnairb** [FraunhoferIOSB/FROST-Server#81]
With the pending loss of a free and updated Java 8 implementation, have you given any thought to updating the master POM to support JDK 11?  This would not be required to run FROST on JDK 11 (one could still run 1.8 code on JDK 11), but since many people will likely be running JDK 11+, it would be nice to be able to start using features from JDK 9+.

**Comment by hylkevds** [comment]
I've made a branch that seems to compile on java 11, and still run on 8. Can you try it out and see if there are any problems with it?

**Comment by selimnairb** [comment]
I can do some testing over the next few days.  A quick question, does the Travis CI pipeline run conformance tests after builds?  If so, we could test the jdk11 branch through the pipeline to ensure that there are no regressions compiling and running under JDK 11.  Note that this would at least require updating `.travis.yml` to use `openjdk11`, but might be more involved in that, as per [here](https://www.deps.co/guides/travis-ci-latest-java/).

**Comment by hylkevds** [comment]
Currently the build does not automatically run the conformance tests. It would be nice to have, ideally already during the maven tests, using something like https://github.com/testcontainers/testcontainers-java

**Comment by hylkevds** [comment]
The jdk11 branch is now also built on Travis.
Docker image has the tag jdk11-1.10-SNAPSHOT
I'll probably merge it into master in the near future.

**Comment by hylkevds** [comment]
I've merged the jdk11 branch.
