### ISSUE TITLE
HTTP Request Header

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#83]
Hi,
     I'm currently working on a web service to provide account control about SensorThingsAPI.It needs 
 to replace the origin STA url in original STA web service GET response to mine web service url.
But I encounter something wrong with the content-length due to string replace. However, I copy the original response body and count it in : https://reurl.cc/bn7d3
I got a different count answer compare to SensorThingsAPI response header "Content-Length".
Can I ask how's the counting work in SensorThingsAPI? 
And how do I replicate the counting process to count the same answer as STA did?

Thanks a lot.

**Comment by smilehappy126** [comment]
I see. Thanks for answering.
That website has a dropdown list, it can switch to UTF-8 convert.

**Comment by hylkevds** [comment]
The tests that I ran show correct content-lengths. If you have a specific example that shows an incorrect length, just re-open this issue.
