### ISSUE TITLE
Docker image 1.9 doesn't start

### ISSUE THREAD

**Issue by hk298** [FraunhoferIOSB/FROST-Server#89]
I'm having an issue with the latest Docker image. Tomcat starts, but http://localhost:8080/FROST-Server/v1.0 gives me a 404. The log says in line 82 that "one or more listeners failed to start".
I'm using docker-compose with a yaml file that works fine with 1.8.

[docker_1-9.log](https://github.com/FraunhoferIOSB/FROST-Server/files/2669577/docker_1-9.log)

**Comment by ManfredSchenkIOSB** [comment]
I can confirm the 404 here: the docker-compose.yaml leads to the 404, the docker-compose-seperated.yaml works for me.

**Comment by hylkevds** [comment]
The problem was that the auth.provider option was requested without a default value.
Adding an empty auth.provider option fixes it. The next build will also fix it.

**Comment by hk298** [comment]
Yes, it works with an empty auth.provider option.

How about non-empty auth options? Here's what I have in the configuration:
```
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - http_cors_allowed_methods=OPTIONS,GET,POST,PUT,PATCH,DELETE
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - auth_provider=de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
      - auth_db_driver=org.postgresql.Driver
      - auth_db_url=jdbc:postgresql://database:5432/sensorthings
      - auth_db_username=sensorthings
      - auth_db_password=ChangeMe
      - auth_realmName=test
      - auth_autoUpdateDatabase=true
```
and this is what I find in the log:
```
INFO   d.f.i.i.sta.settings.Settings - Setting auth.provider has value de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider.
INFO  d.f.i.i.f.h.c.AbstractContextListener - Turning on authentication.
SEVERE org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
SEVERE org.apache.catalina.core.StandardContext.startInternal Context [/FROST-Server] startup failed due to previous errors
INFO  d.f.i.i.f.h.c.AbstractContextListener - Context destroyed, shutting down threads...
```

**Comment by hylkevds** [comment]
I've written some documentation on the auth mechanism in [auth.adoc](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/auth.adoc), the settings are also described in the normal settings document [settings.adoc](https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc).

I'll look into why there is no proper error message on the console when something goes wrong this early in the startup.
