### ISSUE TITLE
Pushing data from MQTT

### ISSUE THREAD

**Issue by rouvoy** [FraunhoferIOSB/FROST-Server#92]
What is the status of support for MQTT in FROST-Server? It seems limited to querying data, but does not seem to support data uploads. Is that correct? If so, is there any planned support for such a feature?

**Comment by mjacoby** [comment]
FROST Server should support all MQTT options as defined in the SensorThings API standard which includes creation of Observations via MQTT as described [here](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#86).
This functionality is also tested in our extended test suite https://github.com/FraunhoferIOSB/ets-sta10/blob/master/src/main/java/org/opengis/cite/sta10/createObservationsViaMQTT/Capability7Test.java
You can also use this code to check if you are using the right topic name and payload.

If you discover that this is not working for your FROST Server, please provide additional details on the exception/behavior. 

If you think the MQTT interface should support additional operations besides creating observations and querying data, please create an issue for the standard itself under https://github.com/opengeospatial/sensorthings/issues
