### ISSUE TITLE
 plugins.coreModel.idType

### ISSUE THREAD

**Issue by ksonda** [FraunhoferIOSB/FROST-Server#959]
In the newer versions of FROST, I'm trying to enable string/uuid @iot.ids

In my docker-compose (which uses image: fraunhoferiosb/frost-server:2.0) I have added these two settings.

```
- persistence_idGenerationMode=ServerAndClientGenerated
- plugins_coreModel_idType=STRING
```

FROST and the DB start, and I can interact with FROST, but the behavior appears to be as if I had set `plugins_coreModel_idType=LONG`. I can set my own @iot.id but only if they are integers. The docker logs for FROST include blocks like this for each table in the core model.

```
Running Changeset: liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-1::scf

13:17:17.013 [http-nio-8080-exec-1] INFO             liquibase.changelog - Table SENSORS created

13:17:17.015 [http-nio-8080-exec-1] INFO             liquibase.changelog - ChangeSet liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-1::scf ran successfully in 8ms

Running Changeset: liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-2::scf

13:17:17.022 [http-nio-8080-exec-1] INFO             liquibase.changelog - Columns ID(BIGINT) added to SENSORS

13:17:17.023 [http-nio-8080-exec-1] INFO             liquibase.changelog - ChangeSet liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-2::scf ran successfully in 6ms

Running Changeset: liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-3::scf

13:17:17.025 [http-nio-8080-exec-1] INFO             liquibase.changelog - Marking ChangeSet: liquibase/plugincoremodel/tableSensors.xml::2021-01-01-sensors-3::scf ran despite precondition failure due to onFail='MARK_RAN': 

          liquibase/plugincoremodel/tables.xml : Expected changelog property 'id-Sensor' to have a value of 'STRING'.  Got 'LONG'

          liquibase/plugincoremodel/tables.xml : Expected changelog property 'id-Sensor' to have a value of 'UUID'.  Got 'LONG'
```

Any advice? I am setting the coreModel idType setting incorrectly?

**Comment by hylkevds** [comment]
I suspect you have the option:
```
persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong
```
For backwards-compatibility, if it finds that old key (specifically `longid.PostgresPersistenceManagerLong`) it sets all idType options to Long.
Make sure you use `de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager`.
If that is not it, can you give the full log output?

**Comment by ksonda** [comment]
Thanks.

FYI in https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html the setting is given as:

`de.fraunhofer.iosb.ilt.sta.persistence.pgjooq.PostgresPersistenceManager`  (`sta` instead of `frostserver`). This was my problem starting from scratch

**Comment by hylkevds** [comment]
Oops, old version of the name there :)
Fill fix that, thanks!
