### ISSUE TITLE
Using $select and $resultMetadata not possible?

### ISSUE THREAD

**Issue by dirk-ecker** [FraunhoferIOSB/FROST-Server#968]
I try to get all locations with name and their metadata with the following request:

`https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations?$select=name&$resultMetadata=full`

gives me

```
{
  "value": [
    {
      "name": "Location_ObservedSoilProfile.1948-001386"
    },
...
```
The metadata is missing, okay maybe it collides with $select so get one of it into the $select, here the link to the things:

`https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations?$select=name,Things@iot.navigationLink`

gives me

```
{
  "code": 400,
  "type": "error",
  "message": "Invalid property 'Things@iot.navigationLink' found in select, for entity type Location"
}
```

Okay, what about the self link:

`https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations?$select=name,@iot.selfLink`

gives me 

```
{
  "value": [
    {
      "name": "Location_ObservedSoilProfile.1948-001386",
      "@iot.selfLink": "https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations(39)"
    },
```
means works as expected.

I can request this

`https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations?$select=name&$expand=Things($select=@iot.selfLink)`

gives me

```

  "value": [
    {
      "name": "Location_ObservedSoilProfile.1948-001386",
      "Things": [
        {
          "@iot.selfLink": "https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Things(39)"
        },
        {
          "@iot.selfLink": "https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Things(89)"
        }
      ]
    },
    {
```
but that is not what i want.

Am I missing something here?

**Comment by hylkevds** [comment]
The way $select works on navigationLinks is a bit hidden in the [OData spec](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionselect):

> If the select item is a navigation property, then the corresponding navigation link is represented in the response. If the navigation property also appears in an [$expand](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionexpand) query option, then it is additionally represented as inline content.

The navigation property in this case is `Things`, so to get the NavigationLink to the Things you would do:
https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Locations?$select=name,Things

**Comment by dirk-ecker** [comment]
Thank you for clarifying/helping.

OData is not very self explanatory in this case and even worse you are asking for Thing and you get Thing@... what kicks generic programming a little.

Maybe it is a good idea to add an example to your exelent FROST-Server Documentation.
