### ISSUE TITLE
MQTT Test

### ISSUE THREAD

**Issue by tadolphi** [FraunhoferIOSB/FROST-Server#99]
Hi,

i am new to MQTT and would like to check it out. Currently i am using the eclipse paho client and would like to connect to my FROST Server via subscribe and afterwards using the mqtt publish to publish an observation to the server. Do you have an example how to connect and subscribe to the FROST Server? Eclipse Paho states all the time that it cannot connect to the server. It is installed on a windows system inside an VM running UBUNTU. I used the full docker image you are providing. So am i missing something? maybe to open some ports or mapping of some required ports for mqtt? Any help is highly appreciated.
Thanks Thomas

**Comment by tadolphi** [comment]
Hi,

yes the http interface works. i can see the intial page when i call 
http://xxx.xxx.xxx.xxx:8080/FROST-Server/v1.0/
I used that docker:
https://hub.docker.com/r/fraunhoferiosb/frost-server/

so when i use that page
https://www.eclipse.org/paho/clients/js/utility/
the host is: xxx.xxx.xxx.xxx
port is: 1883 and the rest is not needed right?
but i still got the error. Connection failed: AMQJS0007E Socket error:undefined.

**Comment by hylkevds** [comment]
Ok, you have the combined package that includes MQTT, that's good.

That web-client can only connect using websockets. For that you have to use port 9876 (and probably turn of tls), but I have not had success connecting using it.

This client does work for me, using websockets, on port 9876:
http://www.hivemq.com/demos/websocket-client/

**Comment by hylkevds** [comment]
Closing issue, since there are no more responses. I guess it works?
