### ISSUE TITLE
Try to figure out service root url if not specified

### ISSUE THREAD

**Issue by hylkevds** [FraunhoferIOSB/FROST-Server#991]
If the service root url is not specified, FROST-Server could try to figure it out itself, using the `X-Forwarded-For` header and the requests url.

**Comment by hylkevds** [comment]
The problem is that the `x-forwarded-*` headers don't contain the path of the request, so if the reverse proxy does url-rewriting, FROST won't know it and will generate wrong paths.

**Comment by DerLinne** [comment]
Perhaps you can define an addition parameter for the path - the Reverse Proxy, or in our case, the API Gateway of the CIVITAS/CORE Platform could set this easily.

Could this be an Idea?

X-Forwarded-For -> https://subdomain.domain.tld
Frost-Base-Path -> /frost/base/path

This would be very very helpful!

**Comment by hylkevds** [comment]
I'm thinking of using `X-Forwarded-Path` for that. There are quite a few hits when searching for that, so it is the most likely to become a standard at some point.
Though it should also not be too hard to make configurable.

**Comment by DerLinne** [comment]
Sounds good - if you have any news on this, we can directly test that

**Comment by hylkevds** [comment]
You can now test it using 2.4.0-SNAPSHOT.

New settings:
* **http.requestDecoder.autodetectRootUrl:** Since 2.4.0  
  If true, FROST will try to automatically detect the serviceRootUrl. Default `false` if the serviceRootUrl is not set, otherwise `true`.
* **http.requestDecoder.useXForwardedHeaders:** Since 2.4.0  
  If true, FROST will use the X-Forwarded headers to detect the serviceRootUrl. Default `false`.
* **http.requestDecoder.XForwardedHostHeader:** Since 2.4.0  
  The name of the X-Forwarded-Host equivalent header. Default `X-Forwarded-Host`.
* **http.requestDecoder.XForwardedPathHeader:** Since 2.4.0  
  The name of the X-Forwarded-Path equivalent header. Default `X-Forwarded-Path`.
* **http.requestDecoder.XForwardedPortHeader:** Since 2.4.0  
  The name of the X-Forwarded-Port equivalent header. Default `X-Forwarded-Port`.
* **http.requestDecoder.XForwardedProtoHeader:** Since 2.4.0  
  The name of the X-Forwarded-Proto equivalent header. Default `X-Forwarded-Proto`.
